/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
struct S {
   uint32_t a ;
   uint16_t b ;
};
static uint32_t g_out = 0U;
int main(void)
{
  int __retres;
  uint8_t buf[sizeof(struct S)];
  struct S s = {.a = 0x11223344U, .b = (uint16_t)0x5566U};
  g_out = ((uint32_t)sizeof(uint8_t [sizeof(struct S)]) ^ s.a) ^ (uint32_t)s.b;
  __retres = (int)(g_out & 0xFFU);
  return __retres;
}


