/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g = 0U;
static void step_slice_1(uint32_t x)
{
  g = (g + x) ^ 0x55U;
  return;
}

void main(void)
{
  uint32_t i = 0U;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  i ++;
  /*@ \slicing::slice_preserve_stmt ; */
  step_slice_1(i);
  return;
}


