/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g = 0U;
static void foo_slice_1(uint32_t x)
{
  g = (g + x) ^ 0x5AU;
  return;
}

void main(void)
{
  foo_slice_1(3U);
  return;
}


