/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_arr[3] = {1U, 2U, 3U};
static uint32_t g_out = 0U;
static void func_1_slice_1(void)
{
  g_arr[1] += 7U;
  g_out = g_arr[1];
  uint32_t IRR_SENTINEL_RW = 0U;
  IRR_SENTINEL_RW = (IRR_SENTINEL_RW + g_arr[2]) ^ 0xBEEFU;
  return;
}

void main(void)
{
  func_1_slice_1();
  return;
}


