/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_arr[3] = {1U, 2U, 3U};
static void func_1_slice_1(void)
{
  g_arr[1] += 7U;
  return;
}

void main(void)
{
  func_1_slice_1();
  return;
}


