#include <stdio.h>
/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_add_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 + (int)si2);
  return __retres;
}

static int16_t safe_rshift_func_int16_t_s_u_slice_1(int16_t left)
{
  int16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (int16_t)tmp;
  return __retres;
}

static uint64_t safe_sub_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int32_t g_2 = (int32_t)1L;
static uint32_t g_175 = (uint32_t)0UL;
static int16_t g_203 = (int16_t)0x07C0L;
static uint16_t g_301 = (uint16_t)0xC571L;
static uint32_t *g_1101 = & g_175;
static uint16_t *g_1235[6][6] =
  {{& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301}};
static uint16_t **g_1234 = & g_1235[2][1];
static int32_t *g_1247 = & g_2;
static uint32_t **g_1447 = & g_1101;
static int32_t g_2465 = (int32_t)0x2764EB57L;
static int16_t *g_2774 = & g_203;
static int16_t **g_2773 = & g_2774;
static int16_t **g_2778 = & g_2774;
static int16_t * const * const **g_4404 = (int16_t * const * const **)0;
static int16_t * const * const ***g_4403 = & g_4404;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  uint64_t tmp_50;
  int16_t tmp_49;
  int16_t tmp_42;
  uint16_t l_9 = (uint16_t)0x0CB8L;
  int32_t l_4276 = (int32_t)0xF414069CL;
  uint8_t l_4432 = (uint8_t)0x35L;
  {
    uint64_t l_4274;
    int8_t tmp_40;
    int tmp_39;
    int32_t tmp_35;
    int32_t *l_4263 = & g_2465;
    l_4274 = 1UL;
    tmp_35 = (int32_t)l_4274;
    *l_4263 = tmp_35;
    tmp_39 = 1;
    tmp_40 = safe_add_func_int8_t_s_s_slice_1((int8_t)((int16_t *)0 != *g_2773),
                                              (int8_t)tmp_39);
    l_4276 = (int32_t)tmp_40;
    goto break_cont_1;
  }
  break_cont_1:
  *(*g_1234) = (uint16_t)((int)*(*g_1234) ^ l_4276);
  tmp_49 = safe_rshift_func_int16_t_s_u_slice_1((int16_t)(! 6UL));
  tmp_50 = safe_sub_func_uint64_t_u_u_slice_1((uint64_t)tmp_49,
                                              (uint64_t)l_4432);
  tmp_42 = (int16_t)tmp_50;
  *(*g_2778) = tmp_42;
  *g_1247 = (int32_t)l_9;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_203: %d\n", (int)g_203);
    printf("g_3968: 未在切片中定义\n");
    printf("g_2465: %d\n", g_2465);
    printf("g_1801: 未在切片中定义\n");
    printf("g_2: %d\n", g_2);

  __retres = 0;
  return __retres;
}


