/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
struct Pair {
   uint32_t a ;
   uint32_t b ;
};
static uint32_t g_out = 0U;
int main(void)
{
  int __retres;
  uint8_t buf[sizeof(struct Pair)];
  g_out = (uint32_t)sizeof(uint8_t [sizeof(struct Pair)]);
  __retres = (int)(g_out & 0xFFU);
  return __retres;
}


