/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
struct Pair {
   uint32_t a ;
   uint32_t b ;
};
static uint32_t g_out = 0U;
static void write_bytes_slice_1(uint8_t *dst, struct Pair const *p)
{
  memcpy((void *)dst,(void const *)p,sizeof(struct Pair));
  return;
}

static uint32_t read_u32_slice_1(uint8_t const *src)
{
  uint32_t v;
  memcpy((void *)(& v),(void const *)src,sizeof(uint32_t));
  return v;
}

int main(void)
{
  int __retres;
  uint8_t buf[sizeof(struct Pair)];
  struct Pair p = {.a = 0x11223344U, .b = 0x55667788U};
  memset((void *)(buf),0,sizeof(uint8_t [sizeof(struct Pair)]));
  write_bytes_slice_1(buf,(struct Pair const *)(& p));
  uint32_t x = read_u32_slice_1((uint8_t const *)(buf));
  uint32_t y = read_u32_slice_1((uint8_t const *)(& buf[4]));
  g_out = x ^ (y + 7U);
  __retres = (int)(g_out & 0xFFU);
  return __retres;
}


