/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int EINVAL_realsmith_onl0Q = 7;
int realsmith_onl0Q_slice_1(void)
{
  int __retres;
  __retres = - EINVAL_realsmith_onl0Q;
  return __retres;
}

int realsmith_proxy_5UmS4_slice_1(int p_3_TSZHk)
{
  int proxy_ret_unTnt = realsmith_onl0Q_slice_1();
  return proxy_ret_unTnt;
}

int realsmith_lEWHn_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

static int realsmith_867IV_slice_1(void) __attribute__((__used__));
static int realsmith_867IV_slice_1(void)
{
  int __retres;
  __retres = 0;
  goto return_label;
  return_label: return __retres;
}

int realsmith_proxy_3HCtS_slice_1(char p_0_KC70N, unsigned long p_1_3b1kv)
{
  char proxy_eU9Gf[14] =
    {(char)22,
     p_0_KC70N,
     (char)23,
     (char)70,
     p_0_KC70N,
     (char)30,
     p_0_KC70N,
     p_0_KC70N,
     p_0_KC70N,
     (char)75,
     (char)32,
     (char)74,
     p_0_KC70N,
     (char)52};
  int proxy_ret_JKqTw = realsmith_867IV_slice_1();
  return proxy_ret_JKqTw;
}

unsigned char IFLA_XDP_PROG_ID_realsmith_vnYZI = (unsigned char)10;
static unsigned char realsmith_vnYZI_slice_1(void) __attribute__((__used__));
static unsigned char realsmith_vnYZI_slice_1(void)
{
  unsigned char __retres;
  __retres = IFLA_XDP_PROG_ID_realsmith_vnYZI;
  return __retres;
}

static int *realsmith_69zym_slice_1(int *obj) __attribute__((__used__));
static int *realsmith_69zym_slice_1(int *obj)
{
  int *__retres;
  int *ret;
  ret = obj;
  __retres = ret;
  return __retres;
}

int realsmith_proxy_zyN5i_slice_1(int p_0_E4sZi)
{
  int __retres;
  int *proxy_ret_4bDpW = realsmith_69zym_slice_1(& p_0_E4sZi);
  __retres = *proxy_ret_4bDpW;
  return __retres;
}

int FASTTRAP_T_COMMON_realsmith_ExGdr = 7;
static int realsmith_ExGdr_slice_1(void) __attribute__((__used__));
static int realsmith_ExGdr_slice_1(void)
{
  int __retres;
  __retres = FASTTRAP_T_COMMON_realsmith_ExGdr;
  return __retres;
}

static int realsmith_j2Mo2_slice_1(void) __attribute__((__used__));
static int realsmith_j2Mo2_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_3zscM_slice_1(void)
{
  int proxy_ret_Mdmdx = realsmith_j2Mo2_slice_1();
  return proxy_ret_Mdmdx;
}

int realsmith_eYDt4_slice_1(void)
{
  int __retres;
  int val;
  val = 1;
  __retres = ! val;
  return __retres;
}

static int realsmith_b74WA_slice_1(void) __attribute__((__used__));
static int realsmith_b74WA_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_yi2G2_slice_1(void)
{
  int proxy_ret_WLEWG = realsmith_b74WA_slice_1();
  return proxy_ret_WLEWG;
}

int MEDIUM_realsmith_81BZW = 18;
int realsmith_81BZW_slice_1(void)
{
  int __retres;
  __retres = MEDIUM_realsmith_81BZW;
  return __retres;
}

static int realsmith_dHzH8_slice_1(void) __attribute__((__used__));
static int realsmith_dHzH8_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_fKzHC_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int R_ANAL_COND_UNKNOWN_realsmith_Eaotj = -2;
static int realsmith_Eaotj_slice_1(void) __attribute__((__used__));
static int realsmith_Eaotj_slice_1(void)
{
  int __retres;
  __retres = R_ANAL_COND_UNKNOWN_realsmith_Eaotj;
  return __retres;
}

int realsmith_FnQVv_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_4Gi9F_slice_1(void)
{
  int proxy_ret_zFW5W = realsmith_FnQVv_slice_1();
  return proxy_ret_zFW5W;
}

static char const *realsmith_C3aLa_slice_1(void) __attribute__((__used__));
static char const *realsmith_C3aLa_slice_1(void)
{
  char const *__retres;
  __retres = "struct Function {\n  var (*func)(var);\n};\n";
  return __retres;
}

char realsmith_proxy_snjLM_slice_1(void)
{
  char __retres;
  char *proxy_ret_LfdNh = realsmith_C3aLa_slice_1();
  __retres = *proxy_ret_LfdNh;
  return __retres;
}

static int realsmith_FidWZ_slice_1(void) __attribute__((__used__));
static int realsmith_FidWZ_slice_1(void)
{
  int __retres;
  __retres = 6;
  return __retres;
}

__inline static unsigned int realsmith_okX1Q_slice_1(unsigned int x,
                                                     unsigned int n) __attribute__((
__used__));
__inline static unsigned int realsmith_okX1Q_slice_1(unsigned int x,
                                                     unsigned int n)
{
  unsigned int __retres;
  __retres = (x >> n) | (x << ((unsigned int)32 - n));
  return __retres;
}

static int realsmith_ArIuJ_slice_1(void) __attribute__((__used__));
static int realsmith_ArIuJ_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_k7iVT_slice_1(void)
{
  int proxy_MbqwT[16];
  int proxy_ret_aNfeO = realsmith_ArIuJ_slice_1();
  return proxy_ret_aNfeO;
}

static int8_t safe_add_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 + (int)si2);
  return __retres;
}

static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_u_slice_1(int8_t left,
                                                  unsigned int right)
{
  int8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else 
    if ((int)left > 127 >> right) tmp = (int)left;
    else tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_rshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right >= 32) tmp = (int)left; else tmp = (int)left >> right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_rshift_func_int8_t_s_u_slice_1(int8_t left,
                                                  unsigned int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left >> right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_unary_minus_func_int16_t_s_slice_1(int16_t si)
{
  int16_t __retres;
  __retres = (int16_t)(- ((int)si));
  return __retres;
}

static int16_t safe_sub_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 - (int)si2);
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_mod_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1;
  else 
    if ((int)si1 == -32768) tmp = (int)si1 % (int)si2;
    else tmp = (int)si1 % (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_add_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si1 > 0) goto _LAND_0;
  else {
    _LAND_0: ;
    if (si1 < 0) tmp = si1 + si2; else tmp = si1 + si2;
  }
  return tmp;
}

static int64_t safe_add_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  if (si1 > (int64_t)0) {
    if (si2 > (int64_t)0) {
      if ((long long)si1 > 9223372036854775807LL - (long long)si2) tmp = si1;
      else goto _LAND_0;
    }
    else goto _LAND_0;
  }
  else {
    _LAND_0: ;
    if (si1 < (int64_t)0) tmp = si1 + si2; else tmp = si1 + si2;
  }
  return tmp;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  if (((long long)(si1 ^ si2) & ((((long long)si1 ^ ((long long)(si1 ^ si2) & ~ 9223372036854775807LL)) - (long long)si2) ^ (long long)si2)) < (long long)0) 
    tmp = si1;
  else tmp = si1 - si2;
  return tmp;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint8_t safe_mod_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  int tmp;
  tmp = (int)ui1 % (int)ui2;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint8_t safe_lshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else 
    if ((int)left > 255 >> right) tmp = (int)left;
    else tmp = (int)left << right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint8_t safe_rshift_func_uint8_t_u_s_slice_1(uint8_t left, int right)
{
  uint8_t __retres;
  int tmp;
  tmp = (int)left >> right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint8_t safe_rshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_add_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint16_t safe_mod_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  int tmp;
  if ((int)ui2 == 0) tmp = (int)ui1; else tmp = (int)ui1 % (int)ui2;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else 
    if ((int)left > 65535 >> right) tmp = (int)left;
    else tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint16_t safe_rshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint64_t safe_sub_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static uint64_t safe_mod_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  tmp = ui1 % ui2;
  return tmp;
}

static uint64_t safe_div_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  if (ui2 == (uint64_t)0) tmp = ui1; else tmp = ui1 / ui2;
  return tmp;
}

static int32_t g_4[2] = {(int32_t)(-8L), (int32_t)(-8L)};
static int32_t g_44 = (int32_t)0x635D5AA0L;
static uint8_t g_76 = (uint8_t)0x90L;
static uint8_t *g_75 = & g_76;
static uint64_t g_80 = (uint64_t)0x737198010E05D1EELL;
static int64_t g_85 = -1L;
static uint64_t g_89 = (uint64_t)0x8A5C6425F0F443C0LL;
static uint64_t *g_88 = & g_89;
static uint32_t g_103[9][2] =
  {{(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL},
   {(uint32_t)0UL, (uint32_t)0UL}};
static int32_t g_128 = (int32_t)(-3L);
static int8_t g_165 = (int8_t)(-7L);
static int8_t g_166 = (int8_t)(-1L);
static uint64_t g_167 = (uint64_t)0xDB116D794BBEC019LL;
static uint32_t *g_248 = & g_103[0][1];
static uint32_t **g_247 = & g_248;
static uint32_t ***g_246 = & g_247;
static int32_t g_277 = (int32_t)0x9A4662F5L;
static int16_t g_326 = (int16_t)(-10L);
static int8_t g_327[3][10] =
  {{(int8_t)0x96L,
    (int8_t)0x76L,
    (int8_t)0x15L,
    (int8_t)(-8L),
    (int8_t)0L,
    (int8_t)(-8L),
    (int8_t)0x15L,
    (int8_t)0x76L,
    (int8_t)0x96L,
    (int8_t)1L},
   {(int8_t)0x96L,
    (int8_t)5L,
    (int8_t)0x78L,
    (int8_t)(-1L),
    (int8_t)(-8L),
    (int8_t)1L,
    (int8_t)1L,
    (int8_t)(-8L),
    (int8_t)(-1L),
    (int8_t)0x78L},
   {(int8_t)1L,
    (int8_t)1L,
    (int8_t)(-8L),
    (int8_t)(-1L),
    (int8_t)0x78L,
    (int8_t)5L,
    (int8_t)0x96L,
    (int8_t)0x60L,
    (int8_t)0x96L,
    (int8_t)5L}};
static uint16_t g_329 = (uint16_t)0x6EC9L;
static uint16_t g_333 = (uint16_t)0xC21DL;
static uint8_t g_336 = (uint8_t)0UL;
static uint8_t g_364 = (uint8_t)252UL;
static int32_t g_379[6] =
  {(int32_t)1L,
   (int32_t)1L,
   (int32_t)1L,
   (int32_t)1L,
   (int32_t)1L,
   (int32_t)1L};
static uint32_t g_450 = (uint32_t)0x3600E5B1L;
static uint16_t *g_537 = & g_329;
static uint16_t **g_536 = & g_537;
static uint32_t ****g_578 = & g_246;
static uint32_t *****g_577 = & g_578;
static int16_t *g_634 = & g_326;
static int64_t g_713 = (int64_t)0x09D06D2233501648LL;
static uint64_t g_963 = (uint64_t)0x54AE6C7109BAEE24LL;
static int64_t g_1254 = -1L;
static int8_t *g_1777 = & g_327[2][8];
static int8_t **g_1776[2] = {& g_1777, & g_1777};
static int8_t ***g_1775 = & g_1776[1];
static int32_t g_1836 = (int32_t)0xFB7837E0L;
static int64_t g_2107 = (int64_t)0x96B360636424A09ELL;
static int32_t *g_2499 = & g_277;
static void func_1_slice_1(void);

static void func_10_slice_1(uint32_t p_11, uint16_t p_12);

static void func_25_slice_1(uint64_t p_26, uint32_t p_28, uint32_t const p_29);

static void func_30_slice_1(int32_t * const p_31, uint32_t p_32);

static int32_t *func_33_slice_1(void);

static int8_t func_54_slice_1(uint64_t p_55, int32_t * const p_56);

static uint16_t func_57_slice_1(void);

static void func_60_slice_1(int32_t *p_61, int32_t *p_62, int32_t *p_63,
                            int32_t p_64);

static int32_t *func_65_slice_1(void);

static void func_69_slice_1(uint32_t p_70, uint8_t *p_74);

static void func_1_slice_1(void)
{
  uint32_t l_7;
  int tmp_24;
  int32_t *l_3 = g_4;
  int64_t l_2964 = (int64_t)0xEA973CF56FD6E84ALL;
  tmp_24 = realsmith_fKzHC_slice_1();
  func_10_slice_1((uint32_t)(((tmp_24 + g_4[1]) - -8) + g_4[1]),
                  (uint16_t)g_4[0]);
  {
    uint8_t const l_2939 = 0x2BL;
    uint32_t *tmp;
    uint64_t **tmp_2;
    uint8_t tmp_1;
    int tmp_5;
    uint64_t tmp_4;
    uint8_t tmp_14;
    uint8_t tmp_13;
    uint8_t tmp_12;
    int8_t tmp_11;
    unsigned int tmp_8;
    int16_t tmp_10;
    uint32_t *tmp_9;
    int16_t tmp_7;
    uint32_t *l_2941[8][1][3] =
      {{{& l_7, (uint32_t *)0, (uint32_t *)0}},
       {{& g_103[2][0], & g_103[2][0], (uint32_t *)0}},
       {{& g_450, (uint32_t *)0, (uint32_t *)0}},
       {{(uint32_t *)0, & l_7, (uint32_t *)0}},
       {{& g_450, & l_7, & g_450}},
       {{& g_103[2][0], (uint32_t *)0, (uint32_t *)0}},
       {{& g_103[2][0], & g_103[2][0], (uint32_t *)0}},
       {{& g_450, (uint32_t *)0, (uint32_t *)0}}};
    uint64_t **l_2949 = & g_88;
    int32_t l_2965 = (int32_t)0x67A28533L;
    tmp = l_2941[2][0][2];
    *l_3 = tmp == l_2941[3][0][0];
    tmp_2 = l_2949;
    tmp_1 = (uint8_t)(tmp_2 != (uint64_t **)0);
    *g_75 = tmp_1;
    tmp_5 = realsmith_lEWHn_slice_1();
    tmp_4 = (uint64_t)((((tmp_5 + (int)*g_88) + ((int)g_2107 - 1680122014)) + g_4[1]) - 1270792101) + *g_88;
    *g_88 = tmp_4;
    tmp_8 = realsmith_okX1Q_slice_1((unsigned int)*g_88 + (unsigned int)(-1270792088),
                                    (unsigned int)*g_88 + (unsigned int)(-1270792101));
    tmp_9 = & l_7;
    tmp_10 = safe_mul_func_int16_t_s_s_slice_1((int16_t)(l_2941[2][0][2] == tmp_9),
                                               (int16_t)l_2964);
    tmp_11 = safe_add_func_int8_t_s_s_slice_1((int8_t)tmp_10,
                                              (int8_t)((int32_t)((long)(
                                                                 (((tmp_8 + (unsigned int)l_2965) + (unsigned int)*g_88) + (
                                                                  (unsigned int)l_2964 - (unsigned int)1876355146)) + (
                                                                 (unsigned int)g_2107 - (unsigned int)1680122014)) - 3361817824) + l_2965));
    tmp_12 = safe_rshift_func_uint8_t_u_s_slice_1((uint8_t)((int)l_2939 | (int)tmp_11),
                                                  3);
    tmp_13 = safe_rshift_func_uint8_t_u_s_slice_1(tmp_12,*l_3);
    tmp_14 = safe_lshift_func_uint8_t_u_u_slice_1(tmp_13,(unsigned int)5);
    tmp_7 = safe_mod_func_int16_t_s_s_slice_1((int16_t)*l_3,(int16_t)tmp_14);
    *g_634 = tmp_7;
  }
  return;
}

static void func_10_slice_1(uint32_t p_11, uint16_t p_12)
{
  uint32_t const ****l_2830 = (void*)0;
  uint32_t const *****l_2829 = & l_2830;
  {
    uint32_t const *****l_2834;
    int tmp_137;
    uint16_t const ****l_2846 = (uint16_t const ****)0;
    tmp_137 = realsmith_proxy_5UmS4_slice_1((int)p_12 + -65472);
    func_25_slice_1((uint64_t)g_4[0],(uint32_t)p_12,
                    (uint32_t)((int)((uint16_t)((((tmp_137 + (int)p_12) + (int)p_11) + g_4[0]) - 65505)) + (int)p_12));
    {
      int32_t l_2747 = (int32_t)(-1L);
      goto break_cont_1;
      break_cont_1: ;
      (*(*(*g_246))) ++;
      if (1) goto _LOR;
      else 
        if (1) {
          _LOR: ;
          goto _LAND;
        }
        else {
          _LAND:
          {
            uint32_t * const **** const l_2835 = (void*)0;
            int16_t tmp_91;
            uint16_t tmp_88;
            uint16_t tmp_87;
            int tmp_89;
            int tmp_90;
            uint64_t tmp_100;
            int8_t tmp_99;
            uint32_t tmp_95;
            int tmp_98;
            uint16_t tmp_97;
            int8_t *l_2856 = & g_166;
            tmp_87 = (uint16_t)0xE2AAL;
            tmp_88 = safe_rshift_func_uint16_t_u_u_slice_1(tmp_87,
                                                           (unsigned int)4);
            tmp_89 = realsmith_FidWZ_slice_1();
            tmp_90 = realsmith_Eaotj_slice_1();
            l_2834 = l_2829;
            tmp_91 = safe_unary_minus_func_int16_t_s_slice_1((int16_t)(
                                                             ((unsigned int)(
                                                              (int)tmp_88 & (
                                                              (int)((uint16_t)(
                                                              (tmp_89 + (int)p_12) - 65534)) + (int)p_12)) | (
                                                              (uint32_t)(
                                                              (tmp_90 + (int)p_11) - -10) + p_11)) > (unsigned int)(
                                                             (void *)l_2834 == (void *)l_2835)));
            *g_2499 = (int32_t)tmp_91;
            *l_2856 = (int8_t)((long)*l_2856 | 0x62L);
            tmp_95 = *(*(*(*(*g_577))));
            tmp_97 = (uint16_t)l_2747;
            *g_537 = tmp_97;
            tmp_98 = 1;
            tmp_99 = safe_mul_func_int8_t_s_s_slice_1(*g_1777,
                                                      (int8_t)(tmp_95 >= (uint32_t)tmp_98));
            tmp_100 = safe_sub_func_uint64_t_u_u_slice_1((uint64_t)tmp_99,
                                                         (uint64_t)((
                                                                    l_2846 == (uint16_t const ****)0) != (int)*l_2856));
            *g_2499 = (int32_t)((unsigned long)*g_2499 & tmp_100);
          }
        }
      g_76 = (uint8_t)0;
      goto break_cont_2;
    }
    break_cont_2: ;
  }
  return;
}

static void func_25_slice_1(uint64_t p_26, uint32_t p_28, uint32_t const p_29)
{
  int32_t *l_40[4];
  int i;
  int8_t tmp_6;
  uint16_t tmp_4;
  int32_t *tmp_2;
  int8_t tmp;
  int32_t *tmp_8;
  int8_t *l_1386 = & g_327[2][8];
  i = 0;
  while (i < 4) {
    l_40[i] = g_4;
    i ++;
  }
  func_69_slice_1(p_29,g_75);
  tmp_2 = func_65_slice_1();
  func_60_slice_1(l_40[3],tmp_2,& g_379[5],(int32_t)p_28);
  tmp_4 = func_57_slice_1();
  tmp = (int8_t)((long)((long)tmp_4 < 8L) <= 0x13100FB3L);
  *l_1386 = tmp;
  tmp_6 = func_54_slice_1(0UL,l_40[3]);
  tmp_8 = func_33_slice_1();
  func_30_slice_1(tmp_8,(uint32_t)((uint64_t)tmp_6 == p_26));
  return;
}

static void func_30_slice_1(int32_t * const p_31, uint32_t p_32)
{
  uint16_t tmp_8;
  int8_t tmp_7;
  int tmp_6;
  int tmp;
  int8_t tmp_5;
  int tmp_3;
  char tmp_4;
  int32_t tmp_56;
  uint32_t l_2192[9] =
    {(uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L,
     (uint32_t)0x8228DD22L};
  int32_t *l_2197 = & g_277;
  int16_t l_2583 = (int16_t)0x1BF8L;
  tmp = realsmith_proxy_3HCtS_slice_1((char)((int)((char)l_2192[7]) + -74),
                                      (unsigned long)l_2192[7] + (unsigned long)(-2183716109));
  *(*(*g_246)) = *g_248;
  tmp_3 = 0;
  tmp_4 = realsmith_proxy_snjLM_slice_1();
  tmp_5 = safe_add_func_int8_t_s_s_slice_1((int8_t)((unsigned int)tmp_3 | (
                                                    (uint32_t)(((((((int)tmp_4 + (int)((char)p_32)) + (int)((char)*g_248)) + (
                                                                  (int)((char)l_2192[7]) - 34)) + (int)((char)*p_31)) + (int)((char)g_4[0])) - 99) + p_32)),
                                           (int8_t)0L);
  if (((uint32_t)((tmp + (int)l_2192[7]) - -2111251166) + l_2192[7]) & (unsigned int)tmp_5) 
    tmp_6 = 1;
  else tmp_6 = 0;
  tmp_7 = safe_lshift_func_int8_t_s_u_slice_1((int8_t)tmp_6,
                                              (unsigned int)*g_75);
  tmp_8 = safe_mod_func_uint16_t_u_u_slice_1((uint16_t)tmp_7,(uint16_t)(-2L));
  *l_2197 = (int32_t)tmp_8;
  tmp_56 = *l_2197;
  if (tmp_56) goto _LOR_0;
  else 
    if (*(*(*g_1775))) {
      _LOR_0:
      {
        int32_t l_2265;
        g_85 = (int64_t)10;
        goto break_cont_3;
        break_cont_3: g_89 = (uint64_t)0;
        {
          uint64_t tmp_39;
          int64_t tmp_38;
          uint64_t tmp_37;
          int8_t tmp_36;
          uint16_t tmp_32;
          int32_t tmp_31;
          int32_t tmp_29;
          int tmp_35;
          int32_t *l_2545 = & g_44;
          tmp_29 = (int32_t)(*(*(*(*(*g_577)))) & (unsigned int)(0xC27FL > (long)p_32));
          tmp_31 = safe_add_func_int32_t_s_s_slice_1((int32_t)((unsigned long long)(
                                                               (unsigned long long)tmp_29 < 0xF6FF76FE41880D0CLL) | 0xF59DF16FFCA76E87LL),
                                                     (int32_t)0x08404EE2L);
          tmp_32 = safe_add_func_uint16_t_u_u_slice_1((uint16_t)tmp_31,
                                                      (uint16_t)p_32);
          tmp_35 = 0;
          tmp_36 = safe_mul_func_int8_t_s_s_slice_1((int8_t)tmp_35,
                                                    (int8_t)tmp_32);
          tmp_37 = safe_mod_func_uint64_t_u_u_slice_1((uint64_t)tmp_36,
                                                      (uint64_t)5L);
          tmp_38 = safe_sub_func_int64_t_s_s_slice_1((long)(p_32 | (unsigned int)(
                                                            tmp_37 > (uint64_t)0L)) & -1L,
                                                     (int64_t)p_32);
          tmp_39 = safe_div_func_uint64_t_u_u_slice_1(3UL,(uint64_t)tmp_38);
          l_2265 = (int32_t)tmp_39;
          *l_2545 ^= l_2265;
          goto break_cont_4;
        }
        break_cont_4: goto return_label;
      }
    }
  *g_88 ^= (unsigned long)((unsigned long)l_2583 >= 4294967287UL);
  if (! *g_88) (*g_88) --;
  return_label: return;
}

static int32_t *func_33_slice_1(void)
{
  int32_t *__retres;
  __retres = g_4;
  return __retres;
}

static int8_t func_54_slice_1(uint64_t p_55, int32_t * const p_56)
{
  int8_t __retres;
  int32_t l_1390;
  int32_t l_1407[2][2][5];
  unsigned char tmp_49;
  int16_t tmp_63;
  int tmp_50;
  int tmp_52;
  int tmp_62;
  int8_t tmp_54;
  int tmp_53;
  int tmp_64;
  int64_t l_1387 = (int64_t)0xA551717D732CAD3ELL;
  int8_t *l_1395 = & g_327[2][8];
  int32_t *l_2182 = & g_379[5];
  tmp_49 = realsmith_vnYZI_slice_1();
  tmp_50 = realsmith_proxy_zyN5i_slice_1(*p_56 + -52);
  tmp_52 = realsmith_proxy_yi2G2_slice_1();
  l_1390 = (int32_t)((uint64_t)(((tmp_52 + (int)p_55) + (int)l_1387) - 1932307775) + p_55);
  tmp_53 = realsmith_dHzH8_slice_1();
  *l_1395 = (int8_t)((int)*l_1395 ^ (((tmp_53 + g_379[5]) - 1) + g_379[5]));
  tmp_54 = safe_rshift_func_int8_t_s_s_slice_1(*l_1395,2);
  if (tmp_54) tmp_62 = 1; else tmp_62 = 1;
  l_1407[1][0][4] = tmp_62;
  tmp_63 = safe_sub_func_int16_t_s_s_slice_1((int16_t)((((unsigned long)(
                                                         4294967287UL < (unsigned long)*g_248) | p_55) > (unsigned long)l_1390) >= l_1407[1][0][4]),
                                             (int16_t)((uint64_t)((((
                                                                    (
                                                                    tmp_50 + (int)p_55) + *p_56) + g_379[5]) + (int)l_1387) - 1932307707) + p_55));
  if (((int64_t)((((int)tmp_49 + (int)((unsigned char)l_1387)) + (int)((unsigned char)*(*g_536))) - 75) + l_1387) & (long)tmp_63) {
    uint8_t tmp_20;
    uint64_t tmp_19;
    int32_t tmp_18;
    int tmp_1;
    uint16_t tmp_0;
    uint64_t tmp;
    int32_t l_1447 = (int32_t)(-1L);
    uint16_t *l_1453 = & g_333;
    int32_t *l_1455 = & g_277;
    tmp_1 = 0;
    tmp_0 = (uint16_t)((unsigned long)tmp_1 & 4294967295UL);
    *l_1453 = tmp_0;
    tmp_18 = safe_add_func_int32_t_s_s_slice_1(-1L == (long)l_1407[1][0][4],
                                               (int32_t)0xD0E194A4L);
    tmp = (uint64_t)((uint64_t)tmp_18 < g_167);
    *g_88 = tmp;
    tmp_19 = safe_mod_func_uint64_t_u_u_slice_1(tmp,(uint64_t)l_1447);
    tmp_20 = safe_lshift_func_uint8_t_u_u_slice_1((uint8_t)(~ ((unsigned long)(
                                                               (uint64_t)*(*g_536) > tmp_19) | p_55) != (unsigned long)0x7A3929DFL),
                                                  (unsigned int)1);
    *l_1455 = ~ ((int)tmp_20);
  }
  else {
    uint8_t *l_2153 = & g_364;
    {
      uint32_t tmp_22;
      tmp_22 = (uint32_t)(! 4294967286UL);
      *(*(*(*g_578))) = tmp_22;
    }
    g_75 = l_2153;
  }
  tmp_64 = realsmith_proxy_4Gi9F_slice_1();
  __retres = (int8_t)(((tmp_64 + *l_2182) - 2) + *l_2182);
  return __retres;
}

static uint16_t func_57_slice_1(void)
{
  uint16_t __retres;
  uint64_t *tmp_105;
  uint64_t *l_1185 = & g_167;
  uint64_t **l_1188 = & g_88;
  g_336 = (uint8_t)(-16);
  goto break_cont_5;
  break_cont_5: tmp_105 = l_1185;
                *l_1188 = tmp_105;
  goto break_cont_6;
  break_cont_6: ;
  {
    int tmp_139;
    uint16_t l_1376 = (uint16_t)0x2110L;
    tmp_139 = realsmith_proxy_k7iVT_slice_1();
    __retres = (uint16_t)((int)((uint16_t)((tmp_139 + (int)l_1376) - 8465)) + (int)l_1376);
    goto return_label;
  }
  return_label: return __retres;
}

static void func_60_slice_1(int32_t *p_61, int32_t *p_62, int32_t *p_63,
                            int32_t p_64)
{
  uint64_t l_474;
  int32_t tmp_57;
  int32_t *l_411 = & g_44;
  uint8_t *l_674 = (uint8_t *)0;
  g_329 = (uint16_t)7;
  while ((int)g_329 <= 26) {
    l_411 = g_4;
    g_329 = (uint16_t)((int)g_329 + 1);
  }
  *g_75 = (uint8_t)((int)*g_75 | p_64);
  tmp_57 = (int32_t)0xEB2BDE5AL;
  *p_62 = tmp_57;
  g_277 = tmp_57;
  l_474 = (uint64_t)0;
  while (l_474 <= (uint64_t)2) {
    {
      int tmp_144;
      int16_t l_694 = (int16_t)(-1L);
      int32_t l_724 = (int32_t)0x792E91C4L;
      int32_t l_910 = (int32_t)7L;
      p_62 = p_63;
      g_166 = (int8_t)0;
      while ((int)g_166 <= 2) {
        {
          uint8_t tmp_68;
          uint16_t tmp_67;
          int16_t tmp_101;
          int32_t tmp_100;
          uint64_t tmp_103;
          int64_t *l_695 = & g_85;
          tmp_67 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)l_694);
          tmp_68 = safe_mul_func_uint8_t_u_u_slice_1((uint8_t)tmp_67,
                                                     (uint8_t)*l_411);
          *l_695 = (int64_t)tmp_68;
          tmp_101 = safe_mod_func_int16_t_s_s_slice_1((int16_t)(l_674 != & g_364),
                                                      (int16_t)*g_537);
          tmp_100 = (int32_t)tmp_101;
          *p_62 = tmp_100;
          tmp_103 = *g_88;
          *g_88 = tmp_103;
          g_329 = (uint16_t)0;
          while ((int)g_329 <= 2) {
            {
              int32_t tmp_77;
              tmp_77 = *p_63;
              *p_63 = tmp_77;
              l_724 = (int32_t)1UL;
            }
            g_329 = (uint16_t)((int)g_329 + 1);
          }
        }
        g_166 = (int8_t)((int)g_166 + 1);
      }
      (*g_88) ++;
      tmp_144 = 1;
      l_910 &= tmp_144;
      l_724 = (int32_t)((long)l_724 | 0xAA28D954L);
      {
        int tmp_121;
        tmp_121 = realsmith_ExGdr_slice_1();
        *p_63 = ((((((tmp_121 + l_910) + *p_63) + *p_61) + l_724) + (int)*(*g_536)) - -1440163495) + l_910;
      }
    }
    l_474 += (uint64_t)1;
  }
  return;
}

static int32_t *func_65_slice_1(void)
{
  int32_t *__retres;
  __retres = & g_379[5];
  return __retres;
}

static void func_69_slice_1(uint32_t p_70, uint8_t *p_74)
{
  int32_t l_156;
  uint32_t l_77[9] =
    {(uint32_t)1UL,
     (uint32_t)0UL,
     (uint32_t)0UL,
     (uint32_t)1UL,
     (uint32_t)0UL,
     (uint32_t)0UL,
     (uint32_t)1UL,
     (uint32_t)0UL,
     (uint32_t)0UL};
  int32_t l_93 = (int32_t)(-5L);
  p_70 = (uint32_t)1;
  while (p_70 <= (uint32_t)8) {
    {
      int64_t * const l_99 = (void*)0;
      uint32_t *l_132[10][1][2];
      int32_t l_116[7][6] =
        {{(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL},
         {(int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL,
          (int32_t)0xD48F7C91L,
          (int32_t)0xD48F7C91L,
          (int32_t)0x8AF5EEACL}};
      int32_t *l_368 = & l_93;
      g_76 = (uint8_t)0;
      while ((int)g_76 <= 8) {
        {
          uint64_t *l_78;
          int tmp_4;
          uint64_t tmp;
          uint8_t tmp_17;
          int8_t tmp_25;
          int tmp_24;
          uint64_t *l_79 = & g_80;
          int64_t *l_84 = & g_85;
          uint32_t *l_133 = & l_77[p_70];
          int32_t l_144[4] =
            {(int32_t)0xCC4819D7L,
             (int32_t)0xCC4819D7L,
             (int32_t)0xCC4819D7L,
             (int32_t)0xCC4819D7L};
          tmp = (uint64_t)l_77[g_76];
          *l_79 = tmp;
          *l_84 ^= (long)l_77[6];
          l_78 = g_88;
          if (g_44) tmp_4 = 1; else tmp_4 = 0;
          l_93 = (int32_t)((long long)l_93 & (0x36B4ADBCF703B84DLL | (long long)(
                                              tmp_4 ^ (int)g_76)));
          g_89 = (uint64_t)3;
          while (g_89 <= (uint64_t)8) {
            {
              uint16_t tmp_6;
              int64_t tmp_5;
              int8_t tmp_15;
              int tmp_14;
              uint8_t tmp_8;
              int tmp_7;
              int64_t *l_98[9][1][7] =
                {{{& g_85,
                   & g_85,
                   (int64_t *)0,
                   & g_85,
                   (int64_t *)0,
                   & g_85,
                   & g_85}},
                 {{& g_85, & g_85, & g_85, & g_85, & g_85, & g_85, & g_85}},
                 {{& g_85,
                   & g_85,
                   & g_85,
                   (int64_t *)0,
                   (int64_t *)0,
                   & g_85,
                   & g_85}},
                 {{& g_85, & g_85, & g_85, & g_85, & g_85, & g_85, & g_85}},
                 {{& g_85,
                   (int64_t *)0,
                   (int64_t *)0,
                   & g_85,
                   & g_85,
                   & g_85,
                   (int64_t *)0}},
                 {{& g_85,
                   & g_85,
                   (int64_t *)0,
                   & g_85,
                   (int64_t *)0,
                   & g_85,
                   & g_85}},
                 {{(int64_t *)0,
                   & g_85,
                   & g_85,
                   & g_85,
                   (int64_t *)0,
                   (int64_t *)0,
                   & g_85}},
                 {{& g_85,
                   & g_85,
                   & g_85,
                   (int64_t *)0,
                   (int64_t *)0,
                   & g_85,
                   & g_85}},
                 {{& g_85, & g_85, & g_85, & g_85, & g_85, & g_85, & g_85}}};
              uint32_t *l_102 = & g_103[0][1];
              int32_t *l_127 = & g_128;
              (l_77[g_76]) --;
              *l_102 = (uint32_t)((unsigned long)*l_102 | 4294967287UL);
              tmp_5 = safe_add_func_int64_t_s_s_slice_1((int64_t)(l_98[6][0][0] == l_99),
                                                        (int64_t)(l_77[g_76] | *l_102));
              tmp_6 = safe_lshift_func_uint16_t_u_u_slice_1((uint16_t)(
                                                            (long long)tmp_5 & 0x139C94463E91B5B2LL),
                                                            (unsigned int)5);
              l_93 = (int32_t)tmp_6;
              tmp_7 = realsmith_proxy_3zscM_slice_1();
              tmp_8 = safe_mod_func_uint8_t_u_u_slice_1(*p_74,
                                                        (uint8_t)((((
                                                                    (
                                                                    (
                                                                    tmp_7 + l_116[5][3]) + (int)g_327[1][4]) + (int)*(*g_247)) + (int)*g_248) - -728793993) + l_116[5][3]));
              if (tmp_8) {
                int tmp_13;
                tmp_13 = realsmith_eYDt4_slice_1();
                if ((unsigned int)(((((tmp_13 + g_4[0]) + (int)*(*g_247)) + (int)*g_248) - -26) + g_4[0]) & l_77[p_70]) 
                  tmp_14 = 1;
                else tmp_14 = 0;
              }
              else tmp_14 = 0;
              tmp_15 = safe_rshift_func_int8_t_s_u_slice_1((int8_t)1L,
                                                           (unsigned int)tmp_14);
              *l_127 &= (int)tmp_15;
            }
            g_89 += (uint64_t)1;
          }
          l_132[3][0][1] = & l_77[g_76];
          tmp_17 = safe_rshift_func_uint8_t_u_u_slice_1((uint8_t)l_93,
                                                        (unsigned int)(
                                                        l_132[3][0][1] == (uint32_t *)0));
          *l_133 |= (unsigned int)g_4[0];
          tmp_24 = realsmith_81BZW_slice_1();
          *l_78 = (uint64_t)(((tmp_24 + (int)*g_88) + g_4[0]) - 19) + *g_88;
          tmp_25 = safe_sub_func_int8_t_s_s_slice_1((int8_t)p_70,
                                                    (int8_t)255UL);
          g_44 = (unsigned long)tmp_17 >= ((unsigned long)((int64_t)(
                                                           (long)(*l_133 > (uint32_t)(
                                                                  (int)tmp_25 & l_144[0])) <= -1L) >= g_85) & 18446744073709551615UL);
        }
        g_76 = (uint8_t)((int)g_76 + 1);
      }
      l_156 = 6;
      while (l_156 >= 1) {
        g_44 = 0;
        while (g_44 <= 8) {
          g_167 --;
          g_44 ++;
        }
        l_156 --;
      }
      g_165 = (int8_t)8;
      while ((int)g_165 >= 0) {
        {
          uint32_t ****l_249 = & g_246;
          int32_t *l_251 = & g_44;
          *l_249 = g_246;
          *l_251 = (int32_t)0x197FE0C6L;
          g_89 = (uint64_t)3;
          while (g_89 <= (uint64_t)8) {
            {
              int64_t *l_252 = & g_85;
              *l_252 = (int64_t)g_166;
            }
            g_89 += (uint64_t)1;
          }
        }
        g_165 = (int8_t)((int)g_165 - 1);
      }
      if (*l_368) break;
    }
    p_70 += (uint32_t)1;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


