#include <stdio.h>
/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
__inline static int realsmith_PiJPn_slice_1(void) __attribute__((__used__));
__inline static int realsmith_PiJPn_slice_1(void)
{
  int ret = 0;
  return ret;
}

int realsmith_proxy_e5IyA_slice_1(void)
{
  int proxy_ret_enwR0 = realsmith_PiJPn_slice_1();
  return proxy_ret_enwR0;
}

static int realsmith_01i8A_slice_1(int minv, int maxv) __attribute__((
__used__));
static int realsmith_01i8A_slice_1(int minv, int maxv)
{
  int tmp;
  if (maxv == minv) tmp = maxv; else tmp = 1 % (maxv - minv) + minv;
  return tmp;
}

int A6XX_RB_MRT_FLAG_BUFFER_PITCH_ARRAY_PITCH__MASK_realsmith_NquDV = -3;
int A6XX_RB_MRT_FLAG_BUFFER_PITCH_ARRAY_PITCH__SHIFT_realsmith_NquDV = 10;
__inline static int realsmith_NquDV_slice_1(int val) __attribute__((__used__));
__inline static int realsmith_NquDV_slice_1(int val)
{
  int __retres;
  __retres = ((val >> 5) << A6XX_RB_MRT_FLAG_BUFFER_PITCH_ARRAY_PITCH__SHIFT_realsmith_NquDV) & A6XX_RB_MRT_FLAG_BUFFER_PITCH_ARRAY_PITCH__MASK_realsmith_NquDV;
  return __retres;
}

__inline static int realsmith_Hb94H_slice_1(int dB) __attribute__((__used__));
__inline static int realsmith_Hb94H_slice_1(int dB)
{
  int __retres;
  __retres = (dB + 119) << 9;
  return __retres;
}

int FASTTRAP_T_COMMON_realsmith_NSwoq = 14;
static int realsmith_NSwoq_slice_1(void) __attribute__((__used__));
static int realsmith_NSwoq_slice_1(void)
{
  int __retres;
  __retres = FASTTRAP_T_COMMON_realsmith_NSwoq;
  return __retres;
}

unsigned long realsmith_bS2WK_slice_1(char const *s, unsigned long count)
{
  unsigned long __retres;
  char const *sc;
  sc = s;
  while (1) {
    unsigned long tmp;
    tmp = count;
    count --;
    if (! tmp) break;
    sc ++;
  }
  __retres = (unsigned long)(sc - s);
  return __retres;
}

unsigned long realsmith_proxy_5Berf_slice_1(char p_0_dHXfK,
                                            unsigned long p_1_hPE8a)
{
  char proxy_x6gG0[15] =
    {(char)70,
     p_0_dHXfK,
     (char)95,
     p_0_dHXfK,
     p_0_dHXfK,
     p_0_dHXfK,
     p_0_dHXfK,
     p_0_dHXfK,
     (char)57,
     (char)31,
     (char)11,
     (char)18,
     (char)94,
     p_0_dHXfK,
     (char)35};
  unsigned long proxy_ret_XJ68P =
    realsmith_bS2WK_slice_1((char const *)(proxy_x6gG0),p_1_hPE8a);
  return proxy_ret_XJ68P;
}

static int realsmith_L1HXk_slice_1(void) __attribute__((__used__));
static int realsmith_L1HXk_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

__inline static int realsmith_asafu_slice_1(int const seq1, int const seq2) __attribute__((
__used__));
__inline static int realsmith_asafu_slice_1(int const seq1, int const seq2)
{
  int __retres;
  __retres = (long)((seq2 << 16) - (seq1 << 16)) > (long)0;
  return __retres;
}

long NULL_RTX_realsmith_AyXA6 = (long)16;
static long realsmith_AyXA6_slice_1(void) __attribute__((__used__));
static long realsmith_AyXA6_slice_1(void)
{
  long __retres;
  __retres = NULL_RTX_realsmith_AyXA6;
  goto return_label;
  return_label: return __retres;
}

int FSI_SMODE_ECRC_realsmith_xo0f1 = 6;
int FSI_SMODE_WSC_realsmith_xo0f1 = 10;
static int realsmith_xo0f1_slice_1(void) __attribute__((__used__));
static int realsmith_xo0f1_slice_1(void)
{
  int __retres;
  __retres = ((((FSI_SMODE_WSC_realsmith_xo0f1 | FSI_SMODE_ECRC_realsmith_xo0f1) | 1) | 1) | 1) | 1;
  return __retres;
}

int realsmith_GDq5Q_slice_1(void)
{
  int __retres;
  int err;
  err = 1;
  __retres = err;
  return __retres;
}

int realsmith_proxy_OOw8c_slice_1(void)
{
  int proxy_ret_LYDbT = realsmith_GDq5Q_slice_1();
  return proxy_ret_LYDbT;
}

static int realsmith_epUSQ_slice_1(void) __attribute__((__used__));
static int realsmith_epUSQ_slice_1(void)
{
  int ret = 1;
  return ret;
}

int realsmith_proxy_0lA2m_slice_1(void)
{
  int proxy_ret_TdxXx = realsmith_epUSQ_slice_1();
  return proxy_ret_TdxXx;
}

static int16_t safe_unary_minus_func_int16_t_s_slice_1(int16_t si)
{
  int16_t __retres;
  __retres = (int16_t)(- ((int)si));
  return __retres;
}

static uint8_t safe_lshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left << right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_add_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static uint64_t safe_sub_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int64_t const g_20 = (int64_t)0x245C8100C4307E4ALL;
static uint16_t g_32 = (uint16_t)0xDFDDL;
static uint16_t *g_31 = & g_32;
static int32_t g_53 = (int32_t)0x23C5AD05L;
static uint32_t g_77 = (uint32_t)0x0039C1D5L;
static uint64_t g_86[8][8][1] =
  {{{(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x8B24CEC8E4446CA3LL}},
   {{18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL},
    {(uint64_t)0x8B24CEC8E4446CA3LL},
    {(uint64_t)0x942A26B13122E3BDLL}},
   {{(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {18446744073709551615UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {1UL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {(uint64_t)0x1BD9F019D5C01CF5LL},
    {18446744073709551615UL}},
   {{(uint64_t)0x1BD9F019D5C01CF5LL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x942A26B13122E3BDLL}},
   {{(uint64_t)0x8B24CEC8E4446CA3LL},
    {18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL},
    {(uint64_t)0x8B24CEC8E4446CA3LL}},
   {{(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {18446744073709551615UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {1UL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {(uint64_t)0x1BD9F019D5C01CF5LL}},
   {{18446744073709551615UL},
    {(uint64_t)0x1BD9F019D5C01CF5LL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL}},
   {{(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x8B24CEC8E4446CA3LL},
    {18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL}}};
static int32_t *g_122 = & g_53;
static int32_t **g_121 = & g_122;
static uint8_t g_128 = (uint8_t)0UL;
static int16_t g_158 = (int16_t)0x837BL;
static uint32_t *g_207 = & g_77;
static int64_t g_215 = -1L;
static uint64_t *g_485 = & g_86[5][1][0];
static uint64_t **g_484 = & g_485;
static int16_t const * const g_532 = (int16_t const *)(& g_158);
static int16_t const * const *g_531 = & g_532;
static uint16_t **g_874 = & g_31;
static uint16_t ***g_873 = & g_874;
static int8_t const g_946 = (int8_t)(-1L);
static int8_t const *g_945 = & g_946;
static int32_t *g_975 = & g_53;
static int8_t g_1083[5] =
  {(int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL};
static int16_t g_1096 = (int16_t)4L;
static int64_t g_1097 = (int64_t)0xB5571E1BD64C67E1LL;
static uint16_t g_1099 = (uint16_t)1UL;
static int32_t g_1106[9][4] =
  {{(int32_t)0x77F46250L,
    (int32_t)0xF61EC496L,
    (int32_t)1L,
    (int32_t)0x05502A66L},
   {(int32_t)0xF61EC496L, (int32_t)0L, (int32_t)9L, (int32_t)0x77F46250L},
   {(int32_t)0x24E6A5C1L, (int32_t)0L, (int32_t)0L, (int32_t)0x24E6A5C1L},
   {(int32_t)0x24E6A5C1L,
    (int32_t)0x05502A66L,
    (int32_t)9L,
    (int32_t)0xBC06FF13L},
   {(int32_t)0xF61EC496L, (int32_t)0x24E6A5C1L, (int32_t)1L, (int32_t)(-4L)},
   {(int32_t)0x77F46250L,
    (int32_t)0x4360383FL,
    (int32_t)0x77F46250L,
    (int32_t)(-4L)},
   {(int32_t)1L,
    (int32_t)0x24E6A5C1L,
    (int32_t)0xF61EC496L,
    (int32_t)0xBC06FF13L},
   {(int32_t)9L,
    (int32_t)0x05502A66L,
    (int32_t)0x24E6A5C1L,
    (int32_t)0x24E6A5C1L},
   {(int32_t)0L, (int32_t)0L, (int32_t)0x24E6A5C1L, (int32_t)0x77F46250L}};
static int32_t *g_1296 = & g_1106[6][2];
static int32_t g_1652 = (int32_t)1L;
static uint16_t g_2016 = (uint16_t)0xD896L;
static int32_t * const *g_2063 = (int32_t * const *)(& g_122);
static uint8_t *g_2382 = & g_128;
static int32_t ***g_2883 = & g_121;
static int32_t ****g_2882 = & g_2883;
static int16_t *g_3154 = & g_1096;
static int16_t **g_3153 = & g_3154;
static int16_t ***g_3152 = & g_3153;
static uint8_t g_3381 = (uint8_t)0xA5L;
static int32_t **g_3604 = & g_1296;
static int32_t ***g_3603 = & g_3604;
static uint64_t ***g_3628 = (uint64_t ***)0;
static uint64_t ****g_3627 = & g_3628;
static int32_t ****g_3960[3][3] =
  {{& g_3603, & g_3603, & g_3603},
   {& g_3603, & g_3603, & g_3603},
   {& g_3603, & g_3603, & g_3603}};
static int16_t * const *g_4162 = (int16_t * const *)(& g_3154);
static uint64_t *****g_4491 = & g_3627;
static int8_t *g_4506 = & g_1083[4];
static int8_t **g_4505 = & g_4506;
static void func_1_slice_1(void);

static void func_2_slice_1(uint32_t p_4, uint32_t p_6);

static void func_11_slice_1(void);

static void func_23_slice_1(void);

static int32_t func_27_slice_1(void);

static void func_1_slice_1(void)
{
  int8_t l_7 = (int8_t)0x62L;
  {
    int16_t l_8[1];
    int i_0;
    int tmp_40;
    uint32_t tmp_48;
    int32_t tmp_47;
    int tmp_49;
    int tmp_50;
    unsigned long tmp_59;
    int tmp_60;
    uint16_t l_3369 = (uint16_t)0xC49FL;
    int8_t l_4999 = (int8_t)0x43L;
    i_0 = 0;
    while (i_0 < 1) {
      l_8[i_0] = (int16_t)8L;
      i_0 ++;
    }
    tmp_40 = realsmith_proxy_OOw8c_slice_1();
    tmp_47 = func_27_slice_1();
    tmp_48 = safe_sub_func_uint32_t_u_u_slice_1((uint32_t)5UL,
                                                (uint32_t)tmp_47);
    tmp_49 = realsmith_xo0f1_slice_1();
    tmp_50 = realsmith_proxy_0lA2m_slice_1();
    func_23_slice_1();
    func_11_slice_1();
    tmp_59 = realsmith_proxy_5Berf_slice_1((char)((int)((char)l_8[0]) + -10),
                                           (unsigned long)l_8[0] + (unsigned long)(-5));
    tmp_60 = realsmith_proxy_e5IyA_slice_1();
    func_2_slice_1((uint32_t)((int)((int16_t)((tmp_59 + (unsigned long)l_8[0]) - (unsigned long)11)) + (int)l_8[0]),
                   (uint32_t)((int)((int8_t)((tmp_40 + (int)l_7) - 99)) + (int)l_7));
    {
      int8_t l_5000[6];
      int i_1;
      int8_t l_4992[4][5][1] =
        {{{(int8_t)0x51L},
          {(int8_t)0x51L},
          {(int8_t)0xE4L},
          {(int8_t)0x1EL},
          {(int8_t)0xE4L}},
         {{(int8_t)0x51L},
          {(int8_t)0x51L},
          {(int8_t)0xE4L},
          {(int8_t)0x1EL},
          {(int8_t)0xE4L}},
         {{(int8_t)0x51L},
          {(int8_t)0x51L},
          {(int8_t)0xE4L},
          {(int8_t)0x1EL},
          {(int8_t)0xE4L}},
         {{(int8_t)0x51L},
          {(int8_t)0x51L},
          {(int8_t)0xE4L},
          {(int8_t)0x1EL},
          {(int8_t)0xE4L}}};
      i_1 = 0;
      while (i_1 < 6) {
        l_5000[i_1] = (int8_t)0x10L;
        i_1 ++;
      }
      *(*(*g_873)) = (uint16_t)((int)*(*(*g_873)) + 1);
      {
        int64_t const l_5003;
        int16_t tmp_0;
        int tmp;
        tmp = realsmith_L1HXk_slice_1();
        tmp_0 = safe_unary_minus_func_int16_t_s_slice_1((int16_t)((int64_t)(
                                                                  (((
                                                                    (
                                                                    (
                                                                    tmp + (int)l_5003) + (int)l_4999) + (int)l_5000[3]) + (int)l_3369) + (int)l_4992[1][1][0]) - 50497) + l_5003));
        *(*(*(*g_2882))) = (int32_t)tmp_0;
      }
    }
  }
  return;
}

static void func_2_slice_1(uint32_t p_4, uint32_t p_6)
{
  {
    uint16_t tmp_129;
    int tmp_106;
    uint64_t tmp_128;
    long tmp_107;
    int tmp_108;
    int tmp_127;
    uint32_t tmp_105;
    g_1097 = (int64_t)0;
    while (g_1097 <= (int64_t)2) {
      {
        int16_t tmp_41;
        int32_t *****l_4421 = & g_3960[0][1];
        int32_t **l_4496 = (int32_t **)0;
        g_1099 = (uint16_t)0;
        while ((int)g_1099 <= 7) g_1099 = (uint16_t)((int)g_1099 + 1);
        tmp_41 = (int16_t)(*(*(*l_4421)) != l_4496);
        *(*(*g_3152)) = tmp_41;
      }
      g_1097 += (int64_t)1;
    }
    tmp_106 = realsmith_NquDV_slice_1((int)p_4 + 17);
    tmp_107 = realsmith_AyXA6_slice_1();
    tmp_108 = realsmith_asafu_slice_1((int)p_4 + -5,(int)*g_532 + 31949);
    tmp_127 = realsmith_01i8A_slice_1((int)p_4 + 48,(int)p_4 + 68);
    tmp_128 = safe_sub_func_uint64_t_u_u_slice_1((uint64_t)((uint32_t)(
                                                            (((((tmp_108 + (int)p_4) + (int)*g_31) + (int)*g_532) + (int)p_6) + (int)*(*g_3153)) - 25540) + p_4 >= 
                                                            (uint32_t)(
                                                            (tmp_127 + (int)p_4) - 65) + p_4),
                                                 (uint64_t)((uint32_t)(
                                                            (tmp_107 + (long)p_4) - (long)24) + p_4));
    tmp_129 = safe_add_func_uint16_t_u_u_slice_1((uint16_t)tmp_128,
                                                 (uint16_t)((uint32_t)(
                                                            (tmp_106 + (int)p_4) - 8) + p_4));
    tmp_105 = (uint32_t)tmp_129;
    *g_207 = tmp_105;
    goto break_cont_1;
  }
  break_cont_1: ;
  return;
}

static void func_11_slice_1(void)
{
  *g_121 = *g_121;
  return;
}

static void func_23_slice_1(void)
{
  uint8_t tmp_41;
  int tmp_39;
  uint8_t tmp_30;
  int tmp_40;
  int16_t tmp_29;
  uint64_t l_3386 = 0UL;
  tmp_39 = 0;
  tmp_30 = (uint8_t)tmp_39;
  *g_2382 = tmp_30;
  tmp_40 = realsmith_Hb94H_slice_1((int)l_3386 + 4);
  tmp_41 = safe_lshift_func_uint8_t_u_u_slice_1((uint8_t)((uint64_t)(
                                                          (tmp_40 + (int)l_3386) - 62976) + l_3386),
                                                (unsigned int)tmp_30);
  tmp_29 = (int16_t)tmp_41;
  *(*(*g_3152)) = tmp_29;
  goto return_label;
  return_label: return;
}

static int32_t func_27_slice_1(void)
{
  int32_t __retres;
  {
    int tmp;
    tmp = realsmith_NSwoq_slice_1();
    __retres = (int)((uint16_t)((tmp + (int)g_2016) - 55460)) + (int)g_2016;
  }
  return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_53: %d\n", g_53);
    printf("g_32: %u\n", (unsigned int)g_32);
    printf("g_77: %lu\n", (unsigned long)g_77);
    printf("g_128: %u\n", (unsigned int)g_128);
    printf("g_175: 未在切片中定义\n");
    printf("g_158: %d\n", (int)g_158);
    printf("g_264: 未在切片中定义\n");

  __retres = 0;
  return __retres;
}


