#include <stdio.h>
/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_add_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 + (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_rshift_func_int8_t_s_u_slice_1(int8_t left,
                                                  unsigned int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left >> right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_unary_minus_func_int16_t_s_slice_1(int16_t si)
{
  int16_t __retres;
  __retres = (int16_t)(- ((int)si));
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_lshift_func_int16_t_s_u_slice_1(int16_t left)
{
  int16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (int16_t)tmp;
  return __retres;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t safe_mod_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  int tmp;
  tmp = (int)ui1 % (int)ui2;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint8_t safe_lshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left << right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_add_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint16_t safe_sub_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 - (int)ui2);
  return __retres;
}

static uint32_t safe_unary_minus_func_uint32_t_u_slice_1(uint32_t ui)
{
  uint32_t __retres;
  __retres = - ui;
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static uint32_t safe_mod_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t tmp;
  tmp = ui1 % ui2;
  return tmp;
}

static uint64_t safe_sub_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int64_t const g_20 = (int64_t)0x245C8100C4307E4ALL;
static uint16_t g_32 = (uint16_t)0xDFDDL;
static uint16_t *g_31 = & g_32;
static int32_t g_53 = (int32_t)0x23C5AD05L;
static uint32_t g_77 = (uint32_t)0x0039C1D5L;
static uint64_t g_86[8][8][1] =
  {{{(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x8B24CEC8E4446CA3LL}},
   {{18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL},
    {(uint64_t)0x8B24CEC8E4446CA3LL},
    {(uint64_t)0x942A26B13122E3BDLL}},
   {{(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {18446744073709551615UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {1UL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {(uint64_t)0x1BD9F019D5C01CF5LL},
    {18446744073709551615UL}},
   {{(uint64_t)0x1BD9F019D5C01CF5LL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x942A26B13122E3BDLL}},
   {{(uint64_t)0x8B24CEC8E4446CA3LL},
    {18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL},
    {(uint64_t)0x8B24CEC8E4446CA3LL}},
   {{(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x9CC13236C2177953LL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {18446744073709551615UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {1UL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {(uint64_t)0x1BD9F019D5C01CF5LL}},
   {{18446744073709551615UL},
    {(uint64_t)0x1BD9F019D5C01CF5LL},
    {(uint64_t)0xFB8AAA841158A35CLL},
    {1UL},
    {(uint64_t)0xA8E7E64BFCE9347ALL},
    {18446744073709551615UL},
    {(uint64_t)0x7C1471C2AA0BDEC7LL},
    {(uint64_t)0x9CC13236C2177953LL}},
   {{(uint64_t)0x942A26B13122E3BDLL},
    {(uint64_t)0x8B24CEC8E4446CA3LL},
    {18446744073709551615UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {0UL},
    {0UL},
    {(uint64_t)0xB9E0795B172C66C3LL},
    {18446744073709551615UL}}};
static int32_t *g_122 = & g_53;
static int32_t **g_121 = & g_122;
static uint8_t g_128 = (uint8_t)0UL;
static int16_t g_158 = (int16_t)0x837BL;
static uint32_t g_175 = (uint32_t)1UL;
static uint32_t *g_207 = & g_77;
static uint32_t **g_206 = & g_207;
static int64_t g_215 = -1L;
static int8_t g_264 = (int8_t)1L;
static uint32_t g_362 = (uint32_t)18446744073709551613UL;
static int32_t *g_433 = & g_53;
static uint64_t *g_485 = & g_86[5][1][0];
static uint64_t **g_484 = & g_485;
static int16_t const * const g_532 = (int16_t const *)(& g_158);
static int16_t const * const *g_531 = & g_532;
static uint32_t g_662 = (uint32_t)0x44EB7B80L;
static uint16_t **g_874 = & g_31;
static uint16_t ***g_873 = & g_874;
static int8_t const g_946 = (int8_t)(-1L);
static int8_t const *g_945 = & g_946;
static int32_t *g_975 = & g_53;
static uint16_t g_979 = (uint16_t)0x0D53L;
static int8_t g_1083[5] =
  {(int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL, (int8_t)0x2EL};
static int16_t g_1096 = (int16_t)4L;
static int64_t g_1097 = (int64_t)0xB5571E1BD64C67E1LL;
static uint16_t g_1099 = (uint16_t)1UL;
static int32_t g_1106[9][4] =
  {{(int32_t)0x77F46250L,
    (int32_t)0xF61EC496L,
    (int32_t)1L,
    (int32_t)0x05502A66L},
   {(int32_t)0xF61EC496L, (int32_t)0L, (int32_t)9L, (int32_t)0x77F46250L},
   {(int32_t)0x24E6A5C1L, (int32_t)0L, (int32_t)0L, (int32_t)0x24E6A5C1L},
   {(int32_t)0x24E6A5C1L,
    (int32_t)0x05502A66L,
    (int32_t)9L,
    (int32_t)0xBC06FF13L},
   {(int32_t)0xF61EC496L, (int32_t)0x24E6A5C1L, (int32_t)1L, (int32_t)(-4L)},
   {(int32_t)0x77F46250L,
    (int32_t)0x4360383FL,
    (int32_t)0x77F46250L,
    (int32_t)(-4L)},
   {(int32_t)1L,
    (int32_t)0x24E6A5C1L,
    (int32_t)0xF61EC496L,
    (int32_t)0xBC06FF13L},
   {(int32_t)9L,
    (int32_t)0x05502A66L,
    (int32_t)0x24E6A5C1L,
    (int32_t)0x24E6A5C1L},
   {(int32_t)0L, (int32_t)0L, (int32_t)0x24E6A5C1L, (int32_t)0x77F46250L}};
static int32_t g_1142 = (int32_t)0x2F8825B6L;
static int32_t *g_1296 = & g_1106[6][2];
static uint16_t g_1356[8][8] =
  {{(uint16_t)0xD8D3L,
    (uint16_t)0xD8D3L,
    (uint16_t)0x9FFAL,
    (uint16_t)0x5871L,
    (uint16_t)0x7865L,
    (uint16_t)0x9FFAL,
    (uint16_t)0x7865L,
    (uint16_t)0x5871L},
   {(uint16_t)0UL,
    (uint16_t)0x5871L,
    (uint16_t)0UL,
    (uint16_t)0x1132L,
    (uint16_t)0x5871L,
    (uint16_t)0x5897L,
    (uint16_t)0x5897L,
    (uint16_t)0x5871L},
   {(uint16_t)0x5871L,
    (uint16_t)0x5897L,
    (uint16_t)0x5897L,
    (uint16_t)0x5871L,
    (uint16_t)0x1132L,
    (uint16_t)0UL,
    (uint16_t)0x5871L,
    (uint16_t)0UL},
   {(uint16_t)0x5871L,
    (uint16_t)0x7865L,
    (uint16_t)0x9FFAL,
    (uint16_t)0x7865L,
    (uint16_t)0x5871L,
    (uint16_t)0x9FFAL,
    (uint16_t)0xD8D3L,
    (uint16_t)0xD8D3L},
   {(uint16_t)0UL,
    (uint16_t)0x7865L,
    (uint16_t)0x1132L,
    (uint16_t)0x1132L,
    (uint16_t)0x7865L,
    (uint16_t)0UL,
    (uint16_t)0x5897L,
    (uint16_t)0x7865L},
   {(uint16_t)0xD8D3L,
    (uint16_t)0x5897L,
    (uint16_t)0x1132L,
    (uint16_t)0xD8D3L,
    (uint16_t)0x1132L,
    (uint16_t)0x5897L,
    (uint16_t)0xD8D3L,
    (uint16_t)0UL},
   {(uint16_t)0x7865L,
    (uint16_t)0x5871L,
    (uint16_t)0x9FFAL,
    (uint16_t)0xD8D3L,
    (uint16_t)0UL,
    (uint16_t)0xD8D3L,
    (uint16_t)0x5897L,
    (uint16_t)0x1132L},
   {(uint16_t)0xF328L,
    (uint16_t)0UL,
    (uint16_t)0x9FFAL,
    (uint16_t)65528UL,
    (uint16_t)0UL,
    (uint16_t)65528UL,
    (uint16_t)0x9FFAL,
    (uint16_t)0UL}};
static int32_t g_1652 = (int32_t)1L;
static uint32_t ***g_1809 = & g_206;
static int64_t g_1824[5][3] =
  {{(int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL},
   {(int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL},
   {(int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL},
   {(int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL},
   {(int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL,
    (int64_t)0xE494AB0408ED4E10LL}};
static int64_t g_1973 = (int64_t)0xAC3DFC881E74B629LL;
static uint16_t g_2016 = (uint16_t)0xD896L;
static int32_t * const *g_2063 = (int32_t * const *)(& g_122);
static int32_t * const **g_2062 = & g_2063;
static int32_t * const ***g_2061 = & g_2062;
static uint8_t g_2256[7][3] =
  {{(uint8_t)6UL, (uint8_t)1UL, (uint8_t)6UL},
   {(uint8_t)255UL, (uint8_t)255UL, (uint8_t)0xB8L},
   {(uint8_t)255UL, (uint8_t)255UL, (uint8_t)255UL},
   {(uint8_t)6UL, (uint8_t)255UL, (uint8_t)255UL},
   {(uint8_t)255UL, (uint8_t)1UL, (uint8_t)0xB8L},
   {(uint8_t)6UL, (uint8_t)1UL, (uint8_t)6UL},
   {(uint8_t)255UL, (uint8_t)255UL, (uint8_t)0xB8L}};
static uint32_t g_2297 = (uint32_t)1UL;
static uint32_t **g_2328 = & g_207;
static uint8_t *g_2382 = & g_128;
static uint8_t **g_2381[4] = {& g_2382, & g_2382, & g_2382, & g_2382};
static int32_t ***g_2883 = & g_121;
static int32_t ****g_2882 = & g_2883;
static int16_t *g_3154 = & g_1096;
static int16_t **g_3153 = & g_3154;
static int16_t ***g_3152 = & g_3153;
static uint8_t g_3381 = (uint8_t)0xA5L;
static int32_t **g_3604 = & g_1296;
static int32_t ***g_3603 = & g_3604;
static uint64_t ***g_3628 = (uint64_t ***)0;
static uint64_t ****g_3627 = & g_3628;
static int32_t ****g_3960[3][3] =
  {{& g_3603, & g_3603, & g_3603},
   {& g_3603, & g_3603, & g_3603},
   {& g_3603, & g_3603, & g_3603}};
static int16_t * const *g_4162 = (int16_t * const *)(& g_3154);
static uint16_t g_4347 = (uint16_t)0x78AFL;
static uint8_t *g_4419 = & g_2256[0][1];
static uint64_t *****g_4491 = & g_3627;
static int8_t *g_4506 = & g_1083[4];
static int8_t **g_4505 = & g_4506;
static void func_1_slice_1(void);

static void func_2_slice_1(uint64_t p_3, uint32_t p_4, uint64_t p_5,
                           uint32_t p_6);

static int8_t func_11_slice_1(void);

static void func_23_slice_1(void);

static int32_t func_27_slice_1(void);

static void func_1_slice_1(void)
{
  int8_t l_7 = (int8_t)0x62L;
  {
    int16_t l_8[1];
    int i_0;
    int8_t tmp_24;
    int8_t tmp_23;
    uint32_t tmp_18;
    int32_t tmp_17;
    uint16_t l_3369 = (uint16_t)0xC49FL;
    i_0 = 0;
    while (i_0 < 1) {
      l_8[i_0] = (int16_t)8L;
      i_0 ++;
    }
    tmp_17 = func_27_slice_1();
    tmp_18 = safe_sub_func_uint32_t_u_u_slice_1((uint32_t)5UL,
                                                (uint32_t)tmp_17);
    func_23_slice_1();
    tmp_23 = func_11_slice_1();
    tmp_24 = safe_add_func_int8_t_s_s_slice_1(tmp_23,*g_945);
    func_2_slice_1((uint64_t)l_7,(uint32_t)l_8[0],
                   (uint64_t)((unsigned long long)tmp_24 > 0xDCE9E3EAB4CB2464LL),
                   (uint32_t)l_7);
    *(*(*g_873)) = (uint16_t)((int)*(*(*g_873)) + 1);
    {
      int64_t const l_5003;
      int16_t tmp;
      tmp = safe_unary_minus_func_int16_t_s_slice_1((int16_t)l_5003);
      *(*(*(*g_2882))) = (int32_t)tmp;
    }
  }
  return;
}

static void func_2_slice_1(uint64_t p_3, uint32_t p_4, uint64_t p_5,
                           uint32_t p_6)
{
  uint8_t ***l_4573 = & g_2381[2];
  g_4347 = (uint16_t)1;
  while ((int)g_4347 <= 7) {
    {
      uint32_t tmp_71;
      uint16_t tmp_70;
      uint64_t tmp_69;
      uint32_t tmp_62;
      uint64_t tmp_61;
      uint8_t ***l_4574 = & g_2381[2];
      int8_t l_4576[7][2][2] =
        {{{(int8_t)(-10L), (int8_t)0x1FL}, {(int8_t)(-5L), (int8_t)0x1FL}},
         {{(int8_t)(-10L), (int8_t)(-10L)}, {(int8_t)0x68L, (int8_t)0xCEL}},
         {{(int8_t)(-4L), (int8_t)0x4CL}, {(int8_t)0x78L, (int8_t)9L}},
         {{(int8_t)0x1FL, (int8_t)0x78L}, {(int8_t)0L, (int8_t)(-9L)}},
         {{(int8_t)0L, (int8_t)0x78L}, {(int8_t)0x1FL, (int8_t)9L}},
         {{(int8_t)0x78L, (int8_t)0x4CL}, {(int8_t)(-4L), (int8_t)0xCEL}},
         {{(int8_t)0x68L, (int8_t)(-10L)}, {(int8_t)(-10L), (int8_t)0x1FL}}};
      g_1097 = (int64_t)0;
      while (g_1097 <= (int64_t)2) {
        {
          int16_t tmp_28;
          int32_t *****l_4421 = & g_3960[0][1];
          int32_t **l_4496 = (int32_t **)0;
          g_1099 = (uint16_t)0;
          while ((int)g_1099 <= 7) {
            {
              uint8_t tmp_17;
              int tmp_16;
              int8_t tmp_10;
              int8_t *l_4470 = & g_264;
              if (*(*g_2063)) goto __Cont;
              g_175 = (uint32_t)1;
              while (g_175 <= (uint32_t)7) g_175 += (uint32_t)1;
              tmp_16 = 1;
              l_4421 = & g_3960[0][0];
              tmp_17 = safe_add_func_uint8_t_u_u_slice_1((uint8_t)(& g_3960[0][0] == l_4421),
                                                         (uint8_t)tmp_16);
              tmp_10 = (int8_t)tmp_17;
              *l_4470 = tmp_10;
              *(*(*g_2883)) = (int32_t)((unsigned int)*(*(*g_2883)) & p_4);
              g_1973 = (int64_t)0;
              while (g_1973 <= (int64_t)2) {
                {
                  int16_t tmp_27;
                  tmp_27 = safe_mul_func_int16_t_s_s_slice_1((int16_t)0xA625L,
                                                             (int16_t)p_6);
                  *g_433 = (int32_t)tmp_27;
                }
                g_1973 += (int64_t)1;
              }
            }
            __Cont: g_1099 = (uint16_t)((int)g_1099 + 1);
          }
          tmp_28 = (int16_t)(*(*(*l_4421)) != l_4496);
          *(*(*g_3152)) = tmp_28;
          *g_485 &= (unsigned long)((unsigned long)p_6 > 7UL);
        }
        g_1097 += (int64_t)1;
      }
      g_979 = (uint16_t)1;
      while ((int)g_979 <= 7) {
        {
          int64_t l_4533[4];
          int i_7;
          i_7 = 0;
          while (i_7 < 4) {
            l_4533[i_7] = (int64_t)0x9B29539EA0BC9406LL;
            i_7 ++;
          }
          g_662 = (uint32_t)0;
          while (g_662 <= (uint32_t)7) {
            {
              uint8_t l_4538 = (uint8_t)0x3DL;
              g_362 = (uint32_t)1;
              while (g_362 <= (uint32_t)4) {
                if (*(*(*(*g_2061)))) break;
                (*(*g_484)) ++;
                if (*(*g_484)) {
                  int8_t tmp_38;
                  int8_t tmp_37;
                  uint8_t tmp_36;
                  *g_485 |= p_3;
                  tmp_36 = safe_mod_func_uint8_t_u_u_slice_1((uint8_t)(
                                                             (uint32_t)(
                                                             (long)(*(*g_2328) & (unsigned int)(
                                                                    (uint64_t)1L != p_3)) < -1L) < p_4),
                                                             (uint8_t)l_4533[3]);
                  tmp_37 = safe_rshift_func_int8_t_s_u_slice_1((int8_t)(
                                                               (unsigned int)tmp_36 & p_4),
                                                               (unsigned int)6);
                  tmp_38 = safe_lshift_func_int8_t_s_s_slice_1(tmp_37,7);
                  *(*g_121) ^= -6L == (long)(*g_485 > (uint64_t)tmp_38);
                }
                *g_122 = (int32_t)0x1EB2B0CBL;
                g_362 += (uint32_t)1;
              }
              *(*(*(*g_2061))) = (int)l_4538 != (int)l_4538;
              g_362 = (uint32_t)0;
              while (g_362 <= (uint32_t)7) {
                {
                  int16_t tmp_58;
                  uint32_t tmp_57;
                  int tmp_56;
                  if (p_5) tmp_56 = 1; else tmp_56 = 0;
                  tmp_57 = safe_unary_minus_func_uint32_t_u_slice_1((uint32_t)tmp_56);
                  tmp_58 = safe_lshift_func_int16_t_s_u_slice_1(*(*g_3153));
                  *(*(*(*g_2061))) = (int)tmp_58 <= (int)l_4538;
                }
                g_362 += (uint32_t)1;
              }
            }
            g_662 += (uint32_t)1;
          }
        }
        g_979 = (uint16_t)((int)g_979 + 1);
      }
      if (! *(*g_4162)) {
        uint16_t tmp_67;
        int tmp_66;
        int32_t tmp_63;
        tmp_66 = 1;
        tmp_67 = safe_sub_func_uint16_t_u_u_slice_1((uint16_t)((l_4573 != l_4574) | (
                                                               (uint32_t)tmp_66 != p_6)),
                                                    (uint16_t)p_3);
        p_5 = (uint64_t)((uint64_t)tmp_67 != p_3);
        tmp_63 = (int32_t)((unsigned long)(((unsigned long)*(*(*g_873)) < (
                                            p_5 | (unsigned long)p_6)) < (int)l_4576[1][0][0]) & p_3);
        *g_975 = tmp_63;
      }
      tmp_69 = safe_sub_func_uint64_t_u_u_slice_1((uint64_t)(p_4 >= p_4),
                                                  (uint64_t)p_4);
      tmp_70 = safe_add_func_uint16_t_u_u_slice_1((uint16_t)tmp_69,
                                                  (uint16_t)p_4);
      tmp_62 = (uint32_t)tmp_70;
      *g_207 = tmp_62;
      tmp_71 = safe_mod_func_uint32_t_u_u_slice_1((uint32_t)0x0CCAA974L,
                                                  tmp_62);
      g_215 = (int64_t)((unsigned long)tmp_71 | 1UL);
      tmp_61 = (uint64_t)(g_215 | (long)p_4);
      *(*g_484) = tmp_61;
      if (*(*(*(*g_2061)))) break;
      g_2297 = (uint32_t)0;
      while (g_2297 <= (uint32_t)2) {
        {
          int32_t *l_4581 = & g_1142;
          *(*g_2883) = l_4581;
        }
        g_2297 += (uint32_t)1;
      }
    }
    g_4347 = (uint16_t)((int)g_4347 + 1);
  }
  return;
}

static int8_t func_11_slice_1(void)
{
  int8_t __retres;
  int tmp_7;
  int32_t l_4089 = (int32_t)0x84A7A107L;
  uint32_t l_4091 = (uint32_t)1UL;
  *g_121 = *g_121;
  tmp_7 = 0;
  *(*(*(*g_2882))) = (int32_t)((long)*(*(*(*g_2882))) | ((long)((unsigned int)tmp_7 ^ l_4091) | 0x4ADFL));
  __retres = (int8_t)l_4089;
  return __retres;
}

static void func_23_slice_1(void)
{
  uint8_t tmp_32;
  int tmp_31;
  uint8_t tmp_26;
  int16_t tmp_25;
  uint64_t l_3386 = 0UL;
  tmp_31 = 0;
  tmp_26 = (uint8_t)tmp_31;
  *g_2382 = tmp_26;
  tmp_32 = safe_lshift_func_uint8_t_u_u_slice_1((uint8_t)l_3386,
                                                (unsigned int)tmp_26);
  tmp_25 = (int16_t)tmp_32;
  *(*(*g_3152)) = tmp_25;
  goto return_label;
  return_label: return;
}

static int32_t func_27_slice_1(void)
{
  int32_t __retres;
  int32_t tmp;
  tmp = *(*g_121);
  *(*g_121) = tmp;
  __retres = (int32_t)g_2016;
  return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_53: %d\n", g_53);
    printf("g_32: %u\n", (unsigned int)g_32);
    printf("g_77: %lu\n", (unsigned long)g_77);
    printf("g_128: %u\n", (unsigned int)g_128);
    printf("g_175: %lu\n", (unsigned long)g_175);
    printf("g_158: %d\n", (int)g_158);
    printf("g_264: %d\n", (int)g_264);

  __retres = 0;
  return __retres;
}


