#include <stdio.h>
/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_lshift_func_int16_t_s_s_slice_1(int16_t left)
{
  int16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_sub_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static int32_t safe_div_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  tmp = si1 / si2;
  return tmp;
}

static int64_t safe_div_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  if (si2 == (int64_t)0) tmp = si1; else tmp = si1 / si2;
  return tmp;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint8_t safe_div_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  int tmp;
  tmp = (int)ui1 / (int)ui2;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_sub_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 - (int)ui2);
  return __retres;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int8_t g_10[8] =
  {(int8_t)0x4DL,
   (int8_t)0x87L,
   (int8_t)0x4DL,
   (int8_t)0x4DL,
   (int8_t)0x87L,
   (int8_t)0x4DL,
   (int8_t)0x4DL,
   (int8_t)0x87L};
static int32_t g_25 = (int32_t)0xE9646B8DL;
static int16_t g_66 = (int16_t)0xC1C5L;
static int32_t g_69 = (int32_t)1L;
static int32_t *g_68 = & g_69;
static int32_t g_131 = (int32_t)0x9AC9426BL;
static uint32_t g_160 = (uint32_t)0x2287F110L;
static uint64_t g_200 = 1UL;
static int64_t g_255 = -1L;
static int32_t **g_406 = & g_68;
static uint8_t g_414[6][6][7] =
  {{{(uint8_t)0xC5L,
     (uint8_t)250UL,
     (uint8_t)255UL,
     (uint8_t)0xC5L,
     (uint8_t)0UL,
     (uint8_t)0xF7L,
     (uint8_t)0UL},
    {(uint8_t)0xC5L,
     (uint8_t)248UL,
     (uint8_t)248UL,
     (uint8_t)0xC5L,
     (uint8_t)6UL,
     (uint8_t)0x59L,
     (uint8_t)0UL},
    {(uint8_t)246UL,
     (uint8_t)250UL,
     (uint8_t)248UL,
     (uint8_t)246UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL},
    {(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL}},
   {{(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL},
    {(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL}},
   {{(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL},
    {(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL}},
   {{(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL},
    {(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL}},
   {{(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0UL},
    {(uint8_t)248UL,
     (uint8_t)0x59L,
     (uint8_t)1UL,
     (uint8_t)248UL,
     (uint8_t)255UL,
     (uint8_t)0x85L,
     (uint8_t)255UL},
    {(uint8_t)248UL,
     (uint8_t)0xF7L,
     (uint8_t)0xF7L,
     (uint8_t)248UL,
     (uint8_t)0UL,
     (uint8_t)0UL,
     (uint8_t)255UL},
    {(uint8_t)255UL,
     (uint8_t)0x59L,
     (uint8_t)0xF7L,
     (uint8_t)255UL,
     (uint8_t)255UL,
     (uint8_t)0UL,
     (uint8_t)0xC5L}},
   {{(uint8_t)0xF7L,
     (uint8_t)0UL,
     (uint8_t)0x26L,
     (uint8_t)0xF7L,
     (uint8_t)1UL,
     (uint8_t)0xA3L,
     (uint8_t)1UL},
    {(uint8_t)0xF7L,
     (uint8_t)0x85L,
     (uint8_t)0x85L,
     (uint8_t)0xF7L,
     (uint8_t)0xC5L,
     (uint8_t)1UL,
     (uint8_t)1UL},
    {(uint8_t)1UL,
     (uint8_t)0UL,
     (uint8_t)0x85L,
     (uint8_t)1UL,
     (uint8_t)1UL,
     (uint8_t)1UL,
     (uint8_t)0xC5L},
    {(uint8_t)0xF7L,
     (uint8_t)0UL,
     (uint8_t)0x26L,
     (uint8_t)0xF7L,
     (uint8_t)1UL,
     (uint8_t)0xA3L,
     (uint8_t)1UL},
    {(uint8_t)0xF7L,
     (uint8_t)0x85L,
     (uint8_t)0x85L,
     (uint8_t)0xF7L,
     (uint8_t)0xC5L,
     (uint8_t)1UL,
     (uint8_t)1UL},
    {(uint8_t)1UL,
     (uint8_t)0UL,
     (uint8_t)0x85L,
     (uint8_t)1UL,
     (uint8_t)1UL,
     (uint8_t)1UL,
     (uint8_t)0xC5L}}};
static uint16_t *g_531 = (uint16_t *)0;
static uint32_t *g_566 = & g_160;
static uint32_t **g_565 = & g_566;
static uint64_t *g_573 = & g_200;
static int32_t g_637 = (int32_t)0x1C083A12L;
static int32_t g_647 = (int32_t)0x4FD4947CL;
static int32_t g_653 = (int32_t)0L;
static int64_t g_823 = 1L;
static uint32_t g_878 = (uint32_t)0x06DE8FDFL;
static int32_t g_1037 = (int32_t)3L;
static uint16_t **g_1360[6] =
  {& g_531, & g_531, & g_531, & g_531, & g_531, & g_531};
static uint16_t ***g_1359 = & g_1360[2];
static int8_t g_1377 = (int8_t)(-1L);
static int8_t * const g_1382 = & g_1377;
static int8_t *g_2106 = & g_10[4];
static int8_t **g_2105 = & g_2106;
static int8_t ***g_2104 = & g_2105;
static uint8_t g_2223 = (uint8_t)0xE8L;
static uint16_t ****g_2433 = & g_1359;
static uint16_t *****g_2432 = & g_2433;
static uint16_t *****g_2434 = & g_2433;
static int32_t g_2436 = (int32_t)0x4D651D34L;
static uint8_t g_2439 = (uint8_t)0xD8L;
static uint32_t *g_3495 = & g_878;
static uint32_t ** const g_3494[9] =
  {& g_3495,
   & g_3495,
   & g_3495,
   & g_3495,
   & g_3495,
   & g_3495,
   & g_3495,
   & g_3495,
   & g_3495};
static uint32_t ** const *g_3493 = & g_3494[8];
static int32_t *g_4042 = & g_131;
static int32_t *g_4187 = & g_1037;
static void func_1_slice_1(void);

static void func_2_slice_1(void);

static int64_t func_5_slice_1(int64_t const p_9);

static void func_16_slice_1(int16_t p_17, int8_t p_18);

static void func_33_slice_1(void);

static void func_38_slice_1(int32_t const * const p_39, uint16_t p_40);

static int32_t *func_41_slice_1(uint64_t p_43, int32_t *p_44);

static void func_45_slice_1(int16_t p_48);

static void func_1_slice_1(void)
{
  uint16_t const l_3216;
  int64_t tmp_7;
  int8_t tmp_2;
  uint8_t tmp_1;
  int16_t tmp_0;
  int32_t tmp;
  uint16_t tmp_12;
  uint64_t tmp_11;
  uint16_t l_23 = (uint16_t)3UL;
  int32_t *l_24 = & g_25;
  int32_t l_5323 = (int32_t)0x1992E7D4L;
  tmp_0 = safe_lshift_func_int16_t_s_s_slice_1((int16_t)g_10[4]);
  *l_24 |= (int)g_10[6];
  tmp_1 = safe_div_func_uint8_t_u_u_slice_1((uint8_t)((int)l_23 < *l_24),
                                            (uint8_t)tmp_0);
  tmp_2 = safe_lshift_func_int8_t_s_s_slice_1((int8_t)tmp_1,2);
  func_16_slice_1((int16_t)tmp_2,g_10[1]);
  tmp_7 = func_5_slice_1((int64_t)l_3216);
  tmp = (int32_t)tmp_7;
  *l_24 = tmp;
  func_2_slice_1();
  tmp_12 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)l_5323,
                                              (uint16_t)*l_24);
  tmp_11 = (uint64_t)tmp_12;
  *g_573 = tmp_11;
  return;
}

static void func_2_slice_1(void)
{
  goto break_cont_1;
  break_cont_1: ;
  g_823 = (int64_t)0;
  g_637 = 1;
  g_2436 = 0;
  while (g_2436 <= 1) g_2436 ++;
  goto return_label;
  return_label: return;
}

static int64_t func_5_slice_1(int64_t const p_9)
{
  int64_t __retres;
  goto break_cont_2;
  break_cont_2: ;
  __retres = p_9;
  return __retres;
}

static void func_16_slice_1(int16_t p_17, int8_t p_18)
{
  int32_t *l_28[9];
  int32_t const *l_2359[5][9][5];
  int i;
  i = 0;
  while (i < 9) {
    l_28[i] = & g_25;
    i ++;
  }
  g_25 = g_25;
  p_18 = (int8_t)0;
  l_2359[3][0][2] = (int32_t const *)func_41_slice_1((uint64_t)g_25,l_28[4]);
  func_38_slice_1(l_2359[3][0][2],(uint16_t)p_17);
  func_33_slice_1();
  return;
}

static void func_33_slice_1(void)
{
  g_255 = (int64_t)0;
  return;
}

static void func_38_slice_1(int32_t const * const p_39, uint16_t p_40)
{
  int32_t **l_2368;
  int32_t l_2392 = (int32_t)1L;
  uint64_t l_2435[4][2][9] =
    {{{(uint64_t)0x7B58B5892FA12684LL,
       18446744073709551615UL,
       1UL,
       (uint64_t)0x7431BFAAEF659D8BLL,
       (uint64_t)0x36A40EADFF33F4C4LL,
       (uint64_t)0xE5BFD9879F058E04LL,
       (uint64_t)0xDD70505C2263C0F7LL,
       (uint64_t)0x41EB2CD053C2CD1ALL,
       (uint64_t)0xDD70505C2263C0F7LL},
      {9UL,
       (uint64_t)0x0BA9CACFDD108844LL,
       (uint64_t)0x36637565472C0D46LL,
       (uint64_t)0x36637565472C0D46LL,
       (uint64_t)0x0BA9CACFDD108844LL,
       9UL,
       (uint64_t)0x1E272148E74B5406LL,
       (uint64_t)0xD790770B0E61E862LL,
       0UL}},
     {{(uint64_t)0x41EB2CD053C2CD1ALL,
       (uint64_t)0x0DA0C5DBA1E79A2CLL,
       (uint64_t)0x99F0CCF9A22E91C3LL,
       (uint64_t)0xE5BFD9879F058E04LL,
       (uint64_t)0x7B58B5892FA12684LL,
       18446744073709551609UL,
       (uint64_t)0x36A40EADFF33F4C4LL,
       (uint64_t)0x36A40EADFF33F4C4LL,
       18446744073709551609UL},
      {(uint64_t)0x36637565472C0D46LL,
       18446744073709551608UL,
       0UL,
       18446744073709551608UL,
       (uint64_t)0x36637565472C0D46LL,
       (uint64_t)0x22248A20DA1658A4LL,
       (uint64_t)0xD790770B0E61E862LL,
       (uint64_t)0x1E272148E74B5406LL,
       9UL}},
     {{18446744073709551609UL,
       (uint64_t)0x41EB2CD053C2CD1ALL,
       1UL,
       (uint64_t)0xDD70505C2263C0F7LL,
       (uint64_t)0x22B4026F3A1190D6LL,
       18446744073709551615UL,
       (uint64_t)0x36A40EADFF33F4C4LL,
       18446744073709551615UL,
       (uint64_t)0x22B4026F3A1190D6LL},
      {(uint64_t)0xD790770B0E61E862LL,
       18446744073709551608UL,
       18446744073709551608UL,
       (uint64_t)0xD790770B0E61E862LL,
       (uint64_t)0x1CC5CA9E9EBF5587LL,
       0UL,
       5UL,
       18446744073709551608UL,
       (uint64_t)0x102EE1A3ACDE35B6LL}},
     {{(uint64_t)0x7B58B5892FA12684LL,
       (uint64_t)0x0DA0C5DBA1E79A2CLL,
       (uint64_t)0xAD9556182B36BBCCLL,
       1UL,
       (uint64_t)0xE5BFD9879F058E04LL,
       18446744073709551615UL,
       18446744073709551615UL,
       (uint64_t)0xE5BFD9879F058E04LL,
       1UL},
      {(uint64_t)0x01E61AC701D5E831LL,
       18446744073709551612UL,
       (uint64_t)0x01E61AC701D5E831LL,
       (uint64_t)0x0BA9CACFDD108844LL,
       (uint64_t)0x1CC5CA9E9EBF5587LL,
       18446744073709551608UL,
       9UL,
       (uint64_t)0x36637565472C0D46LL,
       0UL}}};
  {
    int8_t * const **l_2438;
    int tmp_47;
    int32_t **l_2366[3][8][1] =
      {{{& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68}},
       {{& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68}},
       {{& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68},
        {& g_68}}};
    int8_t * const ***l_2437 = & l_2438;
    l_2368 = l_2366[2][7][0];
    tmp_47 = 0;
    *g_1382 = safe_lshift_func_int8_t_s_s_slice_1((int8_t)(tmp_47 ^ l_2392),
                                                  2);
    {
      int8_t tmp;
      int32_t tmp_0;
      int64_t tmp_18;
      int8_t tmp_17;
      uint32_t tmp_16;
      uint16_t tmp_14;
      uint8_t tmp_13;
      int32_t tmp_12;
      int32_t tmp_11;
      int32_t tmp_10;
      uint32_t tmp_15;
      int32_t tmp_9;
      int8_t l_2397 = (int8_t)(-1L);
      uint8_t *l_2440 = & g_414[3][2][6];
      tmp = (int8_t)0xD1L;
      *(*(*g_2104)) = tmp;
      tmp_0 = (int32_t)l_2397;
      *(*l_2368) = tmp_0;
      g_2432 = g_2432;
      g_2434 = & g_2433;
      tmp_10 = safe_sub_func_int32_t_s_s_slice_1((unsigned long)(g_2432 != g_2434) > (
                                                 l_2435[1][0][2] & (unsigned long)p_40),
                                                 g_2436 < ((int8_t * const ***)0 != l_2437));
      tmp_11 = safe_div_func_int32_t_s_s_slice_1(tmp_10,*(*g_406));
      tmp_12 = safe_div_func_int32_t_s_s_slice_1(tmp_11 < (int32_t)g_2439,
                                                 *(*l_2368));
      *l_2440 = (uint8_t)((int)*l_2440 ^ (0x9EL > (long)tmp_12));
      tmp_13 = safe_mul_func_uint8_t_u_u_slice_1(*l_2440,(uint8_t)p_40);
      tmp_14 = safe_sub_func_uint16_t_u_u_slice_1((uint16_t)tmp_13,
                                                  (uint16_t)l_2397);
      tmp_15 = *(*g_565);
      (*(*g_565)) ++;
      tmp_16 = safe_sub_func_uint32_t_u_u_slice_1(tmp_15,
                                                  (uint32_t)(((int)tmp_14 < *p_39) | *(*l_2368)));
      *(*g_2105) = (int8_t)((unsigned int)*(*g_2105) & tmp_16);
      tmp_17 = safe_mul_func_int8_t_s_s_slice_1((int8_t)0xCDL,*(*g_2105));
      tmp_18 = safe_div_func_int64_t_s_s_slice_1((int64_t)((long)tmp_17 < -7L),
                                                 (int64_t)p_40);
      tmp_9 = (int32_t)tmp_18;
      *(*g_406) = tmp_9;
      func_45_slice_1((int16_t)p_40);
    }
  }
  return;
}

static int32_t *func_41_slice_1(uint64_t p_43, int32_t *p_44)
{
  int32_t tmp_0;
  int32_t tmp_35;
  int tmp_44;
  uint32_t tmp_36;
  int32_t *l_56 = & g_25;
  uint32_t l_2039 = (uint32_t)1UL;
  int32_t *l_2249 = & g_69;
  tmp_0 = (int32_t)g_10[6];
  *l_56 = tmp_0;
  g_68 = p_44;
  func_45_slice_1((int16_t)l_2039);
  tmp_35 = (int32_t)(-8L);
  *l_2249 = tmp_35;
  tmp_44 = 0;
  tmp_36 = (uint32_t)tmp_44;
  *g_566 = tmp_36;
  g_653 = 4;
  while (g_653 > -18) {
    {
      int tmp_33;
      uint64_t tmp_28;
      tmp_33 = 0;
      tmp_28 = (uint64_t)((uint64_t)tmp_33 == p_43);
      *l_2249 = (uint64_t)0L != tmp_28;
    }
    g_653 --;
  }
  return p_44;
}

static void func_45_slice_1(int16_t p_48)
{
  int32_t l_2222;
  int tmp_8;
  uint64_t l_2225 = 18446744073709551615UL;
  l_2222 = (int32_t)0x9409L;
  if ((int)p_48 & l_2222) tmp_8 = 1; else tmp_8 = 0;
  g_2223 = (uint8_t)tmp_8;
  *(*g_406) ^= (uint64_t)p_48 >= l_2225;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_823: %ld\n", (long)g_823);
    printf("g_2223: %u\n", (unsigned int)g_2223);
    printf("g_25: %d\n", g_25);
    printf("g_200: %lu\n", (unsigned long)g_200);
    printf("g_1377: %d\n", (int)g_1377);
    printf("g_2436: %d\n", g_2436);
    printf("g_2439: %u\n", (unsigned int)g_2439);
    printf("g_69: %d\n", g_69);
    printf("g_160: %lu\n", (unsigned long)g_160);
    printf("g_255: %ld\n", (long)g_255);
    printf("g_471: 未在切片中定义\n");
    printf("g_617: 未在切片中定义\n");
    printf("g_624: 未在切片中定义\n");
    printf("g_637: %d\n", g_637);
    printf("g_646: 未在切片中定义\n");

  __retres = 0;
  return __retres;
}


