/* Generated by Frama-C */
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
static int g_sum = 0;
int sum_with_side_effect_slice_1(int count, void * const *__va_params)
{
  va_list args;
  args = __va_params;
  int total = 0;
  {
    int i = 0;
    while (i < count) {
      {
        int tmp;
        tmp = *((int *)*args);
        args ++;
        int val = tmp;
        total += val;
        g_sum += val;
      }
      i ++;
    }
  }
  return total;
}

int sum_simple_slice_1(int count, void * const *__va_params)
{
  va_list args;
  args = __va_params;
  int total = 0;
  {
    int i = 0;
    while (i < count) {
      {
        int tmp;
        tmp = *((int *)*args);
        args ++;
        total += tmp;
      }
      i ++;
    }
  }
  return total;
}

int main(void)
{
  int tmp_2;
  int tmp_3;
  int tmp_4;
  int val = 10;
  int __va_arg0 = 10;
  int __va_arg1 = 20;
  int __va_arg2 = 30;
  void *__va_args[3] = {& __va_arg0, & __va_arg1, & __va_arg2};
  int r1 = sum_with_side_effect_slice_1(3,(void * const *)(__va_args));
  int __va_arg0_18 = 1;
  int __va_arg1_20 = 2;
  int __va_arg2_22 = 3;
  int __va_arg3 = 4;
  void *__va_args_25[4] =
    {& __va_arg0_18, & __va_arg1_20, & __va_arg2_22, & __va_arg3};
  int r2 = sum_simple_slice_1(4,(void * const *)(__va_args_25));
  int __va_arg0_27 = val;
  int __va_arg1_29 = val + 10;
  void *__va_args_31[2] = {& __va_arg0_27, & __va_arg1_29};
  int r3 = sum_with_side_effect_slice_1(2,(void * const *)(__va_args_31));
  {
    int __va_arg0_33 = r1;
    int __va_arg1_35 = r2;
    void *__va_args_37[2] = {& __va_arg0_33, & __va_arg1_35};
    tmp_2 = sum_with_side_effect_slice_1(2,(void * const *)(__va_args_37));
  }
  {
    int __va_arg0_39 = r3;
    int __va_arg1_41 = val;
    void *__va_args_43[2] = {& __va_arg0_39, & __va_arg1_41};
    tmp_3 = sum_simple_slice_1(2,(void * const *)(__va_args_43));
  }
  int r4 = tmp_2 + tmp_3;
  {
    int __va_arg0_45 = val;
    void *__va_args_47[1] = {& __va_arg0_45};
    tmp_4 = sum_with_side_effect_slice_1(1,(void * const *)(__va_args_47));
  }
  if (tmp_4 > 50) val += 10;
  int result = ((((val + r1) + r2) + r3) + r4) + g_sum;
  return result;
}


