/* Generated by Frama-C */
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"

static int g_sum = 0;

int sum_with_side_effect_slice_1(int count, ...)
{
  va_list args;
  va_start(args, count);  // 修复：使用原始方式
  int total = 0;
  {
    int i = 0;
    while (i < count) {
      {
        int val = va_arg(args, int);
        total += val;
        g_sum += val;
      }
      i ++;
    }
  }
  va_end(args);
  return total;
}

int sum_simple_slice_1(int count, ...)
{
  va_list args;
  va_start(args, count);  // 修复：使用原始方式
  int total = 0;
  {
    int i = 0;
    while (i < count) {
      total += va_arg(args, int);
      i ++;
    }
  }
  va_end(args);
  return total;
}

int main(void)
{
  int tmp_2;
  int tmp_3;
  int tmp_4;
  int val = 10;
  int r1 = sum_with_side_effect_slice_1(3, 10, 20, 30);
  int r2 = sum_simple_slice_1(4, 1, 2, 3, 4);
  int r3 = sum_with_side_effect_slice_1(2, val, val + 10);
  tmp_2 = sum_with_side_effect_slice_1(2, r1, r2);
  tmp_3 = sum_simple_slice_1(2, r3, val);
  int r4 = tmp_2 + tmp_3;
  tmp_4 = sum_with_side_effect_slice_1(1, val);
  if (tmp_4 > 50) val += 10;
  int result = ((((val + r1) + r2) + r3) + r4) + g_sum;
  return result;
}