#include <stdio.h>
/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int realsmith_hhN0d_slice_1(void)
{
  int __retres;
  if (1) goto _LOR;
  else {
    _LOR: {
            __retres = 0;
            goto return_label;
          }
  }
  return_label: return __retres;
}

int realsmith_proxy_BNPnC_slice_1(char p_0_fxLyu)
{
  int proxy_ret_vZY08 = realsmith_hhN0d_slice_1();
  return proxy_ret_vZY08;
}

__inline static unsigned int realsmith_7tZsm_slice_1(void) __attribute__((
__used__));
__inline static unsigned int realsmith_7tZsm_slice_1(void)
{
  unsigned int __retres;
  __retres = 0U;
  return __retres;
}

unsigned int realsmith_proxy_jX2pC_slice_1(void)
{
  unsigned int proxy_ret_1QzDz = realsmith_7tZsm_slice_1();
  return proxy_ret_1QzDz;
}

int realsmith_proxy_8bJxO_slice_1(void)
{
  int proxy_ret_7tZsm = realsmith_hhN0d_slice_1();
  return proxy_ret_7tZsm;
}

int realsmith_KgUQ5_slice_1(void)
{
  int proxy_ret_jX2pC = realsmith_hhN0d_slice_1();
  return proxy_ret_jX2pC;
}

int realsmith_proxy_Ea5KT_slice_1(void)
{
  int proxy_ret_KgUQ5 = realsmith_hhN0d_slice_1();
  return proxy_ret_KgUQ5;
}

int realsmith_proxy_uwx85_slice_1(void)
{
  int proxy_ret_8bJxO = realsmith_hhN0d_slice_1();
  return proxy_ret_8bJxO;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1)
{
  int32_t tmp;
  tmp = si1;
  return tmp;
}

static int64_t safe_mod_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 % si2;
  return tmp;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_6 = (int32_t)0x3AD3B315L;
static uint32_t g_9 = (uint32_t)0x0CA9F8D1L;
static int8_t g_13 = (int8_t)0x90L;
static uint32_t g_14 = (uint32_t)0UL;
static uint64_t g_71 = 0UL;
static int32_t const *g_99 = (int32_t const *)0;
static int32_t const ** const g_98 = & g_99;
static int32_t g_106 = (int32_t)(-2L);
static int32_t g_109 = (int32_t)0x519F073EL;
static int32_t g_119[9] =
  {(int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L};
static int64_t g_158 = (int64_t)0x6A1BC1FB248A18BDLL;
static uint32_t g_161 = (uint32_t)0xFA6F0C6FL;
static int8_t *g_204 = & g_13;
static uint64_t g_221 = 18446744073709551610UL;
static uint64_t const g_237 = 18446744073709551615UL;
static uint32_t g_244 = (uint32_t)18446744073709551615UL;
static uint16_t g_312 = (uint16_t)0xD07DL;
static uint16_t const g_436 = (uint16_t)65535UL;
static int32_t *g_466 = (int32_t *)0;
static int32_t g_524[5][5] =
  {{(int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL},
   {(int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL},
   {(int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL},
   {(int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL},
   {(int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL,
    (int32_t)0x672373ACL}};
static int32_t *g_271 = & g_109;
static int32_t **g_270 = & g_271;
static void func_1_slice_1(void);

static void func_2_slice_1(void);

static void func_22_slice_1(uint8_t p_23, int32_t *p_24);

static void func_33_slice_1(void);

static void func_35_slice_1(uint16_t p_37, uint16_t p_39);

static void func_48_slice_1(void);

static int32_t *func_53_slice_1(int32_t *p_54);

static void func_1_slice_1(void)
{
  int32_t l_4[2];
  int i;
  i = 0;
  while (i < 2) {
    l_4[i] = (int32_t)0xF5020F89L;
    i ++;
  }
  func_2_slice_1();
  func_48_slice_1();
  func_35_slice_1((uint16_t)l_4[0],g_436);
  func_33_slice_1();
  func_22_slice_1((uint8_t)l_4[0],& g_6);
  func_2_slice_1();
  return;
}

static void func_2_slice_1(void)
{
  g_9 --;
  g_14 --;
  return;
}

static void func_22_slice_1(uint8_t p_23, int32_t *p_24)
{
  uint32_t tmp;
  uint32_t *l_2509 = & g_14;
  *g_98 = (int32_t const *)p_24;
  tmp = (uint32_t)p_23;
  *l_2509 = tmp;
  if (1) goto _LOR; else _LOR: *p_24 = *(*g_98);
  return;
}

static void func_33_slice_1(void)
{
  g_6 = -9;
  return;
}

static void func_35_slice_1(uint16_t p_37, uint16_t p_39)
{
  uint16_t const l_488 = 0;  // 显式初始化为0
  int32_t tmp_14;
  long tmp;
  uint16_t tmp_13;
  int tmp_1;
  int64_t tmp_11;
  int tmp_10;
  int tmp_12;
  int8_t tmp_0;
  char tmp_15;
  uint64_t l_482 = 0UL;
  int32_t *l_489 = & g_109;
  *g_98 = (int32_t const *)func_53_slice_1(& g_6);
  tmp = realsmith_KgUQ5_slice_1();
  tmp_1 = realsmith_proxy_BNPnC_slice_1((char)((int)((char)p_39) + 63));
  g_161 ++;
  tmp_10 = realsmith_proxy_8bJxO_slice_1();
  tmp_11 = safe_mod_func_int64_t_s_s_slice_1((int64_t)(& g_244 != & g_244),
                                             (int64_t)((int)((uint16_t)(
                                                       ((((tmp_10 + (int)l_488) + (int)g_524[4][4]) + (int)*g_271) + (int)*(*g_270)) - 1194067662)) + (int)l_488));
  tmp_12 = realsmith_proxy_Ea5KT_slice_1();
  tmp_13 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(tmp_11 != (int64_t)(
                                                            (int)((uint16_t)(
                                                            (((((tmp_12 + (int)l_488) + (int)l_482) + (int)p_37) + (int)*g_271) + (int)*(*g_270)) - 117795)) + (int)l_488)));
  tmp_0 = (int8_t)tmp_13;
  *g_204 = tmp_0;
  tmp_14 = safe_mod_func_int32_t_s_s_slice_1(9UL <= (unsigned long)tmp_0);
  tmp_15 = realsmith_proxy_uwx85_slice_1();
  *l_489 |= tmp_14 ^ ((int)((uint16_t)(((int)tmp_15 + (int)((char)l_488)) - 81)) + (int)l_488);
  l_482 = (uint64_t)0;
  while (l_482 <= (uint64_t)1) {
    g_158 = (int64_t)1;
    while (g_158 >= (int64_t)0) g_158 -= (int64_t)1;
    l_482 += (uint64_t)1;
  }
  g_221 = (uint64_t)(-29);
  while (g_221 >= (uint64_t)25) {
    g_71 = (uint64_t)7;
    g_106 = 1;
    while (g_106 >= 0) g_106 --;
    g_221 ++;
  }
  return;
}

static void func_48_slice_1(void)
{
  g_71 ++;
  return;
}

static int32_t *func_53_slice_1(int32_t *p_54)
{
  int32_t *__retres;
  g_6 = 0;
  __retres = p_54;
  goto return_label;
  return_label: return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_6: %d\n", g_6);
    printf("g_106: %d\n", g_106);
    printf("g_109: %d\n", g_109);
    printf("g_9: %lu\n", (unsigned long)g_9);
    printf("g_13: %d\n", (int)g_13);
    printf("g_71: %lu\n", (unsigned long)g_71);
    printf("g_14: %lu\n", (unsigned long)g_14);
    printf("g_158: %ld\n", (long)g_158);
    printf("g_161: %lu\n", (unsigned long)g_161);
    printf("g_221: %lu\n", (unsigned long)g_221);

  __retres = 0;
  return __retres;
}