/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int realsmith_hhN0d_slice_1(void)
{
  int __retres;
  if (1) goto _LOR;
  else {
    _LOR: {
            __retres = 0;
            goto return_label;
          }
  }
  return_label: return __retres;
}

int realsmith_proxy_BNPnC_slice_1(char p_0_fxLyu)
{
  int proxy_ret_vZY08 = realsmith_hhN0d_slice_1();
  return proxy_ret_vZY08;
}

__inline static unsigned int realsmith_7tZsm_slice_1(void) __attribute__((
__used__));
__inline static unsigned int realsmith_7tZsm_slice_1(void)
{
  unsigned int events = (unsigned int)0;
  return events;
}

static int realsmith_QCdNf_slice_1(void) __attribute__((__used__));

static int realsmith_QCdNf_slice_1(void) __attribute__((__used__));
static int realsmith_QCdNf_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_8bJxO_slice_1(void)
{
  int proxy_ret_Oq0K2 = realsmith_QCdNf_slice_1();
  return proxy_ret_Oq0K2;
}

__inline static long realsmith_LphaZ_slice_1(long b, long c) __attribute__((
__used__));
__inline static long realsmith_LphaZ_slice_1(long b, long c)
{
  b = c;
  return b;
}

static int realsmith_skpCk_slice_1(void) __attribute__((__used__));
static int realsmith_skpCk_slice_1(void)
{
  int __retres;
  int year;
  year = 400 * 1;
  __retres = year + 2000;
  return __retres;
}

int realsmith_proxy_pGf3v_slice_1(void)
{
  int proxy_ret_xTitQ = realsmith_skpCk_slice_1();
  return proxy_ret_xTitQ;
}

static int realsmith_fiMiq_slice_1(void) __attribute__((__used__));
static int realsmith_fiMiq_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_Ea5KT_slice_1(void)
{
  int proxy_ret_jBip8 = realsmith_fiMiq_slice_1();
  return proxy_ret_jBip8;
}

__inline static char *realsmith_OhMLR_slice_1(char *text) __attribute__((
__used__));
__inline static char *realsmith_OhMLR_slice_1(char *text)
{
  char *__retres;
  char *ptr = text;
  char *kptr = text;
  goto break_cont_1;
  break_cont_1: kptr = ptr;
  __retres = kptr;
  return __retres;
}

char realsmith_proxy_gOBVs_slice_1(char p_0_HEphr, int p_1_cHjeB)
{
  char __retres;
  char proxy_1DNYH[10] =
    {(char)65,
     (char)0,
     p_0_HEphr,
     (char)73,
     p_0_HEphr,
     (char)67,
     (char)9,
     (char)70,
     (char)41,
     (char)20};
  char *proxy_ret_76RXC = realsmith_OhMLR_slice_1(proxy_1DNYH);
  __retres = *proxy_ret_76RXC;
  return __retres;
}

static char *realsmith_712QR_slice_1(void) __attribute__((__used__));
static char *realsmith_712QR_slice_1(void)
{
  char *buf;
  buf = (char *)"0";
  return buf;
}

char realsmith_proxy_uwx85_slice_1(void)
{
  char __retres;
  char *proxy_ret_d6jWu = realsmith_712QR_slice_1();
  __retres = *proxy_ret_d6jWu;
  return __retres;
}

__inline static int realsmith_3Mx5x_slice_1(unsigned long long u) __attribute__((
__used__));
__inline static int realsmith_3Mx5x_slice_1(unsigned long long u)
{
  int __retres;
  __retres = u < 1ULL << 55;
  return __retres;
}

long realsmith_KgUQ5_slice_1(void)
{
  long __retres;
  __retres = (long)1;
  return __retres;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1)
{
  int32_t tmp;
  tmp = si1;
  return tmp;
}

static int64_t safe_mod_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 % si2;
  return tmp;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_6 = (int32_t)0x3AD3B315L;
static uint32_t g_9 = (uint32_t)0x0CA9F8D1L;
static int8_t g_13 = (int8_t)0x90L;
static uint32_t g_14 = (uint32_t)0UL;
static uint64_t g_71 = 0UL;
static int32_t const *g_99 = (int32_t const *)0;
static int32_t const ** const g_98 = & g_99;
static int32_t g_106 = (int32_t)(-2L);
static int32_t g_109 = (int32_t)0x519F073EL;
static int16_t g_112[7] =
  {(int16_t)1L,
   (int16_t)1L,
   (int16_t)1L,
   (int16_t)1L,
   (int16_t)1L,
   (int16_t)1L,
   (int16_t)1L};
static int32_t g_119[9] =
  {(int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L};
static int64_t g_158 = (int64_t)0x6A1BC1FB248A18BDLL;
static uint32_t g_161 = (uint32_t)0xFA6F0C6FL;
static int8_t *g_204 = & g_13;
static uint64_t g_221 = 18446744073709551610UL;
static uint64_t const g_237 = 18446744073709551615UL;
static uint32_t g_244 = (uint32_t)18446744073709551615UL;
static int16_t *g_271 = & g_112[3];
static int16_t **g_270 = & g_271;
static uint16_t g_312 = (uint16_t)0xD07DL;
static uint16_t g_400[1][3][9] =
  {{{(uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL},
    {(uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL,
     (uint16_t)65535UL},
    {(uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL,
     (uint16_t)0x279FL}}};
static uint16_t const g_436 = (uint16_t)65535UL;
static int32_t *g_466 = (int32_t *)0;
static int64_t g_524[5][6] =
  {{(int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x1639882173A13C76LL,
    (int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x1639882173A13C76LL,
    -1L},
   {(int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x805E9E55472B3AAALL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x805E9E55472B3AAALL,
    (int64_t)0x7B09303C9F13F672LL},
   {(int64_t)0x7B09303C9F13F672LL,
    (int64_t)0xC9576F69CF8D5809LL,
    -1L,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0xC9576F69CF8D5809LL,
    (int64_t)0x7475A7284693693FLL},
   {(int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x1639882173A13C76LL,
    (int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x1639882173A13C76LL,
    -1L},
   {(int64_t)0x7B09303C9F13F672LL,
    (int64_t)0x805E9E55472B3AAALL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x7475A7284693693FLL,
    (int64_t)0x805E9E55472B3AAALL,
    (int64_t)0x7B09303C9F13F672LL}};
static uint16_t *g_1012 = & g_400[0][0][5];
static uint64_t *g_1276 = & g_71;
static int8_t **g_1894 = & g_204;
static uint16_t **g_2112 = & g_1012;
static uint16_t ***g_2111 = & g_2112;
static uint16_t ****g_2110 = & g_2111;
static int16_t * const *g_2291 = (int16_t * const *)(& g_271);
static int16_t * const ** const g_2290 = & g_2291;
static int16_t * const ** const *g_2289 = & g_2290;
static uint64_t **g_2375[6][3][1] =
  {{{& g_1276}, {& g_1276}, {& g_1276}},
   {{& g_1276}, {& g_1276}, {& g_1276}},
   {{& g_1276}, {& g_1276}, {& g_1276}},
   {{& g_1276}, {& g_1276}, {& g_1276}},
   {{& g_1276}, {& g_1276}, {& g_1276}},
   {{& g_1276}, {& g_1276}, {& g_1276}}};
static uint64_t ***g_2374 = & g_2375[2][1][0];
static uint64_t ****g_2373 = & g_2374;
static uint64_t *****g_2372 = & g_2373;
static void func_1_slice_1(void);

static void func_2_slice_1(void);

static void func_22_slice_1(uint8_t p_23, int32_t *p_24);

static void func_33_slice_1(void);

static void func_35_slice_1(uint16_t p_37, uint16_t p_39);

static void func_48_slice_1(void);

static int32_t *func_53_slice_1(int32_t *p_54);

static void func_1_slice_1(void)
{
  int32_t l_4[2];
  int i;
  int tmp_5;
  int tmp_6;
  unsigned int tmp_18;
  i = 0;
  while (i < 2) {
    l_4[i] = (int32_t)0xF5020F89L;
    i ++;
  }
  func_2_slice_1();
  tmp_5 = realsmith_3Mx5x_slice_1((unsigned long long)((int)g_237 + 84));
  tmp_6 = realsmith_proxy_pGf3v_slice_1();
  func_48_slice_1();
  func_35_slice_1((uint16_t)((uint64_t)((((tmp_6 + (int)g_237) + g_119[3]) + (int)g_436) - 67934) + g_237),
                  (uint16_t)((int)((uint16_t)((((tmp_5 + (int)g_436) + g_119[3]) + (int)g_237) - 65535)) + (int)g_436));
  func_33_slice_1();
  tmp_18 = realsmith_7tZsm_slice_1();
  func_22_slice_1((uint8_t)((int32_t)((long)(tmp_18 + (unsigned int)l_4[0]) - 4110552969) + l_4[0]),
                  & g_6);
  func_2_slice_1();
  return;
}

static void func_2_slice_1(void)
{
  g_9 --;
  g_14 --;
  return;
}

static void func_22_slice_1(uint8_t p_23, int32_t *p_24)
{
  long tmp_3;
  uint32_t tmp_2;
  uint32_t *l_2509 = & g_14;
  *g_98 = (int32_t const *)p_24;
  tmp_3 = realsmith_LphaZ_slice_1((long)p_23 + (long)(-63),
                                  (long)p_23 + (long)(-74));
  tmp_2 = (uint32_t)((int)((uint8_t)((tmp_3 + (long)p_23) - (long)200)) + (int)p_23);
  *l_2509 = tmp_2;
  if (1) goto _LOR;
  else {
    _LOR:
    {
      char tmp;
      tmp = realsmith_proxy_gOBVs_slice_1((char)((int)((char)*(*g_98)) + 13),
                                          *(*g_98) + 9);
      *p_24 = (((int)tmp + (int)((char)*(*g_98))) - 56) + *(*g_98);
    }
  }
  return;
}

static void func_33_slice_1(void)
{
  g_6 = -9;
  return;
}

static void func_35_slice_1(uint16_t p_37, uint16_t p_39)
{
  uint16_t const l_488;
  int32_t tmp_14;
  long tmp;
  uint16_t tmp_13;
  int tmp_1;
  int64_t tmp_11;
  int tmp_10;
  int tmp_12;
  int8_t tmp_0;
  char tmp_15;
  uint64_t l_482 = 0UL;
  int32_t *l_489 = & g_109;
  *g_98 = (int32_t const *)func_53_slice_1(& g_6);
  tmp = realsmith_KgUQ5_slice_1();
  tmp_1 = realsmith_proxy_BNPnC_slice_1((char)((int)((char)p_39) + 63));
  g_161 ++;
  tmp_10 = realsmith_proxy_8bJxO_slice_1();
  tmp_11 = safe_mod_func_int64_t_s_s_slice_1((int64_t)(& g_244 != & g_244),
                                             (int64_t)((int)((uint16_t)(
                                                       ((((tmp_10 + (int)l_488) + (int)g_524[4][4]) + (int)*g_271) + (int)*(*g_270)) - 1194067662)) + (int)l_488));
  tmp_12 = realsmith_proxy_Ea5KT_slice_1();
  tmp_13 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(tmp_11 != (int64_t)(
                                                            (int)((uint16_t)(
                                                            (((((tmp_12 + (int)l_488) + (int)l_482) + (int)p_37) + (int)*g_271) + (int)*(*g_270)) - 117795)) + (int)l_488)));
  tmp_0 = (int8_t)tmp_13;
  *g_204 = tmp_0;
  tmp_14 = safe_mod_func_int32_t_s_s_slice_1(9UL <= (unsigned long)tmp_0);
  tmp_15 = realsmith_proxy_uwx85_slice_1();
  *l_489 |= tmp_14 ^ ((int)((uint16_t)(((int)tmp_15 + (int)((char)l_488)) - 81)) + (int)l_488);
  l_482 = (uint64_t)0;
  while (l_482 <= (uint64_t)1) {
    g_158 = (int64_t)1;
    while (g_158 >= (int64_t)0) g_158 -= (int64_t)1;
    l_482 += (uint64_t)1;
  }
  g_221 = (uint64_t)(-29);
  while (g_221 >= (uint64_t)25) {
    g_71 = (uint64_t)7;
    g_106 = 1;
    while (g_106 >= 0) g_106 --;
    g_221 ++;
  }
  return;
}

static void func_48_slice_1(void)
{
  g_71 ++;
  return;
}

static int32_t *func_53_slice_1(int32_t *p_54)
{
  int32_t *__retres;
  g_6 = 0;
  __retres = p_54;
  goto return_label;
  return_label: return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


