/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1)
{
  int32_t tmp;
  tmp = si1;
  return tmp;
}

static int64_t safe_mod_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 % si2;
  return tmp;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_6 = (int32_t)0x3AD3B315L;
static uint32_t g_9 = (uint32_t)0x0CA9F8D1L;
static int8_t g_13 = (int8_t)0x90L;
static uint32_t g_14 = (uint32_t)0UL;
static uint64_t g_71 = 0UL;
static int32_t const *g_99 = (int32_t const *)0;
static int32_t const ** const g_98 = & g_99;
static int32_t g_106 = (int32_t)(-2L);
static int32_t g_109 = (int32_t)0x519F073EL;
static int32_t g_119[9] =
  {(int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L,
   (int32_t)0L};
static int64_t g_158 = (int64_t)0x6A1BC1FB248A18BDLL;
static uint32_t g_161 = (uint32_t)0xFA6F0C6FL;
static int8_t *g_204 = & g_13;
static uint64_t g_221 = 18446744073709551610UL;
static uint64_t const g_237 = 18446744073709551615UL;
static uint32_t g_244 = (uint32_t)18446744073709551615UL;
static uint16_t g_312 = (uint16_t)0xD07DL;
static uint16_t const g_436 = (uint16_t)65535UL;
static int32_t *g_466 = (int32_t *)0;
static void func_1_slice_1(void);

static void func_2_slice_1(void);

static void func_22_slice_1(uint8_t p_23, int32_t *p_24);

static void func_33_slice_1(void);

static void func_35_slice_1(uint16_t p_39);

static void func_48_slice_1(void);

static int32_t *func_53_slice_1(int32_t *p_54);

static void func_1_slice_1(void)
{
  int32_t l_4[2];
  int i;
  i = 0;
  while (i < 2) {
    l_4[i] = (int32_t)0xF5020F89L;
    i ++;
  }
  func_2_slice_1();
  func_48_slice_1();
  func_35_slice_1(g_436);
  func_33_slice_1();
  func_22_slice_1((uint8_t)l_4[0],& g_6);
  func_2_slice_1();
  return;
}

static void func_2_slice_1(void)
{
  g_9 --;
  g_14 --;
  return;
}

static void func_22_slice_1(uint8_t p_23, int32_t *p_24)
{
  uint32_t tmp;
  uint32_t *l_2509 = & g_14;
  *g_98 = (int32_t const *)p_24;
  tmp = (uint32_t)p_23;
  *l_2509 = tmp;
  if (1) goto _LOR; else _LOR: *p_24 = *(*g_98);
  return;
}

static void func_33_slice_1(void)
{
  g_6 = -9;
  return;
}

static void func_35_slice_1(uint16_t p_39)
{
  uint64_t l_482;
  uint16_t const l_488;
  int32_t tmp_7;
  uint16_t tmp_6;
  int64_t tmp_5;
  int8_t tmp;
  int32_t *l_489 = & g_109;
  *g_98 = (int32_t const *)func_53_slice_1(& g_6);
  g_161 ++;
  tmp_5 = safe_mod_func_int64_t_s_s_slice_1((int64_t)(& g_244 != & g_244),
                                            (int64_t)l_488);
  tmp_6 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(tmp_5 != (int64_t)l_488));
  tmp = (int8_t)tmp_6;
  *g_204 = tmp;
  tmp_7 = safe_mod_func_int32_t_s_s_slice_1(9UL <= (unsigned long)tmp);
  *l_489 |= tmp_7 ^ (int)l_488;
  l_482 = (uint64_t)0;
  while (l_482 <= (uint64_t)1) {
    g_158 = (int64_t)1;
    while (g_158 >= (int64_t)0) g_158 -= (int64_t)1;
    l_482 += (uint64_t)1;
  }
  g_221 = (uint64_t)(-29);
  while (g_221 >= (uint64_t)25) {
    g_71 = (uint64_t)7;
    g_106 = 1;
    while (g_106 >= 0) g_106 --;
    g_221 ++;
  }
  return;
}

static void func_48_slice_1(void)
{
  g_71 ++;
  return;
}

static int32_t *func_53_slice_1(int32_t *p_54)
{
  int32_t *__retres;
  g_6 = 0;
  __retres = p_54;
  goto return_label;
  return_label: return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


