/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g = 0U;
int main(void)
{
  int __retres;
  uint32_t out = g + 1U;
  __retres = (int)(out & 0xFFU);
  return __retres;
}


