/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
long realsmith_p1ATZ_slice_1(void)
{
  long colibri_carrier_offset = (long)0;
  colibri_carrier_offset = (long)4832000;
  return colibri_carrier_offset;
}

static int realsmith_eKy7U_slice_1(void) __attribute__((__used__));
static int realsmith_eKy7U_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_ruYVY_slice_1(int p_1_TYlBq)
{
  int proxy_ret_FvgCU = realsmith_eKy7U_slice_1();
  return proxy_ret_FvgCU;
}

__inline static int realsmith_DLSRM_slice_1(int channel) __attribute__((
__used__));
__inline static int realsmith_DLSRM_slice_1(int channel)
{
  int __retres;
  __retres = 0xc0 + 0x4 * channel;
  return __retres;
}

unsigned int control_cpu_realsmith_UWVAf = (unsigned int)2;
static int realsmith_UWVAf_slice_1(unsigned int cpu) __attribute__((__used__));
static int realsmith_UWVAf_slice_1(unsigned int cpu)
{
  int __retres;
  if (cpu != control_cpu_realsmith_UWVAf) {
    __retres = 0;
    goto return_label;
  }
  control_cpu_realsmith_UWVAf = (unsigned int)1;
  if (control_cpu_realsmith_UWVAf == cpu) control_cpu_realsmith_UWVAf = (unsigned int)1;
  __retres = 0;
  return_label: return __retres;
}

__inline static int realsmith_bOJFf_slice_1(void) __attribute__((__used__));
__inline static int realsmith_bOJFf_slice_1(void)
{
  int tmp;
  tmp = 0;
  return tmp;
}

int realsmith_proxy_NNUAV_slice_1(void)
{
  int proxy_ret_WlCS9 = realsmith_bOJFf_slice_1();
  return proxy_ret_WlCS9;
}

static int realsmith_1eiWC_slice_1(void) __attribute__((__used__));
static int realsmith_1eiWC_slice_1(void)
{
  int c = 1;
  return c;
}

static int realsmith_UTlgl_slice_1(void) __attribute__((__used__));
static int realsmith_UTlgl_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

static int realsmith_e50tp_slice_1(int op) __attribute__((__used__));
static int realsmith_e50tp_slice_1(int op)
{
  int __retres;
  switch (op) {
    case 133: case 132: case 128: case 131: case 130: case 129: __retres = 1;
    goto return_label;
    default: __retres = 0;
  }
  return_label: return __retres;
}

__inline static long realsmith_3cjHK_slice_1(long foo) __attribute__((
__used__));
__inline static long realsmith_3cjHK_slice_1(long foo)
{
  return foo;
}

__inline static int realsmith_QwmmW_slice_1(void) __attribute__((__used__));
__inline static int realsmith_QwmmW_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_f0Qal_slice_1(void)
{
  int proxy_ret_rtAVz = realsmith_QwmmW_slice_1();
  return proxy_ret_rtAVz;
}

char const *realsmith_Jo9Kj_slice_1(char const *text)
{
  char const *__retres;
  int i;
  i = 0;
  while ((int)*(text + i) != '\000') i ++;
  __retres = text + i;
  return __retres;
}

char realsmith_proxy_kBxuX_slice_1(char p_0_sVjwJ, int p_1_8h9Du)
{
  char __retres;
  char proxy_cdh3K[15] =
    {p_0_sVjwJ,
     p_0_sVjwJ,
     p_0_sVjwJ,
     (char)0,
     p_0_sVjwJ,
     p_0_sVjwJ,
     (char)100,
     (char)18,
     p_0_sVjwJ,
     p_0_sVjwJ,
     (char)55,
     (char)25,
     p_0_sVjwJ,
     (char)46,
     p_0_sVjwJ};
  char *proxy_ret_BQuQ9 =
    realsmith_Jo9Kj_slice_1((char const *)(proxy_cdh3K));
  __retres = *proxy_ret_BQuQ9;
  return __retres;
}

static int realsmith_ua2V7_slice_1(int *array, int item) __attribute__((
__used__));
static int realsmith_ua2V7_slice_1(int *array, int item)
{
  int __retres;
  int i;
  i = 0;
  while (1) {
    if (*(array + i) == item) {
      __retres = i;
      goto return_label;
    }
    i ++;
  }
  return_label: return __retres;
}

int realsmith_proxy_Sxa9Y_slice_1(int p_0_HA4Tr, int p_1_krus3)
{
  int proxy_C0xOB[11] =
    {53, p_0_HA4Tr, p_0_HA4Tr, 92, 44, p_0_HA4Tr, 79, 22, 12, 69, 62};
  int proxy_ret_GTDUL = realsmith_ua2V7_slice_1(proxy_C0xOB,p_1_krus3);
  return proxy_ret_GTDUL;
}

static int realsmith_J8pT8_slice_1(void) __attribute__((__used__));
static int realsmith_J8pT8_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_GrZiB_slice_1(void)
{
  int ret;
  ret = 1;
  return ret;
}

int realsmith_proxy_2ZdNU_slice_1(void)
{
  int proxy_ret_48lEa = realsmith_GrZiB_slice_1();
  return proxy_ret_48lEa;
}

long realsmith_sp4gY_slice_1(long *pFile)
{
  long uChars = (long)0;
  while (*pFile) {
    uChars ++;
    pFile ++;
  }
  return uChars;
}

long realsmith_proxy_vnDcJ_slice_1(long p_0_d6Pug)
{
  long proxy_T4aFD[13] =
    {(long)13,
     p_0_d6Pug,
     p_0_d6Pug,
     (long)0,
     p_0_d6Pug,
     (long)58,
     p_0_d6Pug,
     p_0_d6Pug,
     (long)82,
     (long)91,
     p_0_d6Pug,
     p_0_d6Pug,
     p_0_d6Pug};
  long proxy_ret_XPMom = realsmith_sp4gY_slice_1(proxy_T4aFD);
  return proxy_ret_XPMom;
}

int ESP_GATT_OK_realsmith_VRvWa = 7;
int realsmith_VRvWa_slice_1(void)
{
  return ESP_GATT_OK_realsmith_VRvWa;
}

int realsmith_proxy_guzdj_slice_1(void)
{
  int proxy_ret_0SyTq = realsmith_VRvWa_slice_1();
  return proxy_ret_0SyTq;
}

int INAT_GRP_MASK_realsmith_mMsrz = 2;
int INAT_GRP_OFFS_realsmith_mMsrz = 5;
__inline static int realsmith_mMsrz_slice_1(int attr) __attribute__((
__used__));
__inline static int realsmith_mMsrz_slice_1(int attr)
{
  int __retres;
  __retres = (attr & INAT_GRP_MASK_realsmith_mMsrz) >> INAT_GRP_OFFS_realsmith_mMsrz;
  return __retres;
}

static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_mod_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_div_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  if ((int)si1 == -128) tmp = (int)si1 / (int)si2;
  else tmp = (int)si1 / (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left; else tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_div_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1;
  else 
    if ((int)si1 == -32768) tmp = (int)si1; else tmp = (int)si1 / (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int16_t safe_lshift_func_int16_t_s_s_slice_1(int16_t left, int right)
{
  int16_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left;
    else 
      if (right >= 32) tmp = (int)left;
      else 
        if ((int)left > 32767 >> right) tmp = (int)left;
        else tmp = (int)left << right;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_div_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si2 == 0) tmp = si1; else tmp = si1 / si2;
  return tmp;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint8_t safe_lshift_func_uint8_t_u_s_slice_1(uint8_t left, int right)
{
  uint8_t __retres;
  int tmp;
  if (right < 0) tmp = (int)left;
  else 
    if (right >= 32) tmp = (int)left;
    else 
      if ((int)left > 255 >> right) tmp = (int)left;
      else tmp = (int)left << right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if ((int)left > 65535 >> right) tmp = (int)left;
  else tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint64_t safe_add_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 + ui2;
  return __retres;
}

static uint64_t safe_mod_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  if (ui2 == (uint64_t)0) tmp = ui1; else tmp = ui1 % ui2;
  return tmp;
}

static int32_t g_2 = (int32_t)0x4E064826L;
static int32_t g_6 = (int32_t)9L;
static uint8_t g_20 = (uint8_t)0x2BL;
static uint64_t g_26 = (uint64_t)0xB659BAAA4F69A750LL;
static int32_t *g_45 = & g_6;
static int32_t **g_44 = & g_45;
static int32_t g_68 = (int32_t)(-1L);
static int16_t g_88 = (int16_t)(-1L);
static uint16_t g_90 = (uint16_t)1UL;
static uint16_t g_131 = (uint16_t)65535UL;
static uint8_t g_150 = (uint8_t)250UL;
static uint32_t g_168 = (uint32_t)0xA92D9FAAL;
static int32_t *g_186 = & g_2;
static int32_t **g_185 = & g_186;
static int64_t g_197[7][8][2] =
  {{{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}}};
static int32_t g_222 = (int32_t)0xA699A93FL;
static uint32_t g_224 = (uint32_t)0UL;
static uint32_t g_260 = (uint32_t)0x40F3676AL;
static int16_t g_298 = (int16_t)0x6F54L;
static int8_t g_347 = (int8_t)(-1L);
static uint8_t g_372 = (uint8_t)0x8CL;
static int32_t *g_514[5][1][1] =
  {{{& g_2}}, {{& g_2}}, {{& g_2}}, {{& g_2}}, {{& g_2}}};
static int32_t ** const g_513 = & g_514[1][0][0];
static uint16_t const *g_575 = (uint16_t const *)(& g_131);
static uint16_t const * const *g_574 = (uint16_t const * const *)(& g_575);
static int64_t * const g_626 = & g_197[5][0][1];
static int64_t * const *g_625 = & g_626;
static int16_t g_655 = (int16_t)0xEAD6L;
static uint64_t *g_742 = & g_26;
static int8_t const g_763 = (int8_t)(-1L);
static uint32_t g_802[9][8][3] =
  {{{(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0xCB2E23F6L},
    {(uint32_t)7UL, (uint32_t)0xFFC5D4D8L, (uint32_t)18446744073709551612UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)0x224F8A36L, (uint32_t)0x8C2021E4L},
    {(uint32_t)7UL, (uint32_t)0UL, (uint32_t)7UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0x6BAE6C21L},
    {(uint32_t)7UL, (uint32_t)18446744073709551612UL, (uint32_t)0xCB5DC14CL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0xCB2E23F6L},
    {(uint32_t)7UL, (uint32_t)0xFFC5D4D8L, (uint32_t)18446744073709551612UL}},
   {{(uint32_t)0xCB2E23F6L, (uint32_t)0x224F8A36L, (uint32_t)0x8C2021E4L},
    {(uint32_t)7UL, (uint32_t)0UL, (uint32_t)7UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}},
   {{(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L}},
   {{(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}},
   {{(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L}},
   {{(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}}};
static uint8_t *g_910 = & g_372;
static uint8_t **g_909 = & g_910;
static int64_t **g_1019 = (int64_t **)0;
static int64_t ***g_1018 = & g_1019;
static uint8_t g_1136 = (uint8_t)0xB0L;
static int8_t *g_1539[7][2][1] =
  {{{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}}};
static uint32_t g_1542 = (uint32_t)4294967295UL;
static uint64_t g_1854 = 18446744073709551614UL;
static int32_t g_1869 = (int32_t)0x820F5903L;
static uint16_t g_1974 = (uint16_t)1UL;
static uint8_t g_2003[1] = {(uint8_t)0x21L};
static uint8_t ***g_2012[5][1] =
  {{& g_909}, {& g_909}, {& g_909}, {& g_909}, {& g_909}};
static uint8_t ****g_2011 = & g_2012[2][0];
static uint8_t ***** const g_2010 = & g_2011;
static int16_t const g_2177 = (int16_t)0x14F2L;
static uint16_t *g_2191 = & g_90;
static void func_1_slice_1(void);

static void func_32_slice_1(int64_t const p_35);

static void func_52_slice_1(int8_t const p_53, uint64_t p_54, int32_t p_55);

static void func_76_slice_1(int32_t *p_77, uint32_t p_78);

static void func_82_slice_1(int32_t p_84, int32_t p_85, uint32_t const p_86,
                            uint64_t p_87);

static void func_93_slice_1(int32_t p_94);

static void func_98_slice_1(void);

static void func_1_slice_1(void)
{
  long tmp_1;
  int tmp_6;
  int tmp_7;
  int8_t tmp_11;
  int16_t tmp_10;
  uint64_t tmp_9;
  int tmp_8;
  int8_t l_14[4] =
    {(int8_t)0xC4L, (int8_t)0xC4L, (int8_t)0xC4L, (int8_t)0xC4L};
  int32_t l_62 = (int32_t)0x9C81B934L;
  g_2 = -23;
  g_6 = 0;
  while (g_6 <= 3) {
    g_20 = (uint8_t)((int)g_20 + 1);
    g_2 ^= (int)l_14[g_6];
    g_6 ++;
  }
  goto break_cont_1;
  break_cont_1:
  tmp_1 = realsmith_proxy_vnDcJ_slice_1((long)g_6 + (long)(-6));
  tmp_6 = realsmith_proxy_2ZdNU_slice_1();
  tmp_7 = realsmith_proxy_f0Qal_slice_1();
  tmp_8 = realsmith_mMsrz_slice_1(g_6 + 3);
  tmp_9 = safe_mod_func_uint64_t_u_u_slice_1((uint64_t)g_2,
                                             (uint64_t)((((tmp_8 + g_6) + (int)g_20) - 51) + g_6));
  tmp_10 = safe_div_func_int16_t_s_s_slice_1((int16_t)tmp_9,(int16_t)(-1L));
  tmp_11 = safe_div_func_int8_t_s_s_slice_1((int8_t)tmp_10,(int8_t)g_2);
  func_52_slice_1(tmp_11,
                  (uint64_t)(((((tmp_7 + l_62) + (int)g_20) + g_6) - -1669219992) + l_62),
                  (((tmp_6 + g_6) + (int)g_20) - 52) + g_6);
  func_32_slice_1((int64_t)((int)((int16_t)((((((tmp_1 + (long)g_2177) + (long)g_6) + (long)g_802[7][2][2]) + (long)g_20) + (long)g_763) - (long)5421)) + (int)g_2177));
  return;
}

static void func_32_slice_1(int64_t const p_35)
{
  int16_t tmp_1;
  int16_t tmp_2;
  int64_t l_2532 = (int64_t)0x0D4D81558201ED89LL;
  int16_t *l_2546 = & g_655;
  int16_t *l_2547 = & g_298;
  tmp_1 = (int16_t)p_35;
  *l_2546 = tmp_1;
  tmp_2 = (int16_t)l_2532;
  *l_2547 = tmp_2;
  return;
}

static void func_52_slice_1(int8_t const p_53, uint64_t p_54, int32_t p_55)
{
  uint8_t const ** const *** const l_2013;
  uint64_t l_1516 = 18446744073709551612UL;
  {
    int32_t l_1965;
    int tmp_1;
    int tmp_6;
    int8_t tmp_57;
    int32_t tmp_56;
    int tmp_50;
    uint16_t tmp_55;
    int32_t * const *l_75 = (int32_t * const *)(& g_45);
    uint16_t *l_89 = & g_90;
    uint32_t l_1517 = (uint32_t)0x1D5DDCBFL;
    int32_t *l_1861 = & g_6;
    tmp_1 = realsmith_e50tp_slice_1((int)p_54 + 1669220143);
    func_93_slice_1(*(*g_44));
    tmp_6 = realsmith_proxy_ruYVY_slice_1((int)l_1517 + -492690570);
    *l_89 = (uint16_t)((int)*l_89 - 1);
    func_82_slice_1((int32_t)p_54,(int32_t)p_53,
                    (uint32_t)((uint32_t)p_53 <= (uint32_t)((((tmp_6 + (int)l_1517) + (int)l_1516) + (int)p_53) - 492690619) + l_1517),
                    (uint64_t)((((tmp_1 + (int)p_54) + (int)l_1516) + (int)p_53) - -1669220048) + p_54);
    func_76_slice_1(l_1861,g_802[4][4][0]);
    g_1136 = (uint8_t)0;
    while ((int)g_1136 <= 7) {
      {
        uint8_t l_1942[2][5][9] =
          {{{(uint8_t)0xD8L,
             (uint8_t)0xEEL,
             (uint8_t)0x27L,
             (uint8_t)0xE3L,
             (uint8_t)5UL,
             (uint8_t)0xE3L,
             (uint8_t)0x27L,
             (uint8_t)0xEEL,
             (uint8_t)0xD8L},
            {(uint8_t)252UL,
             (uint8_t)1UL,
             (uint8_t)0xBDL,
             (uint8_t)0x27L,
             (uint8_t)0UL,
             (uint8_t)0xEEL,
             (uint8_t)0x72L,
             (uint8_t)0xEEL,
             (uint8_t)0UL},
            {(uint8_t)253UL,
             (uint8_t)0x72L,
             (uint8_t)0x72L,
             (uint8_t)253UL,
             (uint8_t)0xE3L,
             (uint8_t)1UL,
             (uint8_t)249UL,
             (uint8_t)0UL,
             (uint8_t)0xBDL},
            {(uint8_t)252UL,
             (uint8_t)0UL,
             (uint8_t)0x72L,
             (uint8_t)6UL,
             (uint8_t)6UL,
             (uint8_t)0x72L,
             (uint8_t)0UL,
             (uint8_t)252UL,
             (uint8_t)5UL},
            {(uint8_t)0xD8L,
             (uint8_t)6UL,
             (uint8_t)0xBDL,
             (uint8_t)252UL,
             (uint8_t)0xE3L,
             (uint8_t)0UL,
             (uint8_t)0UL,
             (uint8_t)0xE3L,
             (uint8_t)252UL}},
           {{(uint8_t)0x27L,
             (uint8_t)0xD8L,
             (uint8_t)0x27L,
             (uint8_t)1UL,
             (uint8_t)0UL,
             (uint8_t)6UL,
             (uint8_t)249UL,
             (uint8_t)5UL,
             (uint8_t)5UL},
            {(uint8_t)0x72L,
             (uint8_t)0xD8L,
             (uint8_t)5UL,
             (uint8_t)0UL,
             (uint8_t)5UL,
             (uint8_t)0xD8L,
             (uint8_t)0x72L,
             (uint8_t)249UL,
             (uint8_t)0xBDL},
            {(uint8_t)249UL,
             (uint8_t)6UL,
             (uint8_t)0UL,
             (uint8_t)1UL,
             (uint8_t)0x27L,
             (uint8_t)0xD8L,
             (uint8_t)0x27L,
             (uint8_t)1UL,
             (uint8_t)0UL},
            {(uint8_t)0UL,
             (uint8_t)0UL,
             (uint8_t)0xE3L,
             (uint8_t)252UL,
             (uint8_t)0xBDL,
             (uint8_t)6UL,
             (uint8_t)0xD8L,
             (uint8_t)249UL,
             (uint8_t)0xD8L},
            {(uint8_t)0UL,
             (uint8_t)0x72L,
             (uint8_t)6UL,
             (uint8_t)6UL,
             (uint8_t)0x72L,
             (uint8_t)0UL,
             (uint8_t)252UL,
             (uint8_t)5UL,
             (uint8_t)253UL}}};
        {
          uint32_t const l_1935;
          uint8_t tmp_40;
          int tmp_38;
          char tmp_39;
          tmp_38 = realsmith_proxy_Sxa9Y_slice_1((int)l_1942[0][2][8] + -200,
                                                 (int)l_1942[0][2][8] + -145);
          tmp_39 = realsmith_proxy_kBxuX_slice_1((char)((int)((char)l_1935) + -17),
                                                 (int)l_1935 + 4);
          tmp_40 = safe_lshift_func_uint8_t_u_s_slice_1((uint8_t)((uint32_t)(
                                                                  ((int)tmp_39 + (int)((char)l_1935)) - 4) + l_1935),
                                                        (int)((uint8_t)(
                                                        (tmp_38 + (int)l_1942[0][2][8]) - 193)) + (int)l_1942[0][2][8]);
          *g_742 |= (unsigned long)tmp_40;
          {
            long tmp_25;
            tmp_25 = realsmith_3cjHK_slice_1((long)g_1974 + (long)4);
            *(*g_909) = (uint8_t)((int)*(*g_909) | (7UL >= (unsigned long)(
                                                    (int32_t)((((((tmp_25 + (long)*(*l_75)) + (long)*g_742) + (long)*g_575) + (long)g_1974) + (long)p_53) - (long)(-1669154525)) + *(*l_75))));
          }
          if (p_53) goto break_cont_3;
          goto break_cont_3;
        }
      }
      break_cont_3: break_cont_2: g_1136 = (uint8_t)((int)g_1136 + 1);
    }
    tmp_50 = realsmith_1eiWC_slice_1();
    tmp_55 = safe_lshift_func_uint16_t_u_u_slice_1((uint16_t)(p_55 != p_55),
                                                   (unsigned int)6);
    *g_742 = (uint64_t)tmp_55;
    l_1965 = (void *)g_2010 == (void *)l_2013;
    tmp_56 = safe_div_func_int32_t_s_s_slice_1(l_1965,
                                               ((tmp_50 + p_55) - 5) + p_55);
    tmp_57 = safe_lshift_func_int8_t_s_s_slice_1((int8_t)tmp_56,*l_1861);
    g_168 = (uint32_t)tmp_57;
  }
  return;
}

static void func_76_slice_1(int32_t *p_77, uint32_t p_78)
{
  uint16_t const * const l_1881;
  uint16_t tmp_17;
  int8_t tmp_16;
  int16_t tmp_15;
  int tmp_0;
  int32_t *l_1865 = & g_2;
  tmp_0 = realsmith_proxy_NNUAV_slice_1();
  tmp_15 = safe_div_func_int16_t_s_s_slice_1((int16_t)1L,
                                             (int16_t)((uint32_t)((((
                                                                    (
                                                                    tmp_0 + (int)p_78) + *p_77) + (int)*(*g_574)) + (int)*(*g_909)) - 65695) + p_78));
  tmp_16 = safe_mod_func_int8_t_s_s_slice_1((int8_t)((uint16_t const *)0 == l_1881),
                                            (int8_t)tmp_15);
  tmp_17 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)tmp_16,
                                              (uint16_t)0xEF32L);
  *l_1865 = (int32_t)tmp_17;
  return;
}

static void func_82_slice_1(int32_t p_84, int32_t p_85, uint32_t const p_86,
                            uint64_t p_87)
{
  int8_t l_1535;
  uint64_t l_1631;
  int8_t *tmp;
  int8_t **l_1541 = & g_1539[3][0][0];
  uint64_t **l_1582 = & g_742;
  tmp = g_1539[3][0][0];
  *l_1541 = tmp;
  l_1535 = (int8_t)1;
  while ((int)l_1535 != 16) {
    {
      int8_t const l_1550;
      g_68 = 0;
      while (g_68 >= 0) {
        {
          int32_t l_1557;
          uint64_t tmp_90;
          int tmp_89;
          int32_t l_1622 = (int32_t)(-6L);
          tmp_89 = 0;
          tmp_90 = safe_mod_func_uint64_t_u_u_slice_1(*g_742,
                                                      (uint64_t)tmp_89);
          if (tmp_90) {
            *(*l_1541) = (int8_t)((long)*(*l_1541) & -1L);
            {
              int tmp_11;
              uint64_t tmp_10;
              g_168 = (uint32_t)0;
              while (g_168 <= (uint32_t)1) {
                g_131 = (uint16_t)((unsigned long)g_131 ^ 65529UL);
                g_168 += (uint32_t)1;
              }
              tmp_11 = realsmith_UWVAf_slice_1((unsigned int)((long)((unsigned int)p_84) + -2625747241));
              tmp_10 = (uint64_t)(((((tmp_11 + p_84) + ((int)p_87 - -1669220044)) + (int)p_86) - -1669220043) + p_84);
              *(*l_1582) = tmp_10;
              if (tmp_10) {
                uint8_t tmp_12;
                tmp_12 = safe_mul_func_uint8_t_u_u_slice_1((uint8_t)p_87,
                                                           (uint8_t)0UL);
                l_1557 = (int32_t)tmp_12;
                g_222 = (int32_t)((0x714CC084L | (long)((int)l_1550 > l_1557)) & (long)p_85);
              }
            }
            *(*g_909) = (uint8_t)((int)*(*g_909) + 1);
          }
          else 
            *(*l_1541) = (int8_t)((int)*(*l_1541) | l_1622);
        }
        g_68 --;
      }
      g_260 = (uint32_t)24;
      while (g_260 != (uint32_t)45) {
        uint64_t tmp_97;
        {
          int32_t *l_1765 = & g_68;
          p_85 = 0;
          while (p_85 != -3) {
            l_1631 = (uint64_t)0;
            while (l_1631 <= (uint64_t)33) {
              {
                int tmp_107;
                (*(*l_1582)) --;
                *g_44 = l_1765;
                tmp_107 = realsmith_UTlgl_slice_1();
                if ((uint32_t)(((((tmp_107 + (int)p_86) + p_84) + ((int)p_87 - -1669220044)) + *g_45) - -1669220043) + p_86) 
                  break;
              }
              l_1631 ++;
            }
            g_150 = (uint8_t)17;
            goto break_cont_4;
            break_cont_4: p_85 --;
          }
        }
        tmp_97 = safe_add_func_uint64_t_u_u_slice_1((uint64_t)g_260,
                                                    (uint64_t)3);
        g_260 = (uint32_t)tmp_97;
      }
    }
    l_1535 = (int8_t)((int)l_1535 + 1);
  }
  return;
}

static void func_93_slice_1(int32_t p_94)
{
  int tmp_3;
  uint64_t tmp_2;
  uint8_t tmp_258;
  int16_t tmp_256;
  int8_t tmp_245;
  int tmp_241;
  int8_t tmp_251;
  long tmp_246;
  int tmp_250;
  int tmp_255;
  int tmp_257;
  int64_t tmp_240;
  int16_t l_888 = (int16_t)0x9E33L;
  func_98_slice_1();
  g_347 = (int8_t)((long)g_347 & -2L);
  tmp_3 = realsmith_J8pT8_slice_1();
  tmp_2 = (uint64_t)((int)((uint16_t)(((((tmp_3 + (int)g_131) + (int)g_1854) + (int)*g_910) + (int)*g_575) - 131209)) + (int)g_131 > 1);
  *g_742 = tmp_2;
  tmp_241 = realsmith_DLSRM_slice_1((int)l_888 + 25071);
  tmp_245 = safe_sub_func_int8_t_s_s_slice_1((signed char)1,
                                             (int8_t)((int)((int16_t)(
                                                      (tmp_241 + (int)l_888) - -24709)) + (int)l_888));
  tmp_246 = realsmith_p1ATZ_slice_1();
  tmp_250 = 1;
  tmp_251 = safe_mul_func_int8_t_s_s_slice_1((int8_t)tmp_250,
                                             (int8_t)((int32_t)((tmp_246 + (long)p_94) - (long)4832004) + p_94));
  tmp_255 = 0;
  tmp_256 = safe_lshift_func_int16_t_s_s_slice_1((int16_t)((int)tmp_251 < tmp_255),
                                                 (int)tmp_245);
  tmp_257 = realsmith_proxy_guzdj_slice_1();
  tmp_258 = safe_add_func_uint8_t_u_u_slice_1((uint8_t)((int64_t)((tmp_257 + (int)g_197[4][5][1]) - 2134903932) + g_197[4][5][1]),
                                              (uint8_t)tmp_256);
  tmp_240 = (int64_t)tmp_258;
  *(*g_625) = tmp_240;
  {
    uint64_t tmp_132;
    tmp_132 = *g_742;
    *g_742 = tmp_132;
    *g_626 |= 1L;
    goto break_cont_5;
    break_cont_5: ;
    goto break_cont_6;
  }
  break_cont_6: g_224 = (uint32_t)(-21);
  return;
}

static void func_98_slice_1(void)
{
  g_88 = (int16_t)0;
  while ((int)g_88 != 4) g_88 = (int16_t)((int)g_88 + 1);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


