/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_mod_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_div_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left; else tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_div_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_div_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si2 == 0) tmp = si1; else tmp = si1 / si2;
  return tmp;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if ((int)left > 65535 >> right) tmp = (int)left;
  else tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint64_t safe_add_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 + ui2;
  return __retres;
}

static uint64_t safe_mod_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  if (ui2 == (uint64_t)0) tmp = ui1; else tmp = ui1 % ui2;
  return tmp;
}

static int32_t g_2 = (int32_t)0x4E064826L;
static int32_t g_6 = (int32_t)9L;
static uint8_t g_20 = (uint8_t)0x2BL;
static uint64_t g_26 = (uint64_t)0xB659BAAA4F69A750LL;
static int32_t *g_45 = & g_6;
static int32_t **g_44 = & g_45;
static int32_t g_68 = (int32_t)(-1L);
static int16_t g_88 = (int16_t)(-1L);
static uint16_t g_90 = (uint16_t)1UL;
static uint16_t g_131 = (uint16_t)65535UL;
static uint8_t g_150 = (uint8_t)250UL;
static uint32_t g_168 = (uint32_t)0xA92D9FAAL;
static int32_t *g_186 = & g_2;
static int32_t **g_185 = & g_186;
static int64_t g_197[7][8][2] =
  {{{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}},
   {{(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL},
    {(int64_t)0x0D3B926A7F400C75LL, (int64_t)0x0D3B926A7F400C75LL}}};
static int32_t g_222 = (int32_t)0xA699A93FL;
static uint32_t g_224 = (uint32_t)0UL;
static uint32_t g_260 = (uint32_t)0x40F3676AL;
static int16_t g_298 = (int16_t)0x6F54L;
static int8_t g_347 = (int8_t)(-1L);
static uint8_t g_372 = (uint8_t)0x8CL;
static int32_t *g_514[5][1][1] =
  {{{& g_2}}, {{& g_2}}, {{& g_2}}, {{& g_2}}, {{& g_2}}};
static int32_t ** const g_513 = & g_514[1][0][0];
static uint16_t const *g_575 = (uint16_t const *)(& g_131);
static uint16_t const * const *g_574 = (uint16_t const * const *)(& g_575);
static int64_t * const g_626 = & g_197[5][0][1];
static int64_t * const *g_625 = & g_626;
static int16_t g_655 = (int16_t)0xEAD6L;
static uint64_t *g_742 = & g_26;
static int8_t const g_763 = (int8_t)(-1L);
static uint32_t g_802[9][8][3] =
  {{{(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0xCB2E23F6L},
    {(uint32_t)7UL, (uint32_t)0xFFC5D4D8L, (uint32_t)18446744073709551612UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)0x224F8A36L, (uint32_t)0x8C2021E4L},
    {(uint32_t)7UL, (uint32_t)0UL, (uint32_t)7UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0x6BAE6C21L},
    {(uint32_t)7UL, (uint32_t)18446744073709551612UL, (uint32_t)0xCB5DC14CL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)1UL, (uint32_t)0xCB2E23F6L},
    {(uint32_t)7UL, (uint32_t)0xFFC5D4D8L, (uint32_t)18446744073709551612UL}},
   {{(uint32_t)0xCB2E23F6L, (uint32_t)0x224F8A36L, (uint32_t)0x8C2021E4L},
    {(uint32_t)7UL, (uint32_t)0UL, (uint32_t)7UL},
    {(uint32_t)0xCB2E23F6L, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}},
   {{(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L}},
   {{(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}},
   {{(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L}},
   {{(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL}},
   {{(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL},
    {(uint32_t)1UL, (uint32_t)0x6BAE6C21L, (uint32_t)1UL},
    {(uint32_t)0UL, (uint32_t)7UL, (uint32_t)0xD7585F84L},
    {(uint32_t)1UL, (uint32_t)0x8C2021E4L, (uint32_t)0xB2EA789DL},
    {(uint32_t)0UL, (uint32_t)18446744073709551612UL, (uint32_t)0UL},
    {(uint32_t)1UL, (uint32_t)0xCB2E23F6L, (uint32_t)6UL},
    {(uint32_t)0UL, (uint32_t)0xCB5DC14CL, (uint32_t)1UL}}};
static uint8_t *g_910 = & g_372;
static uint8_t **g_909 = & g_910;
static int64_t **g_1019 = (int64_t **)0;
static int64_t ***g_1018 = & g_1019;
static uint8_t g_1136 = (uint8_t)0xB0L;
static int8_t *g_1539[7][2][1] =
  {{{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}},
   {{& g_347}, {& g_347}}};
static uint32_t g_1542 = (uint32_t)4294967295UL;
static int32_t g_1869 = (int32_t)0x820F5903L;
static uint16_t g_1974 = (uint16_t)1UL;
static uint8_t g_2003[1] = {(uint8_t)0x21L};
static uint8_t ***g_2012[5][1] =
  {{& g_909}, {& g_909}, {& g_909}, {& g_909}, {& g_909}};
static uint8_t ****g_2011 = & g_2012[2][0];
static uint8_t ***** const g_2010 = & g_2011;
static int16_t const g_2177 = (int16_t)0x14F2L;
static uint16_t *g_2191 = & g_90;
static void func_1_slice_1(void);

static void func_32_slice_1(int64_t const p_35);

static void func_52_slice_1(int8_t const p_53, uint64_t p_54, int32_t p_55);

static void func_76_slice_1(uint32_t p_78);

static void func_82_slice_1(int32_t p_84, int32_t p_85, uint64_t p_87);

static void func_93_slice_1(void);

static void func_98_slice_1(void);

static void func_1_slice_1(void)
{
  int8_t tmp_4;
  int16_t tmp_3;
  uint64_t tmp_2;
  int8_t l_14[4] =
    {(int8_t)0xC4L, (int8_t)0xC4L, (int8_t)0xC4L, (int8_t)0xC4L};
  int32_t l_62 = (int32_t)0x9C81B934L;
  g_2 = -23;
  g_6 = 0;
  while (g_6 <= 3) {
    g_2 ^= (int)l_14[g_6];
    g_6 ++;
  }
  goto break_cont_1;
  break_cont_1:
  tmp_2 = safe_mod_func_uint64_t_u_u_slice_1((uint64_t)g_2,(uint64_t)g_6);
  tmp_3 = safe_div_func_int16_t_s_s_slice_1((int16_t)tmp_2,(int16_t)(-1L));
  tmp_4 = safe_div_func_int8_t_s_s_slice_1((int8_t)tmp_3,(int8_t)g_2);
  func_52_slice_1(tmp_4,(uint64_t)l_62,g_6);
  func_32_slice_1((int64_t)g_2177);
  return;
}

static void func_32_slice_1(int64_t const p_35)
{
  int16_t tmp;
  int16_t tmp_0;
  int64_t l_2532 = (int64_t)0x0D4D81558201ED89LL;
  int16_t *l_2546 = & g_655;
  int16_t *l_2547 = & g_298;
  tmp = (int16_t)p_35;
  *l_2546 = tmp;
  tmp_0 = (int16_t)l_2532;
  *l_2547 = tmp_0;
  return;
}

static void func_52_slice_1(int8_t const p_53, uint64_t p_54, int32_t p_55)
{
  uint8_t const ** const *** const l_2013;
  {
    int32_t l_1965;
    int8_t tmp_33;
    int32_t tmp_32;
    uint16_t tmp_31;
    int32_t * const *l_75 = (int32_t * const *)(& g_45);
    uint16_t *l_89 = & g_90;
    uint32_t l_1517 = (uint32_t)0x1D5DDCBFL;
    int32_t *l_1861 = & g_6;
    func_93_slice_1();
    *l_89 = (uint16_t)((int)*l_89 - 1);
    func_82_slice_1((int32_t)p_54,(int32_t)p_53,p_54);
    func_76_slice_1(g_802[4][4][0]);
    g_1136 = (uint8_t)0;
    while ((int)g_1136 <= 7) {
      *(*g_909) = (uint8_t)((int)*(*g_909) | (7UL >= (unsigned long)*(*l_75)));
      goto break_cont_2;
      break_cont_2: g_1136 = (uint8_t)((int)g_1136 + 1);
    }
    tmp_31 = safe_lshift_func_uint16_t_u_u_slice_1((uint16_t)(p_55 != p_55),
                                                   (unsigned int)6);
    *g_742 = (uint64_t)tmp_31;
    l_1965 = (void *)g_2010 == (void *)l_2013;
    tmp_32 = safe_div_func_int32_t_s_s_slice_1(l_1965,p_55);
    tmp_33 = safe_lshift_func_int8_t_s_s_slice_1((int8_t)tmp_32,*l_1861);
    g_168 = (uint32_t)tmp_33;
  }
  return;
}

static void func_76_slice_1(uint32_t p_78)
{
  uint16_t const * const l_1881 = &g_90;
  uint16_t tmp_11;
  int8_t tmp_10;
  int16_t tmp_9;
  int32_t *l_1865 = & g_2;
  tmp_9 = safe_div_func_int16_t_s_s_slice_1((int16_t)1L,(int16_t)p_78);
  tmp_10 = safe_mod_func_int8_t_s_s_slice_1((int8_t)((uint16_t const *)0 == l_1881),
                                            (int8_t)tmp_9);
  tmp_11 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)tmp_10,
                                              (uint16_t)0xEF32L);
  *l_1865 = (int32_t)tmp_11;
  return;
}

static void func_82_slice_1(int32_t p_84, int32_t p_85, uint64_t p_87)
{
  int8_t l_1535;
  int8_t *tmp;
  int8_t **l_1541 = & g_1539[3][0][0];
  uint64_t **l_1582 = & g_742;
  tmp = g_1539[3][0][0];
  *l_1541 = tmp;
  l_1535 = (int8_t)1;
  while ((int)l_1535 != 16) {
    {
      int8_t const l_1550 = 0xDEL;
      g_68 = 0;
      while (g_68 >= 0) {
        {
          int32_t l_1557;
          uint64_t tmp_69;
          int tmp_68;
          int32_t l_1622 = (int32_t)(-6L);
          tmp_68 = 0;
          tmp_69 = safe_mod_func_uint64_t_u_u_slice_1(*g_742,
                                                      (uint64_t)tmp_68);
          if (tmp_69) {
            *(*l_1541) = (int8_t)((long)*(*l_1541) & -1L);
            {
              uint64_t tmp_4;
              g_168 = (uint32_t)0;
              while (g_168 <= (uint32_t)1) {
                g_131 = (uint16_t)((unsigned long)g_131 ^ 65529UL);
                g_168 += (uint32_t)1;
              }
              tmp_4 = (uint64_t)p_84;
              *(*l_1582) = tmp_4;
              {
                uint8_t tmp_5;
                tmp_5 = safe_mul_func_uint8_t_u_u_slice_1((uint8_t)p_87,
                                                          (uint8_t)0UL);
                l_1557 = (int32_t)tmp_5;
                g_222 = (int32_t)((0x714CC084L | (long)((int)l_1550 > l_1557)) & (long)p_85);
              }
            }
            *(*g_909) = (uint8_t)((int)*(*g_909) + 1);
          }
          else 
            *(*l_1541) = (int8_t)((int)*(*l_1541) | l_1622);
        }
        g_68 --;
      }
      g_260 = (uint32_t)24;
      while (g_260 != (uint32_t)45) {
        uint64_t tmp_72;
        {
          int32_t *l_1765 = & g_68;
          p_85 = 0;
          while (p_85 != -3) {
            (*(*l_1582)) --;
            *g_44 = l_1765;
            goto break_cont_3;
            break_cont_3: ;
            g_150 = (uint8_t)17;
            goto break_cont_4;
            break_cont_4: p_85 --;
          }
        }
        tmp_72 = safe_add_func_uint64_t_u_u_slice_1((uint64_t)g_260,
                                                    (uint64_t)3);
        g_260 = (uint32_t)tmp_72;
      }
    }
    l_1535 = (int8_t)((int)l_1535 + 1);
  }
  return;
}

static void func_93_slice_1(void)
{
  uint64_t tmp_1;
  func_98_slice_1();
  g_347 = (int8_t)((long)g_347 & -2L);
  tmp_1 = (uint64_t)((int)g_131 > 1);
  *g_742 = tmp_1;
  {
    uint64_t tmp_126;
    tmp_126 = *g_742;
    *g_742 = tmp_126;
    goto break_cont_5;
    break_cont_5: ;
    goto break_cont_6;
  }
  break_cont_6: g_224 = (uint32_t)(-21);
  return;
}

static void func_98_slice_1(void)
{
  g_88 = (int16_t)0;
  while ((int)g_88 != 4) g_88 = (int16_t)((int)g_88 + 1);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


