/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g = 0U;
static uint32_t inc(uint32_t x);

static uint32_t inc_slice_1(uint32_t x)
{
  g = x + 1U;
  return g;
}

static uint32_t (*pick_slice_1(void))(uint32_t )
{
  uint32_t (*__retres)(uint32_t );
  __retres = & inc;
  return __retres;
}

int main(void)
{
  int __retres;
  uint32_t tmp_0;
  uint32_t (*fp)(uint32_t ) = pick_slice_1();
  tmp_0 = inc_slice_1(10U);
  uint32_t v = tmp_0;
  __retres = (int)(v & 0xFFU);
  return __retres;
}


