/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g = 0U;
static uint32_t f1(uint32_t x);

static uint32_t f1_slice_1(uint32_t x)
{
  g = x + 10U;
  return g;
}

int main(void)
{
  int __retres;
  uint32_t tmp;
  uint32_t (*p)(uint32_t ) = & f1;
  tmp = f1_slice_1(1U);
  uint32_t v = tmp;
  __retres = (int)(v & 0xFFU);
  return __retres;
}


