/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_state = 0U;
static uint32_t add_1(uint32_t x);

static uint32_t add_2(uint32_t x);

static uint32_t add_2_slice_1(uint32_t x)
{
  g_state = x + 2U;
  return g_state;
}

static uint32_t (*g_fp)(uint32_t ) = & add_1;
int main(void)
{
  int __retres;
  uint32_t tmp;
  g_fp = & add_2;
  tmp = add_2_slice_1(40U);
  uint32_t v = tmp;
  __retres = (int)(v & 0xFFU);
  return __retres;
}


