/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_result = 0U;
static void fa(uint32_t x);

static void fb(uint32_t x);

static void fb_slice_1(uint32_t x)
{
  g_result = x ^ 0x13579BDFU;
  return;
}

static void (*fp)(uint32_t ) = & fa;
int main(void)
{
  int __retres;
  fp = & fb;
  fb_slice_1(1U);
  uint32_t x = g_result;
  uint8_t digest = (uint8_t)(((x ^ (x >> 8)) ^ (x >> 16)) ^ (x >> 24));
  __retres = (int)digest;
  return __retres;
}


