/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int realsmith_SRzzS_slice_1(void) __attribute__((__used__));
static int realsmith_SRzzS_slice_1(void)
{
  int __retres;
  unsigned int i = (unsigned int)0;
  __retres = (int)i;
  return __retres;
}

int realsmith_proxy_Nx4pD_slice_1(void)
{
  int proxy_ret_8XRGj = realsmith_SRzzS_slice_1();
  return proxy_ret_8XRGj;
}

__inline static unsigned int realsmith_tOG6J_slice_1(void) __attribute__((
__used__));
__inline static unsigned int realsmith_tOG6J_slice_1(void)
{
  unsigned int __retres;
  /* Expression loss: original call was realsmith_tOG6J((long)(g_78)+(5))
   * where g_78 = -1, so n = (unsigned int)(-1 + 5) = 4
   * The parameter expression was lost during slicing */
  unsigned int const n = (unsigned int)4UL;
  __retres = (n >> 24) & (unsigned int)0xf;
  return __retres;
}

static int realsmith_T45Bg_slice_1(void) __attribute__((__used__));
static int realsmith_T45Bg_slice_1(void)
{
  int dup;
  dup = 1;
  return dup;
}

int realsmith_proxy_95HBX_slice_1(void)
{
  int proxy_ret_gkyUP = realsmith_T45Bg_slice_1();
  return proxy_ret_gkyUP;
}

int ENODATA_realsmith_Q2bdr = 7;
static int realsmith_Q2bdr_slice_1(void) __attribute__((__used__));
static int realsmith_Q2bdr_slice_1(void)
{
  int __retres;
  int cc;
  cc = 1;
  switch (cc) {
    case 0: ;
    case 1: ;
    __retres = - ENODATA_realsmith_Q2bdr;
    goto return_label;
    case 2: ;
    default: ;
  }
  return_label: return __retres;
}

int realsmith_proxy_nwJ6Q_slice_1(void)
{
  int proxy_ret_c9bou = realsmith_Q2bdr_slice_1();
  return proxy_ret_c9bou;
}

__inline static unsigned int realsmith_rkykD_slice_1(unsigned int size) __attribute__((
__used__));
__inline static unsigned int realsmith_rkykD_slice_1(unsigned int size)
{
  unsigned int __retres;
  __retres = (size * (unsigned int)85 >> 20) + (unsigned int)1;
  return __retres;
}

int realsmith_pXqid_slice_1(void)
{
  int error;
  error = 1;
  return error;
}

int realsmith_ygGi1_slice_1(void)
{
  int __retres;
  __retres = 0;
  goto return_label;
  return_label: return __retres;
}

int realsmith_proxy_ThLET_slice_1(long p_1_zfBYu)
{
  long proxy_6Drdt[15] =
    {p_1_zfBYu,
     p_1_zfBYu,
     p_1_zfBYu,
     p_1_zfBYu,
     (long)10,
     (long)78,
     p_1_zfBYu,
     (long)27,
     (long)11,
     (long)61,
     (long)4,
     (long)66,
     (long)68,
     (long)19,
     p_1_zfBYu};
  int proxy_ret_w5sAt = realsmith_ygGi1_slice_1();
  return proxy_ret_w5sAt;
}

int realsmith_kB1UB_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_65ZsK_slice_1(void)
{
  int proxy_ret_uNh5c = realsmith_kB1UB_slice_1();
  return proxy_ret_uNh5c;
}

__inline static int realsmith_ai0ZQ_slice_1(void) __attribute__((__used__));
__inline static int realsmith_ai0ZQ_slice_1(void)
{
  int tmp;
  tmp = 1;
  return tmp;
}

static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int8_t safe_mod_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_mod_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si2 == 0) tmp = si1; else tmp = si1 % si2;
  return tmp;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left,
                                                      int right)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint64_t safe_div_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  tmp = ui1 / ui2;
  return tmp;
}

static uint8_t g_4 = (uint8_t)0x87L;
static int32_t g_9[2][5][2] =
  {{{(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L},
    {(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L}},
   {{(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L},
    {(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L}}};
static uint16_t g_60 = (uint16_t)1UL;
static int32_t g_77 = (int32_t)0x48991CD3L;
static int32_t g_78 = (int32_t)(-1L);
static int8_t g_90 = (int8_t)0x97L;
static int16_t g_104 = (int16_t)(-1L);
static uint64_t g_118 = 18446744073709551613UL;
static uint8_t g_132 = (uint8_t)4UL;
static int64_t g_134 = -2L;
static int8_t g_151 = (int8_t)0x66L;
static int64_t g_170[1][4] =
  {{(int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL}};
static int8_t g_171 = (int8_t)0x1DL;
static int32_t **g_172 = (int32_t **)0;
static uint16_t g_199 = (uint16_t)7UL;
static int8_t *g_252 = & g_171;
static uint8_t g_299[4] =
  {(uint8_t)0x25L, (uint8_t)0x25L, (uint8_t)0x25L, (uint8_t)0x25L};
static int8_t g_309[3] = {(int8_t)0L, (int8_t)0L, (int8_t)0L};
static int8_t g_311 = (int8_t)0x7CL;
static uint8_t *g_703[1][2] = {{& g_4, & g_4}};
static uint8_t **g_702 = & g_703[0][1];
static int32_t *g_877 = & g_78;
static uint8_t const g_2311 = (uint8_t)0xF8L;
static void func_1_slice_1(void);

static void func_10_slice_1(void);

static void func_14_slice_1(void);

static void func_20_slice_1(void);

static void func_31_slice_1(void);

static void func_37_slice_1(uint8_t p_38, uint8_t *p_39);

static void func_44_slice_1(uint16_t p_45, uint8_t p_46, int32_t *p_47);

static uint16_t func_49_slice_1(void);

static void func_1_slice_1(void)
{
  uint8_t tmp;
  int8_t tmp_4;
  int32_t *l_8 = & g_9[0][4][0];
  tmp = g_4;
  *l_8 = (long)tmp != 0x25L;
  tmp_4 = safe_mod_func_int8_t_s_s_slice_1((int8_t)*l_8,(int8_t)*l_8);
  func_37_slice_1((uint8_t)tmp_4,& g_4);
  func_31_slice_1();
  func_20_slice_1();
  func_14_slice_1();
  func_10_slice_1();
  return;
}

static void func_10_slice_1(void)
{
  g_132 = (uint8_t)24;
  return;
}

static void func_14_slice_1(void)
{
  int16_t tmp_9;
  unsigned int tmp;
  int tmp_8;
  int32_t l_2327 = (int32_t)0L;
  tmp = realsmith_rkykD_slice_1((unsigned int)l_2327 + (unsigned int)28);
  tmp_8 = 1;
  tmp_9 = safe_mod_func_int16_t_s_s_slice_1((int16_t)tmp_8,
                                            (int16_t)((int32_t)((tmp + (unsigned int)l_2327) - (unsigned int)1) + l_2327));
  *g_877 &= (int)tmp_9;
  return;
}

static void func_20_slice_1(void)
{
  uint8_t tmp_2;
  int tmp_16;
  int tmp_15;
  int32_t tmp_8;
  uint8_t *l_2034 = & g_4;
  int32_t l_2035 = (int32_t)(-4L);
  tmp_2 = (uint8_t)246UL;
  *l_2034 = tmp_2;
  tmp_15 = 1;
  g_104 = (int16_t)((int)g_104 | tmp_15);
  tmp_16 = 1;
  tmp_8 = tmp_16 < l_2035;
  *g_877 = tmp_8;
  g_199 = (uint16_t)0;
  return;
}

static void func_31_slice_1(void)
{
  int16_t tmp_29;
  uint16_t tmp_28;
  int tmp_27;
  int64_t tmp_0;
  int64_t *l_554 = & g_134;
  tmp_27 = 1;
  tmp_28 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)tmp_27,12);
  tmp_29 = safe_mul_func_int16_t_s_s_slice_1((int16_t)tmp_28,
                                             (int16_t)0x2F9CL);
  tmp_0 = (int64_t)tmp_29;
  *l_554 = tmp_0;
  return;
}

static void func_37_slice_1(uint8_t p_38, uint8_t *p_39)
{
  g_4 = (uint8_t)0;
  {
    uint16_t tmp_11;
    int32_t tmp;
    int8_t l_70 = (int8_t)1L;
    int32_t *l_76 = & g_77;
    tmp = (int)p_38 > ((int)l_70 < g_9[0][2][0]);
    *l_76 = tmp;
    g_78 &= tmp;
    tmp_11 = func_49_slice_1();
    func_44_slice_1(tmp_11,*p_39,& g_9[0][4][0]);
    {
      uint16_t l_258[3][4] =
        {{(uint16_t)0x96D9L,
          (uint16_t)0x6E73L,
          (uint16_t)0x6E73L,
          (uint16_t)0x96D9L},
         {(uint16_t)0x6E73L,
          (uint16_t)0x96D9L,
          (uint16_t)0x6E73L,
          (uint16_t)0x6E73L},
         {(uint16_t)0x96D9L,
          (uint16_t)0x96D9L,
          (uint16_t)65526UL,
          (uint16_t)0x96D9L}};
      {
        int tmp_32;
        int32_t tmp_14;
        tmp_32 = realsmith_ai0ZQ_slice_1();
        tmp_14 = (int)((uint16_t)((tmp_32 + (int)l_258[2][3]) - 38618)) + (int)l_258[2][3];
        *l_76 = tmp_14;
      }
      goto return_label;
    }
  }
  return_label: return;
}

static void func_44_slice_1(uint16_t p_45, uint8_t p_46, int32_t *p_47)
{
  int32_t *l_84 = & g_78;
  int32_t *l_85 = & g_78;
  int32_t *l_88 = & g_77;
  int16_t *l_123 = & g_104;
  g_60 = (uint16_t)0;
  while ((int)g_60 != 10) {
    {
      int tmp_10;
      int tmp_5;
      int16_t tmp_4;
      int16_t *l_103 = & g_104;
      tmp_5 = realsmith_proxy_nwJ6Q_slice_1();
      tmp_4 = (int16_t)(0xE5F641D3L ^ (long)((int)((uint8_t)((tmp_5 + (int)p_46) - -7)) + (int)p_46));
      *l_103 = tmp_4;
      tmp_10 = 1;
      g_77 = tmp_10;
    }
    g_60 = (uint16_t)((int)g_60 + 1);
  }
  g_90 = (int8_t)(-24);
  while ((int)g_90 <= 9) {
    {
      int8_t tmp_64;
      int tmp_60;
      uint8_t tmp_59;
      uint64_t *l_117 = & g_118;
      int32_t l_130 = (int32_t)0L;
      uint8_t *l_131 = & g_132;
      *l_117 = (uint64_t)((unsigned long long)*l_117 & (unsigned long long)0x23D7FF4CBEB01B51LL);
      tmp_60 = realsmith_pXqid_slice_1();
      tmp_64 = safe_sub_func_int8_t_s_s_slice_1((int8_t)(-1L),
                                                (int8_t)((int)((uint8_t)(
                                                         (((tmp_60 + (int)g_4) + g_9[1][1][0]) + (int)g_311) - 126)) + (int)g_4));
      tmp_59 = (uint8_t)tmp_64;
      *l_131 = tmp_59;
      {
        int tmp_53;
        int tmp_45;
        int8_t tmp_44;
        int32_t tmp_41;
        int8_t *l_150 = & g_151;
        tmp_45 = 1;
        tmp_44 = (int8_t)((int)p_45 ^ ((unsigned long)tmp_45 < 4294967291UL));
        *l_150 = tmp_44;
        {
          int tmp_52;
          tmp_52 = realsmith_proxy_ThLET_slice_1((long)g_77 + (long)27);
          if ((int)((uint8_t)((((((tmp_52 + (int)p_46) + g_9[0][4][0]) + (int)g_4) + g_77) + (int)p_45) - 2)) + (int)p_46) 
            tmp_53 = 1;
          else tmp_53 = 0;
        }
        tmp_41 = tmp_53;
        *l_84 = tmp_41;
        {
          int16_t tmp_23;
          int16_t tmp_21;
          uint64_t tmp_14;
          uint8_t tmp_19;
          int32_t tmp_18;
          int tmp_15;
          int64_t tmp_17;
          int tmp_16;
          unsigned int tmp_20;
          int tmp_22;
          int64_t tmp_13;
          g_134 = (int64_t)0xE406C9851B6DC083LL;
          tmp_14 = safe_div_func_uint64_t_u_u_slice_1((uint64_t)g_90,
                                                      (uint64_t)g_134);
          tmp_15 = realsmith_proxy_Nx4pD_slice_1();
          tmp_16 = realsmith_proxy_95HBX_slice_1();
          tmp_17 = safe_sub_func_int64_t_s_s_slice_1(-1L,
                                                     (int64_t)(((tmp_16 + l_130) - 1) + l_130));
          tmp_18 = safe_mod_func_int32_t_s_s_slice_1((int32_t)tmp_17,
                                                     (int)((uint8_t)(
                                                     (tmp_15 + (int)p_46) - 0)) + (int)p_46);
          tmp_19 = safe_add_func_uint8_t_u_u_slice_1((uint8_t)0xABL,
                                                     (uint8_t)tmp_18);
          tmp_20 = realsmith_tOG6J_slice_1();
          tmp_21 = safe_mul_func_int16_t_s_s_slice_1((int16_t)((int)((uint8_t)(
                                                               ((((tmp_20 + (unsigned int)p_46) + (unsigned int)g_78) + (unsigned int)*p_47) + (unsigned int)g_9[0][4][0]) - (unsigned int)2)) + (int)p_46),
                                                     (int16_t)(0x81E3L > (long)(
                                                               (tmp_14 > (uint64_t)tmp_19) < (int)g_90)));
          *l_85 |= (int)tmp_21;
          tmp_22 = realsmith_proxy_65ZsK_slice_1();
          tmp_23 = safe_mul_func_int16_t_s_s_slice_1((int16_t)((int)((uint8_t)(
                                                               (((((tmp_22 + (int)g_132) + (int)g_4) + g_78) + g_9[0][4][0]) + g_77) - 257)) + (int)g_132),
                                                     (int16_t)(*l_85 == g_9[0][2][0]));
          tmp_13 = (int64_t)tmp_23;
          g_171 = (int8_t)tmp_13;
          *l_123 = (int16_t)((int)((int16_t)g_171));
          *l_88 = & p_47 != g_172;
          *l_150 = (int8_t)((int)*l_150 & ((int32_t **)0 != & p_47));
        }
      }
    }
    g_90 = (int8_t)((int)g_90 + 1);
  }
  return;
}

static uint16_t func_49_slice_1(void)
{
  uint16_t __retres;
  int32_t const *l_79 = (int32_t const *)(& g_78);
  l_79 = l_79;
  __retres = (uint16_t)*l_79;
  return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_104: %d\n", (int)g_104);
  __retres = 0;
  return __retres;
}


