/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
 __attribute__((__FC_BUILTIN__)) void *__fc_vla_alloc(unsigned long size);

static uint32_t foo_slice_1(uint32_t n)
{
  unsigned long __lengthof_vla;
  __lengthof_vla = (unsigned long)n;
  uint32_t *vla = __fc_vla_alloc(sizeof(uint32_t) * __lengthof_vla);
  {
    uint32_t i = 0U;
    while (i < n) {
      *(vla + i) = (i + 1U) * 7U;
      i ++;
    }
  }
  uint32_t s = 0U;
  {
    uint32_t i_0 = 0U;
    while (i_0 < n) {
      s ^= *(vla + i_0);
      i_0 ++;
    }
  }
  return s;
}

int main(void)
{
  int __retres;
  uint32_t out = foo_slice_1(9U);
  __retres = (int)(out & 0xFFU);
  return __retres;
}


