/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_out = 0U;
static void tweak_slice_1(uint32_t n, uint32_t a[n])
{
  uint32_t *p = a + 0;
  uint32_t *q = a + (n - 1U);
  *p = (*p + 1U) ^ 0x5AU;
  *q = (*q + 2U) ^ 0xA5U;
  return;
}

 __attribute__((__FC_BUILTIN__)) void *__fc_vla_alloc(unsigned long size);

int main(void)
{
  int __retres;
  unsigned long __lengthof_a;
  uint32_t n = 5U;
  __lengthof_a = (unsigned long)n;
  uint32_t *a = __fc_vla_alloc(sizeof(uint32_t) * __lengthof_a);
  {
    uint32_t i = 0U;
    while (i < n) {
      *(a + i) = i * 10U;
      i ++;
    }
  }
  tweak_slice_1(n,a);
  g_out = *(a + 0) + *(a + (n - 1U));
  __retres = (int)(g_out & 0xFFU);
  return __retres;
}


