/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static uint32_t g_out = 0U;
static uint32_t mix_slice_1(uint32_t x)
{
  x ^= x >> 16;
  x *= 0x7FEB352DU;
  x ^= x >> 15;
  x *= 0x846CA68BU;
  x ^= x >> 16;
  return x;
}

 __attribute__((__FC_BUILTIN__)) void *__fc_vla_alloc(unsigned long size);

int main(void)
{
  int __retres;
  unsigned long __lengthof_vla;
  uint32_t n = 7U;
  __lengthof_vla = (unsigned long)n;
  uint32_t *vla = __fc_vla_alloc(sizeof(uint32_t) * __lengthof_vla);
  {
    uint32_t i = 0U;
    while (i < n) {
      *(vla + i) = mix_slice_1(i + 1U);
      i ++;
    }
  }
  g_out = *(vla + 3) ^ *(vla + (n - 1U));
  __retres = (int)(g_out & 0xFFU);
  return __retres;
}


