/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int FALSE_realsmith_OLlJA = -6;
int realsmith_OLlJA_slice_1(void)
{
  int __retres;
  __retres = FALSE_realsmith_OLlJA;
  return __retres;
}

long HHA_CNT0_LOWER_realsmith_EUAS7 = (long)(-10);
static long realsmith_EUAS7_slice_1(int cntr_idx) __attribute__((__used__));
static long realsmith_EUAS7_slice_1(int cntr_idx)
{
  long __retres;
  __retres = HHA_CNT0_LOWER_realsmith_EUAS7 + (long)(cntr_idx * 8);
  return __retres;
}

unsigned int realsmith_xqMVb_slice_1(void)
{
  unsigned int const n;
  return n;
}

unsigned int realsmith_proxy_mIMvr_slice_1(char p_0_K6ucy)
{
  unsigned int proxy_ret_sC642 = realsmith_xqMVb_slice_1();
  return proxy_ret_sC642;
}

int realsmith_rqNdj_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int realsmith_proxy_M9dfD_slice_1(void)
{
  int proxy_ret_W3DcO = realsmith_rqNdj_slice_1();
  return proxy_ret_W3DcO;
}

__inline static int realsmith_PwjUx_slice_1(int const *data,
                                            unsigned long index_0) __attribute__((
__used__));
__inline static int realsmith_PwjUx_slice_1(int const *data,
                                            unsigned long index_0)
{
  int __retres;
  __retres = ! (! (*(data + index_0 / (unsigned long)8) & (1 << ((unsigned long)7 - 
                                                                 index_0 % (unsigned long)8))));
  return __retres;
}

int realsmith_proxy_uzIp8_slice_1(int p_0_C1aQ0, unsigned long p_1_kDXsd)
{
  int proxy_RGslo[14] =
    {p_0_C1aQ0,
     p_0_C1aQ0,
     p_0_C1aQ0,
     p_0_C1aQ0,
     55,
     98,
     8,
     40,
     18,
     24,
     p_0_C1aQ0,
     87,
     p_0_C1aQ0,
     31};
  int proxy_ret_NI0MU =
    realsmith_PwjUx_slice_1((int const *)(proxy_RGslo),p_1_kDXsd);
  return proxy_ret_NI0MU;
}

__inline static int realsmith_DlTrX_slice_1(void) __attribute__((__used__));
__inline static int realsmith_DlTrX_slice_1(void)
{
  int tmp;
  tmp = 0;
  return tmp;
}

int TRUE_realsmith_Qy9wa = 13;
static int realsmith_Qy9wa_slice_1(void) __attribute__((__used__));
static int realsmith_Qy9wa_slice_1(void)
{
  int __retres;
  __retres = TRUE_realsmith_Qy9wa;
  return __retres;
}

static int realsmith_NpCyp_slice_1(void) __attribute__((__used__));
static int realsmith_NpCyp_slice_1(void)
{
  int __retres;
  __retres = -1;
  return __retres;
}

int BUS_PROBE_DEFAULT_realsmith_d8YzX = 8;
static int realsmith_d8YzX_slice_1(void) __attribute__((__used__));
static int realsmith_d8YzX_slice_1(void)
{
  int __retres;
  __retres = BUS_PROBE_DEFAULT_realsmith_d8YzX;
  return __retres;
}

unsigned char realsmith_oNKmy_slice_1(void)
{
  unsigned char __retres;
  __retres = (unsigned char)1;
  return __retres;
}

int TEST_ERR_MAJOR_BAD_realsmith_FtDPr = 12;
int realsmith_FtDPr_slice_1(void)
{
  int __retres;
  __retres = TEST_ERR_MAJOR_BAD_realsmith_FtDPr;
  return __retres;
}

int realsmith_proxy_ROOFK_slice_1(void)
{
  int proxy_ret_lB5Up = realsmith_FtDPr_slice_1();
  return proxy_ret_lB5Up;
}

int realsmith_Kr7kP_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

static char *realsmith_3XdHv_slice_1(void) __attribute__((__used__));
static char *realsmith_3XdHv_slice_1(void)
{
  char *__retres;
  __retres = (char *)"?";
  return __retres;
}

char realsmith_proxy_5VZLX_slice_1(int p_0_IjPof)
{
  char __retres;
  char *proxy_ret_anBYc = realsmith_3XdHv_slice_1();
  __retres = *proxy_ret_anBYc;
  return __retres;
}

static int *realsmith_ZsbDZ_slice_1(int *output) __attribute__((__used__));
static int *realsmith_ZsbDZ_slice_1(int *output)
{
  output += 2;
  output += 2;
  output += 2;
  return output;
}

int realsmith_proxy_Uxiok_slice_1(int p_3_mu6ti)
{
  int __retres;
  int proxy_KDJFR[13] =
    {70,
     39,
     9,
     p_3_mu6ti,
     p_3_mu6ti,
     p_3_mu6ti,
     p_3_mu6ti,
     48,
     p_3_mu6ti,
     p_3_mu6ti,
     p_3_mu6ti,
     91,
     p_3_mu6ti};
  int *proxy_ret_Hvje9 = realsmith_ZsbDZ_slice_1(proxy_KDJFR);
  __retres = *proxy_ret_Hvje9;
  return __retres;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_div_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1)
{
  int32_t tmp;
  tmp = si1;
  return tmp;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int64_t const g_13 = -1L;
static uint32_t g_37 = (uint32_t)0x6BB2F144L;
static uint32_t *g_36[2][10][7] =
  {{{& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37,
     & g_37,
     (uint32_t *)0,
     & g_37,
     (uint32_t *)0,
     & g_37,
     (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37}},
   {{& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37}}};
static int32_t g_69[6][8][5] =
  {{{(int32_t)0x04811E35L,
     (int32_t)0x15BB970EL,
     (int32_t)0x691D145CL,
     (int32_t)0x04811E35L,
     (int32_t)(-1L)},
    {(int32_t)0x04811E35L,
     (int32_t)0L,
     (int32_t)(-6L),
     (int32_t)0x3AEBC018L,
     (int32_t)(-8L)},
    {(int32_t)0x07C152A3L,
     (int32_t)0x233FFCD5L,
     (int32_t)0xF089E30CL,
     (int32_t)(-1L),
     (int32_t)0L},
    {(int32_t)0x233FFCD5L,
     (int32_t)1L,
     (int32_t)0x86219E20L,
     (int32_t)0x99B58ECEL,
     (int32_t)(-1L)},
    {(int32_t)0x48F7C4FBL,
     (int32_t)0x5DC1C47FL,
     (int32_t)0L,
     (int32_t)0x5DC1C47FL,
     (int32_t)0x48F7C4FBL},
    {(int32_t)0x86219E20L,
     (int32_t)0x04811E35L,
     (int32_t)1L,
     (int32_t)(-5L),
     (int32_t)0L},
    {(int32_t)0x39AA88D1L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x48F7C4FBL,
     (int32_t)(-1L)},
    {(int32_t)0x5DC1C47FL,
     (int32_t)0L,
     (int32_t)0x14A140C5L,
     (int32_t)0x04811E35L,
     (int32_t)0L}},
   {{(int32_t)0x6D0B4E55L,
     (int32_t)0x48F7C4FBL,
     (int32_t)(-7L),
     (int32_t)0xF089E30CL,
     (int32_t)0x48F7C4FBL},
    {(int32_t)0L,
     (int32_t)0x15BB970EL,
     (int32_t)0xF089E30CL,
     (int32_t)0x9F7A6BAEL,
     (int32_t)(-1L)},
    {(int32_t)0xCFEAA3CEL,
     (int32_t)0L,
     (int32_t)0x14A140C5L,
     (int32_t)0x3AEBC018L,
     (int32_t)0L},
    {(int32_t)0xFF541EDFL,
     (int32_t)0x5DC1C47FL,
     (int32_t)(-1L),
     (int32_t)0x763CD51DL,
     (int32_t)(-8L)},
    {(int32_t)0x233FFCD5L,
     (int32_t)1L,
     (int32_t)0x07C152A3L,
     (int32_t)(-8L),
     (int32_t)(-1L)},
    {(int32_t)0x39AA88D1L,
     (int32_t)0L,
     (int32_t)0L,
     (int32_t)(-8L),
     (int32_t)0x1FF3C8D2L},
    {(int32_t)0x6D0B4E55L,
     (int32_t)0xCFEAA3CEL,
     (int32_t)0x15BB970EL,
     (int32_t)0x763CD51DL,
     (int32_t)0L},
    {(int32_t)5L,
     (int32_t)0x9B762B02L,
     (int32_t)0xA7F359A1L,
     (int32_t)0x3AEBC018L,
     (int32_t)(-5L)}},
   {{(int32_t)0L,
     (int32_t)0L,
     (int32_t)(-6L),
     (int32_t)0x9F7A6BAEL,
     (int32_t)0x9F7A6BAEL},
    {(int32_t)0x86219E20L,
     (int32_t)0x39AA88D1L,
     (int32_t)0x86219E20L,
     (int32_t)0xF089E30CL,
     (int32_t)(-3L)},
    {(int32_t)0L,
     (int32_t)1L,
     (int32_t)(-1L),
     (int32_t)0x04811E35L,
     (int32_t)(-5L)},
    {(int32_t)0xCFEAA3CEL,
     (int32_t)0x04811E35L,
     (int32_t)0x501D2D5FL,
     (int32_t)0xA7F359A1L,
     (int32_t)(-1L)},
    {(int32_t)0xABEFA6B6L,
     (int32_t)(-1L),
     (int32_t)(-9L),
     (int32_t)9L,
     (int32_t)0x763CD51DL},
    {(int32_t)0x691D145CL,
     (int32_t)0x48EDA297L,
     (int32_t)0xE61979B9L,
     (int32_t)0x691D145CL,
     (int32_t)(-2L)},
    {(int32_t)0x15BB970EL,
     (int32_t)0xF089E30CL,
     (int32_t)0x9F7A6BAEL,
     (int32_t)(-1L),
     (int32_t)0xA7F359A1L},
    {(int32_t)0xABEFA6B6L,
     (int32_t)0xFF541EDFL,
     (int32_t)0L,
     (int32_t)(-9L),
     (int32_t)0x07C152A3L}},
   {{(int32_t)0x9B762B02L,
     (int32_t)1L,
     (int32_t)0x48EDA297L,
     (int32_t)1L,
     (int32_t)(-9L)},
    {(int32_t)0xF089E30CL,
     (int32_t)0x15BB970EL,
     (int32_t)0L,
     (int32_t)0x86219E20L,
     (int32_t)(-7L)},
    {(int32_t)0xE61979B9L,
     (int32_t)0x15BB970EL,
     (int32_t)0xABEFA6B6L,
     (int32_t)9L,
     (int32_t)9L},
    {(int32_t)0x8AD7B590L,
     (int32_t)1L,
     (int32_t)(-9L),
     (int32_t)(-7L),
     (int32_t)0L},
    {(int32_t)0x86219E20L,
     (int32_t)0xFF541EDFL,
     (int32_t)0L,
     (int32_t)0x15BB970EL,
     (int32_t)(-1L)},
    {(int32_t)0x64A3C805L,
     (int32_t)0xF089E30CL,
     (int32_t)0x043A44ADL,
     (int32_t)0x043A44ADL,
     (int32_t)0xF089E30CL},
    {(int32_t)(-1L),
     (int32_t)0x48EDA297L,
     (int32_t)(-5L),
     (int32_t)(-1L),
     (int32_t)(-9L)},
    {(int32_t)0x9B762B02L,
     (int32_t)(-1L),
     (int32_t)0L,
     (int32_t)(-1L),
     (int32_t)1L}},
   {{(int32_t)0x88CB35B2L,
     (int32_t)0x86219E20L,
     (int32_t)8L,
     (int32_t)1L,
     (int32_t)(-7L)},
    {(int32_t)0x9B762B02L,
     (int32_t)0x14A140C5L,
     (int32_t)1L,
     (int32_t)0xA7F359A1L,
     (int32_t)(-2L)},
    {(int32_t)(-1L),
     (int32_t)9L,
     (int32_t)0L,
     (int32_t)(-7L),
     (int32_t)0x6D0B4E55L},
    {(int32_t)0x64A3C805L,
     (int32_t)0x9B762B02L,
     (int32_t)0xE61979B9L,
     (int32_t)1L,
     (int32_t)9L},
    {(int32_t)0x86219E20L,
     (int32_t)(-6L),
     (int32_t)0x043A44ADL,
     (int32_t)0x6B242CFFL,
     (int32_t)9L},
    {(int32_t)0x8AD7B590L,
     (int32_t)0xFF541EDFL,
     (int32_t)0x9F7A6BAEL,
     (int32_t)1L,
     (int32_t)(-1L)},
    {(int32_t)0xE61979B9L,
     (int32_t)(-1L),
     (int32_t)0x02A6F411L,
     (int32_t)0x043A44ADL,
     (int32_t)(-1L)},
    {(int32_t)0xF089E30CL,
     (int32_t)0x14A140C5L,
     (int32_t)0x0BF19973L,
     (int32_t)0x691D145CL,
     (int32_t)9L}},
   {{(int32_t)0x9B762B02L,
     (int32_t)0x691D145CL,
     (int32_t)0x501D2D5FL,
     (int32_t)0xF089E30CL,
     (int32_t)9L},
    {(int32_t)0xABEFA6B6L,
     (int32_t)0x8AD7B590L,
     (int32_t)8L,
     (int32_t)9L,
     (int32_t)0x6D0B4E55L},
    {(int32_t)0x15BB970EL,
     (int32_t)0x48EDA297L,
     (int32_t)0x48EDA297L,
     (int32_t)0x15BB970EL,
     (int32_t)(-2L)},
    {(int32_t)0x691D145CL,
     (int32_t)0xA7F359A1L,
     (int32_t)0x9F7A6BAEL,
     (int32_t)0x6B242CFFL,
     (int32_t)(-7L)},
    {(int32_t)0xABEFA6B6L,
     (int32_t)0x9B762B02L,
     (int32_t)(-5L),
     (int32_t)(-9L),
     (int32_t)1L},
    {(int32_t)0xFF541EDFL,
     (int32_t)1L,
     (int32_t)0x02A6F411L,
     (int32_t)0x6B242CFFL,
     (int32_t)(-9L)},
    {(int32_t)(-7L),
     (int32_t)0x86219E20L,
     (int32_t)0L,
     (int32_t)0x15BB970EL,
     (int32_t)0xF089E30CL},
    {(int32_t)0xE61979B9L,
     (int32_t)0x691D145CL,
     (int32_t)(-2L),
     (int32_t)9L,
     (int32_t)(-1L)}}};
static int32_t *g_71 = & g_69[1][7][3];
static uint8_t g_89[9][6][4] =
  {{{(uint8_t)1UL, (uint8_t)255UL, (uint8_t)247UL, (uint8_t)0x3CL},
    {(uint8_t)1UL, (uint8_t)1UL, (uint8_t)0x65L, (uint8_t)1UL},
    {(uint8_t)247UL, (uint8_t)0UL, (uint8_t)0xC7L, (uint8_t)0x11L},
    {(uint8_t)247UL, (uint8_t)0UL, (uint8_t)0x65L, (uint8_t)0xE5L},
    {(uint8_t)1UL, (uint8_t)0x11L, (uint8_t)247UL, (uint8_t)0UL},
    {(uint8_t)1UL, (uint8_t)247UL, (uint8_t)247UL, (uint8_t)1UL}},
   {{(uint8_t)0UL, (uint8_t)247UL, (uint8_t)0x11L, (uint8_t)1UL},
    {(uint8_t)0xE5L, (uint8_t)0x65L, (uint8_t)0UL, (uint8_t)247UL},
    {(uint8_t)0x11L, (uint8_t)0xC7L, (uint8_t)0UL, (uint8_t)247UL},
    {(uint8_t)1UL, (uint8_t)0x65L, (uint8_t)1UL, (uint8_t)1UL},
    {(uint8_t)0x3CL, (uint8_t)247UL, (uint8_t)255UL, (uint8_t)1UL},
    {(uint8_t)246UL, (uint8_t)247UL, (uint8_t)246UL, (uint8_t)1UL}},
   {{(uint8_t)246UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)1UL},
    {(uint8_t)247UL, (uint8_t)0UL, (uint8_t)1UL, (uint8_t)0UL},
    {(uint8_t)0x39L, (uint8_t)255UL, (uint8_t)1UL, (uint8_t)7UL},
    {(uint8_t)247UL, (uint8_t)0x39L, (uint8_t)0UL, (uint8_t)0x65L},
    {(uint8_t)246UL, (uint8_t)0xC7L, (uint8_t)0xFFL, (uint8_t)0xFFL},
    {(uint8_t)0xFFL, (uint8_t)0xFFL, (uint8_t)0xC7L, (uint8_t)246UL}},
   {{(uint8_t)0x65L, (uint8_t)0UL, (uint8_t)0x39L, (uint8_t)247UL},
    {(uint8_t)7UL, (uint8_t)1UL, (uint8_t)255UL, (uint8_t)0x39L},
    {(uint8_t)0UL, (uint8_t)1UL, (uint8_t)0UL, (uint8_t)247UL},
    {(uint8_t)1UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)246UL},
    {(uint8_t)1UL, (uint8_t)0xFFL, (uint8_t)252UL, (uint8_t)0xFFL},
    {(uint8_t)4UL, (uint8_t)0xC7L, (uint8_t)247UL, (uint8_t)0x65L}},
   {{(uint8_t)0x11L, (uint8_t)0x39L, (uint8_t)0xE5L, (uint8_t)7UL},
    {(uint8_t)252UL, (uint8_t)255UL, (uint8_t)1UL, (uint8_t)0UL},
    {(uint8_t)252UL, (uint8_t)0UL, (uint8_t)0xE5L, (uint8_t)1UL},
    {(uint8_t)0x11L, (uint8_t)0UL, (uint8_t)247UL, (uint8_t)1UL},
    {(uint8_t)4UL, (uint8_t)252UL, (uint8_t)252UL, (uint8_t)4UL},
    {(uint8_t)1UL, (uint8_t)247UL, (uint8_t)0UL, (uint8_t)0x11L}},
   {{(uint8_t)1UL, (uint8_t)0xE5L, (uint8_t)0UL, (uint8_t)252UL},
    {(uint8_t)0UL, (uint8_t)1UL, (uint8_t)255UL, (uint8_t)252UL},
    {(uint8_t)7UL, (uint8_t)0xE5L, (uint8_t)0x39L, (uint8_t)0x11L},
    {(uint8_t)0x65L, (uint8_t)247UL, (uint8_t)0xC7L, (uint8_t)4UL},
    {(uint8_t)0xFFL, (uint8_t)252UL, (uint8_t)0xFFL, (uint8_t)1UL},
    {(uint8_t)246UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)1UL}},
   {{(uint8_t)247UL, (uint8_t)0UL, (uint8_t)1UL, (uint8_t)0UL},
    {(uint8_t)0x39L, (uint8_t)255UL, (uint8_t)1UL, (uint8_t)7UL},
    {(uint8_t)247UL, (uint8_t)0x39L, (uint8_t)0UL, (uint8_t)0x65L},
    {(uint8_t)246UL, (uint8_t)0xC7L, (uint8_t)0xFFL, (uint8_t)0xFFL},
    {(uint8_t)0xFFL, (uint8_t)0xFFL, (uint8_t)0xC7L, (uint8_t)246UL},
    {(uint8_t)0x65L, (uint8_t)0UL, (uint8_t)0x39L, (uint8_t)247UL}},
   {{(uint8_t)7UL, (uint8_t)1UL, (uint8_t)255UL, (uint8_t)0x39L},
    {(uint8_t)0UL, (uint8_t)1UL, (uint8_t)0UL, (uint8_t)247UL},
    {(uint8_t)1UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)246UL},
    {(uint8_t)1UL, (uint8_t)0xFFL, (uint8_t)252UL, (uint8_t)0xFFL},
    {(uint8_t)4UL, (uint8_t)0xC7L, (uint8_t)247UL, (uint8_t)0x65L},
    {(uint8_t)0x11L, (uint8_t)0x39L, (uint8_t)0xE5L, (uint8_t)7UL}},
   {{(uint8_t)252UL, (uint8_t)255UL, (uint8_t)1UL, (uint8_t)0UL},
    {(uint8_t)252UL, (uint8_t)0UL, (uint8_t)0xE5L, (uint8_t)1UL},
    {(uint8_t)0x11L, (uint8_t)0UL, (uint8_t)247UL, (uint8_t)1UL},
    {(uint8_t)4UL, (uint8_t)252UL, (uint8_t)252UL, (uint8_t)4UL},
    {(uint8_t)1UL, (uint8_t)247UL, (uint8_t)0UL, (uint8_t)0x11L},
    {(uint8_t)1UL, (uint8_t)0xE5L, (uint8_t)0UL, (uint8_t)252UL}}};
static uint64_t g_92 = 2UL;
static int32_t const g_99 = (int32_t)0x1181933AL;
static uint16_t g_131 = (uint16_t)0xE95AL;
static uint16_t g_135 = (uint16_t)65535UL;
static int16_t g_143 = (int16_t)0xE80CL;
static uint32_t g_169 = (uint32_t)3UL;
static int8_t g_208 = (int8_t)0xFCL;
static int16_t g_239 = (int16_t)0x08B9L;
static uint64_t g_300 = (uint64_t)0xA7D234CDEC322C72LL;
static uint64_t *g_315 = & g_92;
static uint64_t **g_314 = & g_315;
static uint16_t *g_369 = & g_135;
static uint16_t g_394 = (uint16_t)1UL;
static uint16_t g_639 = (uint16_t)1UL;
static uint8_t g_767 = (uint8_t)0x44L;
static int64_t *g_847 = (int64_t *)0;
static int8_t *g_886 = & g_208;
static int8_t **g_885 = & g_886;
static int16_t const *g_952 = (int16_t const *)(& g_239);
static int16_t const **g_951 = & g_952;
static int64_t g_953 = 2L;
static uint16_t g_996 = (uint16_t)1UL;
static uint32_t g_1031 = (uint32_t)4294967292UL;
static uint32_t g_1037 = (uint32_t)0x2DBB3649L;
static int32_t g_1060 = (int32_t)1L;
static int32_t **g_1583 = & g_71;
static uint32_t g_1890 = (uint32_t)0xBF49A2BCL;
static void func_1_slice_1(void);

static void func_8_slice_1(uint32_t *p_11);

static uint32_t *func_14_slice_1(void);

static void func_20_slice_1(uint32_t p_21, uint32_t const p_22);

static int32_t func_25_slice_1(uint32_t * const p_26);

static uint32_t *func_27_slice_1(void);

static void func_29_slice_1(void);

static void func_38_slice_1(void);

static void func_41_slice_1(uint64_t p_42, uint32_t *p_43, uint32_t p_44);

static void func_1_slice_1(void)
{
  int32_t l_35[2];
  int i;
  uint32_t *tmp_38;
  int tmp_15;
  int32_t tmp_36;
  int tmp_16;
  int32_t tmp_35;
  uint32_t *tmp_34;
  int tmp_19;
  int tmp_28;
  char tmp_40;
  uint64_t l_1035 = 0UL;
  uint32_t *l_1036 = & g_1037;
  i = 0;
  while (i < 2) {
    l_35[i] = (int32_t)0xB288586FL;
    i ++;
  }
  tmp_15 = realsmith_proxy_ROOFK_slice_1();
  tmp_16 = realsmith_NpCyp_slice_1();
  tmp_19 = realsmith_OLlJA_slice_1();
  tmp_28 = 1;
  func_41_slice_1((uint64_t)tmp_28,l_1036,
                  (uint32_t)(((((tmp_19 + l_35[1]) + (int)g_13) + (int)l_1035) - -1299687320) + l_35[1]));
  func_29_slice_1();
  tmp_34 = func_27_slice_1();
  tmp_35 = func_25_slice_1(tmp_34);
  tmp_36 = safe_mod_func_int32_t_s_s_slice_1(tmp_35);
  func_20_slice_1((uint32_t)tmp_36,
                  (uint32_t)((((((tmp_15 + l_35[1]) + g_99) + (int)g_13) + (int)l_1035) - -1005982796) + l_35[1]));
  tmp_38 = func_14_slice_1();
  tmp_40 = realsmith_proxy_5VZLX_slice_1((int)g_13 + 70);
  func_8_slice_1(tmp_38);
  g_767 = (uint8_t)0;
  while ((int)g_767 <= 0) g_767 = (uint8_t)((int)g_767 + 1);
  return;
}

static void func_8_slice_1(uint32_t *p_11)
{
  int32_t l_1935[2];
  int i;
  int tmp_9;
  uint32_t tmp_6;
  int32_t *l_1946 = & g_1060;
  i = 0;
  while (i < 2) {
    l_1935[i] = (int32_t)0xD9F01A30L;
    i ++;
  }
  tmp_6 = (uint32_t)l_1935[1];
  *p_11 = tmp_6;
  tmp_9 = 1;
  *l_1946 = (int32_t)((long)*l_1946 | (-8L & (long)tmp_9));
  return;
}

static uint32_t *func_14_slice_1(void)
{
  uint32_t *__retres;
  g_953 = (int64_t)(-4);
  {
    uint32_t *l_1932 = & g_37;
    __retres = l_1932;
    goto return_label;
  }
  return_label: return __retres;
}

static void func_20_slice_1(uint32_t p_21, uint32_t const p_22)
{
  uint8_t tmp_7;
  int tmp_1;
  int8_t tmp_6;
  int64_t tmp_5;
  int tmp_3;
  int tmp_4;
  int16_t tmp_0;
  int tmp_11;
  int64_t **l_1904[9][3][6] =
    {{{& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, (int64_t **)0, & g_847, (int64_t **)0, & g_847, & g_847}},
     {{(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, (int64_t **)0},
      {(int64_t **)0, & g_847, & g_847, (int64_t **)0, & g_847, (int64_t **)0}},
     {{& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {(int64_t **)0, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, (int64_t **)0, & g_847, & g_847, & g_847}},
     {{& g_847, & g_847, & g_847, (int64_t **)0, & g_847, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}},
     {{& g_847, (int64_t **)0, (int64_t **)0, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, (int64_t **)0}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, (int64_t **)0, & g_847, & g_847}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}},
     {{& g_847, & g_847, (int64_t **)0, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}}};
  int32_t l_1907 = (int32_t)0x4CBF1883L;
  uint16_t l_1908[3][5] =
    {{(uint16_t)0x6341L,
      (uint16_t)0UL,
      (uint16_t)0x6341L,
      (uint16_t)0xCA1DL,
      (uint16_t)0x9411L},
     {(uint16_t)0xC7B5L,
      (uint16_t)0UL,
      (uint16_t)0x9411L,
      (uint16_t)0UL,
      (uint16_t)0xC7B5L},
     {(uint16_t)0x6341L,
      (uint16_t)0UL,
      (uint16_t)0UL,
      (uint16_t)0xC7B5L,
      (uint16_t)0UL}};
  int16_t *l_1909 = & g_143;
  tmp_1 = realsmith_Kr7kP_slice_1();
  tmp_3 = realsmith_proxy_M9dfD_slice_1();
  tmp_4 = realsmith_proxy_Uxiok_slice_1((int)p_22 + 1299687222);
  tmp_5 = safe_sub_func_int64_t_s_s_slice_1((int64_t)((uint32_t)((tmp_4 + (int)p_22) - -1299687404) + p_22),
                                            (int64_t)((uint32_t)((tmp_3 + (int)p_21) - 65283) + p_21));
  tmp_6 = safe_mul_func_int8_t_s_s_slice_1((int8_t)(l_1904[6][0][2] == & g_847),
                                           (int8_t)tmp_5);
  l_1907 ^= (int)tmp_6;
  tmp_7 = safe_mul_func_uint8_t_u_u_slice_1((uint8_t)l_1907,
                                            (uint8_t)((int)((uint16_t)(
                                                      (tmp_1 + (int)l_1908[0][0]) - 25410)) + (int)l_1908[0][0]));
  tmp_0 = (int16_t)tmp_7;
  *l_1909 = tmp_0;
  tmp_11 = realsmith_proxy_uzIp8_slice_1((int)*g_952 + -82,
                                         (unsigned long)*g_952 + (unsigned long)80);
  g_1060 = 0x0057L == (long)((int)((int16_t)((tmp_11 + (int)*g_952) - 15)) + (int)*g_952);
  return;
}

static int32_t func_25_slice_1(uint32_t * const p_26)
{
  int32_t __retres;
  uint16_t tmp_42;
  int tmp;
  uint16_t *tmp_10;
  unsigned int tmp_111;
  uint8_t l_1682 = (uint8_t)255UL;
  uint16_t *l_1711 = & g_639;
  uint16_t **l_1712 = & g_369;
  uint32_t *l_1715 = & g_169;
  int32_t *l_1716 = & g_1060;
  tmp = realsmith_Qy9wa_slice_1();
  (*p_26) ++;
  tmp_10 = l_1711;
  *l_1712 = tmp_10;
  *l_1715 = (uint32_t)((long)*l_1715 ^ 0x745646DFL);
  tmp_42 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)((unsigned int)(
                                                            (int)((uint8_t)(
                                                            (((tmp + (int)l_1682) + (int)*(*g_951)) + (int)*g_952) - 4734)) + (int)l_1682) ^ *p_26));
  *l_1716 |= (int)tmp_42;
  g_239 = (int16_t)14;
  goto break_cont_1;
  break_cont_1:
  tmp_111 = realsmith_proxy_mIMvr_slice_1((char)((int)((char)*l_1716) + -43));
  __retres = (int32_t)((tmp_111 + (unsigned int)*l_1716) - (unsigned int)65283) + *l_1716;
  return __retres;
}

static uint32_t *func_27_slice_1(void)
{
  uint32_t *__retres;
  int8_t const l_1637[5][2];
  int16_t tmp_9;
  unsigned char tmp_7;
  int tmp_8;
  long tmp_36;
  int8_t ** const *l_1643[10] =
    {(int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885)};
  int8_t ** const **l_1642 = & l_1643[1];
  uint32_t *l_1679[8] =
    {& g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031};
  tmp_7 = realsmith_oNKmy_slice_1();
  tmp_8 = realsmith_d8YzX_slice_1();
  tmp_9 = safe_div_func_int16_t_s_s_slice_1((int16_t)((long)((int)((int8_t)(
                                                             (((((tmp_8 + (int)l_1637[1][1]) + (int)l_1637[3][1]) + (int)*g_315) + (int)g_1890) + (int)g_996) - -1085693243)) + (int)l_1637[1][1]) == 0L),
                                            (int16_t)((int)((int16_t)(
                                                      (((((int)tmp_7 + (int)((unsigned char)*g_952)) + (int)((unsigned char)g_996)) + (
                                                        (int)((unsigned char)g_1890) - 188)) + (int)((unsigned char)*g_315)) - 189)) + (int)*g_952));
  *(*(*(*l_1642))) = (int8_t)((int)*(*(*(*l_1642))) ^ (int)tmp_9);
  tmp_36 = realsmith_EUAS7_slice_1((int)l_1637[1][1] + 44);
  *g_315 ^= (unsigned long)((int)((int8_t)((tmp_36 + (long)l_1637[1][1]) - (long)333)) + (int)l_1637[1][1]);
  func_38_slice_1();
  __retres = l_1679[3];
  return __retres;
}

static void func_29_slice_1(void)
{
  (*g_315) --;
  return;
}

static void func_38_slice_1(void)
{
  int32_t *l_1186 = & g_1060;
  *l_1186 = (int32_t)0L;
  return;
}

static void func_41_slice_1(uint64_t p_42, uint32_t *p_43, uint32_t p_44)
{
  int16_t *l_1156;
  int16_t l_1117[5][9] =
    {{(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)0x08E1L,
      (int16_t)(-9L),
      (int16_t)3L,
      (int16_t)0x3B4AL,
      (int16_t)(-9L),
      (int16_t)0x3B4AL,
      (int16_t)3L},
     {(int16_t)(-9L),
      (int16_t)0x08E1L,
      (int16_t)0x08E1L,
      (int16_t)(-9L),
      (int16_t)3L,
      (int16_t)0x3B4AL,
      (int16_t)(-9L),
      (int16_t)0x3B4AL,
      (int16_t)3L}};
  int16_t **l_1155[10][6][4] =
    {{{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, (int16_t **)0}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, (int16_t **)0, (int16_t **)0, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{(int16_t **)0, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, & l_1156, & l_1156, (int16_t **)0}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}}};
  (*g_315) ++;
  {
    int tmp_21;
    int8_t tmp_20;
    g_394 = (uint16_t)(-1);
    tmp_21 = realsmith_DlTrX_slice_1();
    tmp_20 = (int8_t)((int)((int16_t)((((((tmp_21 + (int)l_1117[2][0]) + (int)p_44) + (int)*p_43) + (int)p_42) + (int)g_300) - -864715228)) + (int)l_1117[2][0] < (
                      (void *)(& g_952) != (void *)l_1155[7][0][1]));
    *(*g_885) = tmp_20;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


