/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_div_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1)
{
  int32_t tmp;
  tmp = si1;
  return tmp;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int64_t const g_13 = -1L;
static uint32_t g_37 = (uint32_t)0x6BB2F144L;
static uint32_t *g_36[2][10][7] =
  {{{& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37,
     & g_37,
     (uint32_t *)0,
     & g_37,
     (uint32_t *)0,
     & g_37,
     (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37}},
   {{& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, (uint32_t *)0},
    {& g_37, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37},
    {& g_37, (uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0},
    {(uint32_t *)0, & g_37, & g_37, & g_37, & g_37, (uint32_t *)0, & g_37}}};
static uint64_t g_92 = 2UL;
static int32_t const g_99 = (int32_t)0x1181933AL;
static uint16_t g_135 = (uint16_t)65535UL;
static int16_t g_143 = (int16_t)0xE80CL;
static uint32_t g_169 = (uint32_t)3UL;
static int8_t g_208 = (int8_t)0xFCL;
static int16_t g_239 = (int16_t)0x08B9L;
static uint64_t *g_315 = & g_92;
static uint16_t *g_369 = & g_135;
static uint16_t g_394 = (uint16_t)1UL;
static uint16_t g_639 = (uint16_t)1UL;
static uint8_t g_767 = (uint8_t)0x44L;
static int64_t *g_847 = (int64_t *)0;
static int8_t *g_886 = & g_208;
static int8_t **g_885 = & g_886;
static int16_t const *g_952 = (int16_t const *)(& g_239);
static int16_t const **g_951 = & g_952;
static int64_t g_953 = 2L;
static uint32_t g_1031 = (uint32_t)4294967292UL;
static int32_t g_1060 = (int32_t)1L;
static void func_1_slice_1(void);

static void func_8_slice_1(uint32_t *p_11);

static uint32_t *func_14_slice_1(void);

static void func_20_slice_1(uint32_t p_21, uint32_t const p_22);

static int32_t func_25_slice_1(uint32_t * const p_26);

static uint32_t *func_27_slice_1(void);

static void func_29_slice_1(void);

static void func_38_slice_1(void);

static void func_41_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t l_35[2];
  int i;
  uint32_t *tmp_24;
  int32_t tmp_22;
  int32_t tmp_21;
  uint32_t *tmp_20;
  int tmp_15;
  uint64_t l_1035 = 0UL;
  i = 0;
  while (i < 2) {
    l_35[i] = (int32_t)0xB288586FL;
    i ++;
  }
  tmp_15 = 1;
  func_41_slice_1();
  func_29_slice_1();
  tmp_20 = func_27_slice_1();
  tmp_21 = func_25_slice_1(tmp_20);
  tmp_22 = safe_mod_func_int32_t_s_s_slice_1(tmp_21);
  func_20_slice_1((uint32_t)tmp_22,(uint32_t)l_35[1]);
  tmp_24 = func_14_slice_1();
  func_8_slice_1(tmp_24);
  g_767 = (uint8_t)0;
  while ((int)g_767 <= 0) g_767 = (uint8_t)((int)g_767 + 1);
  return;
}

static void func_8_slice_1(uint32_t *p_11)
{
  int32_t l_1935[2];
  int i;
  int tmp_4;
  uint32_t tmp_2;
  int32_t *l_1946 = & g_1060;
  i = 0;
  while (i < 2) {
    l_1935[i] = (int32_t)0xD9F01A30L;
    i ++;
  }
  tmp_2 = (uint32_t)l_1935[1];
  *p_11 = tmp_2;
  tmp_4 = 1;
  *l_1946 = (int32_t)((long)*l_1946 | (-8L & (long)tmp_4));
  return;
}

static uint32_t *func_14_slice_1(void)
{
  uint32_t *__retres;
  g_953 = (int64_t)(-4);
  {
    uint32_t *l_1932 = & g_37;
    __retres = l_1932;
    goto return_label;
  }
  return_label: return __retres;
}

static void func_20_slice_1(uint32_t p_21, uint32_t const p_22)
{
  uint8_t tmp_2;
  int8_t tmp_1;
  int64_t tmp_0;
  int16_t tmp;
  int64_t **l_1904[9][3][6] =
    {{{& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, (int64_t **)0, & g_847, (int64_t **)0, & g_847, & g_847}},
     {{(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, (int64_t **)0},
      {(int64_t **)0, & g_847, & g_847, (int64_t **)0, & g_847, (int64_t **)0}},
     {{& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {(int64_t **)0, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, (int64_t **)0, & g_847, & g_847, & g_847}},
     {{& g_847, & g_847, & g_847, (int64_t **)0, & g_847, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}},
     {{& g_847, (int64_t **)0, (int64_t **)0, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, (int64_t **)0}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, (int64_t **)0, & g_847, & g_847}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {(int64_t **)0, & g_847, & g_847, & g_847, (int64_t **)0, & g_847}},
     {{& g_847, (int64_t **)0, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, (int64_t **)0, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}},
     {{& g_847, & g_847, (int64_t **)0, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847},
      {& g_847, & g_847, & g_847, & g_847, & g_847, & g_847}}};
  int32_t l_1907 = (int32_t)0x4CBF1883L;
  uint16_t l_1908[3][5] =
    {{(uint16_t)0x6341L,
      (uint16_t)0UL,
      (uint16_t)0x6341L,
      (uint16_t)0xCA1DL,
      (uint16_t)0x9411L},
     {(uint16_t)0xC7B5L,
      (uint16_t)0UL,
      (uint16_t)0x9411L,
      (uint16_t)0UL,
      (uint16_t)0xC7B5L},
     {(uint16_t)0x6341L,
      (uint16_t)0UL,
      (uint16_t)0UL,
      (uint16_t)0xC7B5L,
      (uint16_t)0UL}};
  int16_t *l_1909 = & g_143;
  tmp_0 = safe_sub_func_int64_t_s_s_slice_1((int64_t)p_22,(int64_t)p_21);
  tmp_1 = safe_mul_func_int8_t_s_s_slice_1((int8_t)(l_1904[6][0][2] == & g_847),
                                           (int8_t)tmp_0);
  l_1907 ^= (int)tmp_1;
  tmp_2 = safe_mul_func_uint8_t_u_u_slice_1((uint8_t)l_1907,
                                            (uint8_t)l_1908[0][0]);
  tmp = (int16_t)tmp_2;
  *l_1909 = tmp;
  g_1060 = 0x0057L == (long)*g_952;
  return;
}

static int32_t func_25_slice_1(uint32_t * const p_26)
{
  int32_t __retres;
  uint16_t tmp_10;
  uint16_t *tmp_0;
  uint8_t l_1682 = (uint8_t)255UL;
  uint16_t *l_1711 = & g_639;
  uint16_t **l_1712 = & g_369;
  uint32_t *l_1715 = & g_169;
  int32_t *l_1716 = & g_1060;
  (*p_26) ++;
  tmp_0 = l_1711;
  *l_1712 = tmp_0;
  *l_1715 = (uint32_t)((long)*l_1715 ^ 0x745646DFL);
  tmp_10 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)((unsigned int)l_1682 ^ *p_26));
  *l_1716 |= (int)tmp_10;
  g_239 = (int16_t)14;
  goto break_cont_1;
  break_cont_1: __retres = *l_1716;
  return __retres;
}

static uint32_t *func_27_slice_1(void)
{
  uint32_t *__retres;
  int8_t const l_1637[5][2];
  int16_t tmp_0;
  int8_t ** const *l_1643[10] =
    {(int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885),
     (int8_t ** const *)(& g_885)};
  int8_t ** const **l_1642 = & l_1643[1];
  uint32_t *l_1679[8] =
    {& g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031,
     & g_1031};
  tmp_0 = safe_div_func_int16_t_s_s_slice_1((int16_t)((long)l_1637[1][1] == 0L),
                                            *g_952);
  *(*(*(*l_1642))) = (int8_t)((int)*(*(*(*l_1642))) ^ (int)tmp_0);
  *g_315 ^= (unsigned long)l_1637[1][1];
  func_38_slice_1();
  __retres = l_1679[3];
  return __retres;
}

static void func_29_slice_1(void)
{
  (*g_315) --;
  return;
}

static void func_38_slice_1(void)
{
  int32_t *l_1186 = & g_1060;
  *l_1186 = (int32_t)0L;
  return;
}

static void func_41_slice_1(void)
{
  int16_t *l_1156;
  int16_t l_1117[5][9] =
    {{(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)(-9L),
      (int16_t)0xC2F9L,
      (int16_t)0x7576L,
      (int16_t)5L,
      (int16_t)0xC2F9L,
      (int16_t)5L,
      (int16_t)0x7576L},
     {(int16_t)0xC2F9L,
      (int16_t)(-9L),
      (int16_t)0x08E1L,
      (int16_t)(-9L),
      (int16_t)3L,
      (int16_t)0x3B4AL,
      (int16_t)(-9L),
      (int16_t)0x3B4AL,
      (int16_t)3L},
     {(int16_t)(-9L),
      (int16_t)0x08E1L,
      (int16_t)0x08E1L,
      (int16_t)(-9L),
      (int16_t)3L,
      (int16_t)0x3B4AL,
      (int16_t)(-9L),
      (int16_t)0x3B4AL,
      (int16_t)3L}};
  int16_t **l_1155[10][6][4] =
    {{{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, (int16_t **)0},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, (int16_t **)0}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, (int16_t **)0, (int16_t **)0, (int16_t **)0},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}},
     {{(int16_t **)0, & l_1156, & l_1156, (int16_t **)0},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, & l_1156, & l_1156, (int16_t **)0}},
     {{& l_1156, & l_1156, & l_1156, (int16_t **)0},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {(int16_t **)0, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, (int16_t **)0, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156}},
     {{& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156},
      {& l_1156, & l_1156, (int16_t **)0, & l_1156},
      {& l_1156, & l_1156, & l_1156, & l_1156}}};
  (*g_315) ++;
  {
    int8_t tmp_16;
    g_394 = (uint16_t)(-1);
    tmp_16 = (int8_t)((int)l_1117[2][0] < ((void *)(& g_952) != (void *)l_1155[7][0][1]));
    *(*g_885) = tmp_16;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


