/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static unsigned long realsmith_5SPQk_slice_1(unsigned long const name_len) __attribute__((
__used__));
static unsigned long realsmith_5SPQk_slice_1(unsigned long const name_len)
{
  unsigned long __retres;
  __retres = (((unsigned long)96 + name_len) + (unsigned long)2) + (unsigned long)4;
  return __retres;
}

__inline static int realsmith_j4G2y_slice_1(void) __attribute__((__used__));
__inline static int realsmith_j4G2y_slice_1(void)
{
  int tmp;
  tmp = 0;
  return tmp;
}

static int realsmith_hRuh1_slice_1(void) __attribute__((__used__));
static int realsmith_hRuh1_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_dwUr2_slice_1(void)
{
  int proxy_ret_rnwcP = realsmith_hRuh1_slice_1();
  return proxy_ret_rnwcP;
}

int EPERM_realsmith_hFso8 = -9;
static int realsmith_hFso8_slice_1(void) __attribute__((__used__));
static int realsmith_hFso8_slice_1(void)
{
  int error;
  error = EPERM_realsmith_hFso8;
  return error;
}

int realsmith_proxy_zcjwh_slice_1(void)
{
  int proxy_ret_S8Eqx = realsmith_hFso8_slice_1();
  return proxy_ret_S8Eqx;
}

__inline static char *realsmith_X2emH_slice_1(void) __attribute__((__used__));
__inline static char *realsmith_X2emH_slice_1(void)
{
  char *__retres;
  __retres = (char *)"0";
  return __retres;
}

char realsmith_proxy_blIli_slice_1(void)
{
  char __retres;
  char proxy_uR400[13];
  char *proxy_ret_T44Oc = realsmith_X2emH_slice_1();
  __retres = *proxy_ret_T44Oc;
  return __retres;
}

int realsmith_L92eV_slice_1(void)
{
  int __retres;
  int pa;
  pa = 1;
  __retres = pa;
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_2[1][2][10] =
  {{{(int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L},
    {(int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L}}};
static int32_t g_7 = (int32_t)0xE0369BD6L;
static int64_t g_61[1] = {5L};
static uint8_t g_73 = (uint8_t)251UL;
static uint16_t g_85[6][7] =
  {{(uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL},
   {(uint16_t)0x336FL,
    (uint16_t)0x336FL,
    (uint16_t)65535UL,
    (uint16_t)0x336FL,
    (uint16_t)0x336FL,
    (uint16_t)65535UL,
    (uint16_t)0x336FL},
   {(uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL},
   {(uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL},
   {(uint16_t)0x336FL,
    (uint16_t)0x336FL,
    (uint16_t)65535UL,
    (uint16_t)0x336FL,
    (uint16_t)0x336FL,
    (uint16_t)65535UL,
    (uint16_t)0x336FL},
   {(uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL,
    (uint16_t)0UL,
    (uint16_t)0UL,
    (uint16_t)0x336FL}};
static int32_t const g_95 = (int32_t)0xDBC71B59L;
static uint16_t g_115 = (uint16_t)65535UL;
static uint64_t g_153 = (uint64_t)0x809F826083B57DFALL;
static int32_t g_163 = (int32_t)(-2L);
static int32_t *g_162 = & g_163;
static uint8_t g_168[5][7][3] =
  {{{(uint8_t)254UL, (uint8_t)254UL, (uint8_t)0x2EL},
    {(uint8_t)0xEEL, (uint8_t)0x8AL, (uint8_t)252UL},
    {(uint8_t)0x16L, (uint8_t)0x2EL, (uint8_t)0x57L},
    {(uint8_t)255UL, (uint8_t)0x81L, (uint8_t)1UL},
    {(uint8_t)0x7FL, (uint8_t)0x16L, (uint8_t)0x57L},
    {(uint8_t)1UL, (uint8_t)247UL, (uint8_t)252UL},
    {(uint8_t)0x10L, (uint8_t)0UL, (uint8_t)0x2EL}},
   {{(uint8_t)0xB9L, (uint8_t)0x89L, (uint8_t)0x5EL},
    {(uint8_t)254UL, (uint8_t)0x2EL, (uint8_t)0x7FL},
    {(uint8_t)249UL, (uint8_t)0x74L, (uint8_t)0xB9L},
    {(uint8_t)0x10L, (uint8_t)0xC4L, (uint8_t)0UL},
    {(uint8_t)0x84L, (uint8_t)0x60L, (uint8_t)1UL},
    {(uint8_t)0x10L, (uint8_t)254UL, (uint8_t)0xC4L},
    {(uint8_t)249UL, (uint8_t)0x81L, (uint8_t)1UL}},
   {{(uint8_t)254UL, (uint8_t)1UL, (uint8_t)1UL},
    {(uint8_t)0x5EL, (uint8_t)0x89L, (uint8_t)1UL},
    {(uint8_t)0x7FL, (uint8_t)0x57L, (uint8_t)0xC4L},
    {(uint8_t)0xB9L, (uint8_t)0x8AL, (uint8_t)1UL},
    {(uint8_t)0UL, (uint8_t)0xB8L, (uint8_t)0UL},
    {(uint8_t)1UL, (uint8_t)0x8AL, (uint8_t)0xB9L},
    {(uint8_t)0xC4L, (uint8_t)0x57L, (uint8_t)0x7FL}},
   {{(uint8_t)1UL, (uint8_t)0x89L, (uint8_t)0x5EL},
    {(uint8_t)1UL, (uint8_t)1UL, (uint8_t)254UL},
    {(uint8_t)1UL, (uint8_t)0x81L, (uint8_t)249UL},
    {(uint8_t)0xC4L, (uint8_t)254UL, (uint8_t)0x10L},
    {(uint8_t)1UL, (uint8_t)0x60L, (uint8_t)0x84L},
    {(uint8_t)0UL, (uint8_t)0xC4L, (uint8_t)0x10L},
    {(uint8_t)0xB9L, (uint8_t)0x74L, (uint8_t)249UL}},
   {{(uint8_t)0x7FL, (uint8_t)0x2EL, (uint8_t)254UL},
    {(uint8_t)0x5EL, (uint8_t)246UL, (uint8_t)0x5EL},
    {(uint8_t)254UL, (uint8_t)0x2EL, (uint8_t)0x7FL},
    {(uint8_t)249UL, (uint8_t)0x74L, (uint8_t)0xB9L},
    {(uint8_t)0x10L, (uint8_t)0xC4L, (uint8_t)0UL},
    {(uint8_t)0x84L, (uint8_t)0x60L, (uint8_t)1UL},
    {(uint8_t)0x10L, (uint8_t)254UL, (uint8_t)0xC4L}}};
static int8_t g_170[1][1][1] = {{{(int8_t)0x06L}}};
static int32_t g_182[1] = {(int32_t)(-8L)};
static int32_t g_183 = (int32_t)0x1D961218L;
static int64_t g_258 = 1L;
static int16_t g_283 = (int16_t)0x56E4L;
static uint16_t g_583 = (uint16_t)65535UL;
static int64_t g_899 = 1L;
static int32_t g_1019 = (int32_t)(-1L);
static uint16_t const *g_1309 = (uint16_t const *)(& g_583);
static uint16_t const **g_1308 = & g_1309;
static uint16_t const ***g_1307 = & g_1308;
static uint16_t const ****g_1306 = & g_1307;
static void func_1_slice_1(void);

static int16_t func_8_slice_1(int32_t p_13);

static void func_14_slice_1(void);

static void func_20_slice_1(void);

static void func_42_slice_1(void);

static void func_44_slice_1(void);

static void func_50_slice_1(void);

static void func_56_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t const l_389;
  int32_t l_387 = (int32_t)0x476571A6L;
  int32_t *l_850 = & g_2[0][1][9];
  int32_t l_1864 = (int32_t)1L;
  g_2[0][1][5] = 0;
  while (g_2[0][1][5] >= -26) {
    {
      int16_t tmp_28;
      unsigned long tmp_1;
      int32_t tmp_0;
      int32_t *l_6 = & g_7;
      tmp_1 = realsmith_5SPQk_slice_1((unsigned long)l_387 + (unsigned long)(-1197830506));
      g_61[0] = (int64_t)g_2[0][1][7];
      func_56_slice_1();
      func_50_slice_1();
      func_44_slice_1();
      func_42_slice_1();
      func_20_slice_1();
      func_14_slice_1();
      tmp_28 = func_8_slice_1((int32_t)((((tmp_1 + (unsigned long)l_1864) + (unsigned long)l_387) + (unsigned long)l_389) - (unsigned long)1197830736) + *l_850);
      tmp_0 = (int32_t)((long)tmp_28 | 1L);
      *l_6 = tmp_0;
    }
    (g_2[0][1][5]) --;
  }
  return;
}

static int16_t func_8_slice_1(int32_t p_13)
{
  int16_t __retres;
  int tmp;
  *g_162 = (int32_t)(-3L);
  tmp = realsmith_L92eV_slice_1();
  __retres = (int16_t)(((tmp + p_13) - -1984608746) + p_13);
  return __retres;
}

static void func_14_slice_1(void)
{
  g_1019 = 0;
  return;
}

static void func_20_slice_1(void)
{
  g_1019 = 0;
  while (g_1019 >= 0) {
    {
      uint16_t const ****tmp_0;
      uint16_t const *****l_1310 = & g_1306;
      tmp_0 = g_1306;
      *l_1310 = tmp_0;
      g_583 = (uint16_t)0;
      while ((int)g_583 <= 0) {
        g_899 = (int64_t)0;
        while (g_899 >= (int64_t)0) {
          func_50_slice_1();
          g_899 -= (int64_t)1;
        }
        goto break_cont_1;
        break_cont_1: g_583 = (uint16_t)((int)g_583 + 1);
      }
    }
    g_1019 --;
  }
  return;
}

static void func_42_slice_1(void)
{
  g_283 = (int16_t)0;
  while ((int)g_283 > -25) {
    g_153 = (uint64_t)9;
    goto break_cont_2;
    break_cont_2: g_258 = (int64_t)(-18);
    g_283 = (int16_t)((int)g_283 - 1);
  }
  return;
}

static void func_44_slice_1(void)
{
  uint64_t *l_399 = & g_153;
  (*l_399) ++;
  g_183 = 0;
  return;
}

static void func_50_slice_1(void)
{
  uint16_t *l_114 = & g_115;
  {
    uint16_t tmp_2;
    uint16_t tmp_1;
    tmp_2 = (uint16_t)g_73;
    tmp_1 = tmp_2;
    *l_114 = tmp_1;
  }
  g_73 = (uint8_t)0;
  goto break_cont_3;
  break_cont_3: ;
  return;
}

static void func_56_slice_1(void)
{
  int64_t const l_67;
  char tmp_1;
  int tmp_2;
  int16_t tmp_7;
  uint16_t tmp_5;
  int tmp_3;
  int tmp_6;
  uint8_t tmp_0;
  uint8_t *l_72 = & g_73;
  tmp_1 = realsmith_proxy_blIli_slice_1();
  tmp_2 = realsmith_j4G2y_slice_1();
  tmp_3 = realsmith_proxy_dwUr2_slice_1();
  tmp_5 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(0x57CFL != (long)(
                                                           1UL != (unsigned long)l_67)));
  tmp_6 = realsmith_proxy_zcjwh_slice_1();
  tmp_7 = safe_mul_func_int16_t_s_s_slice_1((int16_t)((int64_t)(((((tmp_6 + (int)g_61[0]) + g_2[0][0][9]) + g_182[0]) + (int)g_168[1][5][0]) - 1) + g_61[0]),
                                            (int16_t)tmp_5);
  tmp_0 = (uint8_t)(g_2[0][1][5] < ((((int64_t)(((((int)tmp_1 + (int)((char)l_67)) + (int)((char)g_182[0])) + (int)((char)g_2[0][0][9])) - 50) + l_67) | (
                                     (int64_t)(((((tmp_2 + (int)l_67) + (int)g_168[1][5][0]) + g_182[0]) + g_2[0][1][2]) - 18) + l_67)) != (long)(
                                    0xD7FCCEA59F7C1AE2LL > (unsigned long long)(
                                    (long)tmp_7 <= -9L))));
  *l_72 = tmp_0;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


