/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
static int16_t g_1141 = (int16_t)2L;
/*@ requires valid_read_string(format); */
int printf_va_2(char const * restrict format, int param0);

void main(void)
{
  printf_va_2("g_1141 value: %d\n",(int)g_1141);
  return;
}


