/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_2[1][2][10] =
  {{{(int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L},
    {(int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)0x89B54615L,
     (int32_t)0x89B54615L}}};
static int32_t g_7 = (int32_t)0xE0369BD6L;
static int64_t g_61[1] = {5L};
static uint8_t g_73 = (uint8_t)251UL;
static uint16_t g_115 = (uint16_t)65535UL;
static uint64_t g_153 = (uint64_t)0x809F826083B57DFALL;
static int32_t g_163 = (int32_t)(-2L);
static int32_t *g_162 = & g_163;
static int8_t g_170[1][1][1] = {{{(int8_t)0x06L}}};
static int32_t g_183 = (int32_t)0x1D961218L;
static int64_t g_258 = 1L;
static int16_t g_283 = (int16_t)0x56E4L;
static uint64_t *g_501 = & g_153;
static uint16_t g_583 = (uint16_t)65535UL;
static int64_t g_899 = 1L;
static int32_t g_1019 = (int32_t)(-1L);
static int16_t g_1141 = (int16_t)2L;
static uint16_t const *g_1309 = (uint16_t const *)(& g_583);
static uint16_t const **g_1308 = & g_1309;
static uint16_t const ***g_1307 = & g_1308;
static uint16_t const ****g_1306 = & g_1307;
static void func_1_slice_1(void);

static int16_t func_8_slice_1(int32_t p_13);

static void func_14_slice_1(void);

static void func_20_slice_1(int32_t *p_22);

static void func_42_slice_1(void);

static void func_44_slice_1(void);

static void func_50_slice_1(void);

static void func_56_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t *l_850 = & g_2[0][1][9];
  g_2[0][1][5] = 0;
  while (g_2[0][1][5] >= -26) {
    {
      int16_t tmp_12;
      int32_t tmp;
      int32_t *l_6 = & g_7;
      g_61[0] = (int64_t)g_2[0][1][7];
      func_56_slice_1();
      func_50_slice_1();
      func_44_slice_1();
      func_42_slice_1();
      func_20_slice_1(l_6);
      func_14_slice_1();
      tmp_12 = func_8_slice_1(*l_850);
      tmp = (int32_t)((long)tmp_12 | 1L);
      *l_6 = tmp;
    }
    (g_2[0][1][5]) --;
  }
  return;
}

static int16_t func_8_slice_1(int32_t p_13)
{
  int16_t __retres;
  *g_162 = (int32_t)(-3L);
  __retres = (int16_t)p_13;
  return __retres;
}

static void func_14_slice_1(void)
{
  g_1019 = 0;
  return;
}

static void func_20_slice_1(int32_t *p_22)
{
  g_1019 = 0;
  while (g_1019 >= 0) {
    {
      uint16_t * const **l_1302[10];
      uint16_t * const ***tmp;
      uint16_t const ****tmp_0;
      uint16_t * const ***l_1301 = & l_1302[8];
      uint16_t const *****l_1310 = & g_1306;
      tmp = l_1301;
      tmp_0 = g_1306;
      *l_1310 = tmp_0;
      *p_22 = (void *)tmp == (void *)tmp_0;
      g_583 = (uint16_t)0;
      while ((int)g_583 <= 0) {
        g_899 = (int64_t)0;
        while (g_899 >= (int64_t)0) {
          *p_22 = (int32_t)0x8F00C220L;
          func_50_slice_1();
          g_899 -= (int64_t)1;
        }
        {
          int tmp_24;
          int16_t tmp_21;
          uint16_t l_1334 = (uint16_t)0xA497L;
          int16_t *l_1344 = & g_1141;
          *p_22 &= (int)l_1334;
          if (*p_22) goto break_cont_1;
          tmp_24 = 1;
          tmp_21 = (int16_t)tmp_24;
          *l_1344 = tmp_21;
          goto return_label;
        }
        break_cont_1: g_583 = (uint16_t)((int)g_583 + 1);
      }
    }
    g_1019 --;
  }
  return_label: return;
}

static void func_42_slice_1(void)
{
  g_283 = (int16_t)0;
  while ((int)g_283 > -25) {
    g_153 = (uint64_t)9;
    goto break_cont_2;
    break_cont_2: g_258 = (int64_t)(-18);
    g_283 = (int16_t)((int)g_283 - 1);
  }
  return;
}

static void func_44_slice_1(void)
{
  uint64_t *l_399 = & g_153;
  (*l_399) ++;
  g_183 = 0;
  return;
}

static void func_50_slice_1(void)
{
  uint16_t *l_114 = & g_115;
  {
    uint16_t tmp_1;
    uint16_t tmp_0;
    tmp_1 = (uint16_t)g_73;
    tmp_0 = tmp_1;
    *l_114 = tmp_0;
  }
  g_73 = (uint8_t)0;
  goto break_cont_3;
  break_cont_3: ;
  return;
}

static void func_56_slice_1(void)
{
  int64_t const l_67;
  int16_t tmp_1;
  uint16_t tmp_0;
  uint8_t tmp;
  uint8_t *l_72 = & g_73;
  tmp_0 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(0x57CFL != (long)(
                                                           1UL != (unsigned long)l_67)));
  tmp_1 = safe_mul_func_int16_t_s_s_slice_1((int16_t)g_61[0],(int16_t)tmp_0);
  tmp = (uint8_t)(g_2[0][1][5] < ((l_67 | l_67) != (long)(0xD7FCCEA59F7C1AE2LL > (unsigned long long)(
                                                          (long)tmp_1 <= -9L))));
  *l_72 = tmp;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


