#include <stdio.h>
/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int realsmith_QxAd6_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

int INAT_PFX_MASK_realsmith_rpzw8 = 9;
int INAT_PFX_VEX3_realsmith_rpzw8 = 11;
__inline static int realsmith_rpzw8_slice_1(int attr) __attribute__((
__used__));
__inline static int realsmith_rpzw8_slice_1(int attr)
{
  int __retres;
  __retres = (attr & INAT_PFX_MASK_realsmith_rpzw8) == INAT_PFX_VEX3_realsmith_rpzw8;
  return __retres;
}

unsigned long realsmith_3L7lB_slice_1(char *dst, unsigned long siz)
{
  unsigned long __retres;
  unsigned long dlen;
  char *d = dst;
  unsigned long n = siz;
  while (1) {
    unsigned long tmp;
    tmp = n;
    n --;
    if (! (tmp != (unsigned long)0)) break;
    d ++;
  }
  dlen = (unsigned long)(d - dst);
  n = siz - dlen;
  if (n == (unsigned long)0) __retres = dlen + (unsigned long)1;
  return __retres;
}

unsigned long realsmith_proxy_Ob9Ok_slice_1(char p_0_Oyq4b,
                                            unsigned long p_2_1LX1q)
{
  char proxy_JjuW2[11] =
    {(char)7,
     (char)60,
     p_0_Oyq4b,
     p_0_Oyq4b,
     (char)75,
     p_0_Oyq4b,
     (char)8,
     p_0_Oyq4b,
     p_0_Oyq4b,
     p_0_Oyq4b,
     (char)10};
  unsigned long proxy_ret_m6ahz =
    realsmith_3L7lB_slice_1(proxy_JjuW2,p_2_1LX1q);
  return proxy_ret_m6ahz;
}

static int32_t safe_add_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (1) {
    if (si2 > 0) goto _LAND_0; else goto _LAND_0;
  }
  else {
    _LAND_0: ;
    tmp = si1 + si2;
  }
  return tmp;
}

static int32_t safe_sub_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (((si1 ^ si2) & (((si1 ^ ((si1 ^ si2) & ~ 2147483647)) - si2) ^ si2)) < 0) 
    tmp = si1;
  else tmp = si1 - si2;
  return tmp;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_3 = (int32_t)8L;
static int32_t g_25 = (int32_t)0x9ED890FCL;
static uint64_t g_36 = (uint64_t)0xD0881826FBD10CAALL;
static uint16_t g_85 = (uint16_t)0xA615L;
static int32_t g_99[1] = {(int32_t)0xF020A73BL};
static uint64_t g_101 = (uint64_t)0x157F02CAA0E68526LL;
static uint8_t g_111[7] =
  {(uint8_t)0x80L,
   (uint8_t)0x80L,
   (uint8_t)1UL,
   (uint8_t)0x80L,
   (uint8_t)0x80L,
   (uint8_t)1UL,
   (uint8_t)0x80L};
static uint16_t const g_142 = (uint16_t)65530UL;
static uint16_t const *g_141 = & g_142;
static int32_t *g_179 = g_99;
static int16_t g_207 = (int16_t)0x39DEL;
static int64_t g_208 = (int64_t)0xD5033BB9946DB040LL;
static uint16_t g_270 = (uint16_t)0xA0E6L;
static uint8_t g_275 = (uint8_t)0x94L;
static uint16_t *g_313 = & g_270;
static uint16_t g_409 = (uint16_t)65535UL;
static int32_t * const *g_463 = (int32_t * const *)(& g_179);
static int32_t * const **g_462 = & g_463;
static uint8_t g_501 = (uint8_t)0x7BL;
static uint8_t const g_774 = (uint8_t)7UL;
static int64_t *g_785 = & g_208;
static int64_t * const *g_784 = (int64_t * const *)(& g_785);
static int16_t g_854 = (int16_t)0xC4A5L;
static uint64_t *g_929[4][1] = {{& g_101}, {& g_101}, {& g_101}, {& g_101}};
static int64_t **g_962 = & g_785;
static uint8_t const *g_1115 = & g_774;
static uint8_t const ** const g_1114 = & g_1115;
static int32_t **g_1156 = & g_179;
static int32_t g_1870 = (int32_t)0xAC5182AAL;
static int32_t * const g_1869 = & g_1870;
static int32_t * const * const g_1868 = & g_1869;
static uint64_t **g_1890 = & g_929[1][0];
static void func_1_slice_1(void);

static uint32_t func_9_slice_1(uint32_t const p_11);

static void func_13_slice_1(void);

static void func_16_slice_1(uint8_t p_17);

static void func_30_slice_1(void);

static void func_1_slice_1(void)
{
  {
    uint8_t const l_1896[4];
    uint64_t l_1904;
    int32_t tmp_21;
    uint32_t tmp_20;
    int tmp_8;
    uint16_t l_19 = (uint16_t)0x5A40L;
    tmp_8 = realsmith_rpzw8_slice_1((int)l_1896[0] + -203);
    func_30_slice_1();
    func_16_slice_1((uint8_t)l_19);
    func_13_slice_1();
    tmp_20 = func_9_slice_1((uint32_t)((int)((uint8_t)((tmp_8 + (int)l_1896[0]) - 255)) + (int)l_1896[0]));
    tmp_21 = safe_sub_func_int32_t_s_s_slice_1((int32_t)3L,(int32_t)tmp_20);
    if (tmp_21) {
      g_270 = (uint16_t)0;
      goto return_label;
    }
    else 
      g_501 = (uint8_t)((long)((uint64_t *)0 == & l_1904) != 0xE66EL);
    goto return_label;
  }
  return_label: return;
}

static uint32_t func_9_slice_1(uint32_t const p_11)
{
  uint32_t __retres;
  unsigned long tmp;
  tmp = realsmith_proxy_Ob9Ok_slice_1((char)((int)((char)p_11) + 8),
                                      (unsigned long)p_11 + (unsigned long)(-247));
  __retres = (uint32_t)((tmp + (unsigned long)p_11) - (unsigned long)264) + p_11;
  return __retres;
}

static void func_13_slice_1(void)
{
  int tmp_47;
  uint64_t tmp_35;
  int32_t ** const *l_1417 = (int32_t ** const *)(& g_1156);
  int32_t ***l_1419 = & g_1156;
  int16_t *l_1782 = & g_207;
  int32_t const *l_1819 = (int32_t const *)(g_99);
  g_270 = (uint16_t)(-16);
  while ((int)g_270 >= 11) {
    {
      int tmp_2;
      g_409 = (uint16_t)(-30);
      while ((int)g_409 >= 45) {
        int32_t tmp_0;
        tmp_0 = safe_add_func_int32_t_s_s_slice_1((int32_t)g_409,6);
        g_409 = (uint16_t)tmp_0;
      }
      tmp_2 = realsmith_QxAd6_slice_1();
      func_16_slice_1((uint8_t)((int)((uint8_t)((tmp_2 + (int)*(*g_1114)) - 8)) + (int)*(*g_1114)));
    }
    g_270 = (uint16_t)((int)g_270 + 1);
  }
  if (*(*g_1156)) {
    int32_t ** const *tmp_12;
    int32_t ** const **l_1418 = & l_1417;
    int16_t *l_1441 = & g_207;
    tmp_12 = l_1417;
    *l_1418 = tmp_12;
    {
      int16_t l_1440 = (int16_t)0xA27EL;
      g_275 = (uint8_t)25;
      while ((int)g_275 >= 19) {
        {
          uint16_t tmp_9;
          uint16_t tmp_8;
          int tmp_7;
          {
            uint16_t tmp_3;
            tmp_3 = (uint16_t)((((long)*g_141 < -1L) >= *(*(*(*l_1418)))) <= (int)l_1440);
            *g_313 = tmp_3;
            tmp_7 = 1;
          }
          tmp_8 = safe_lshift_func_uint16_t_u_u_slice_1((uint16_t)tmp_7,
                                                        (unsigned int)0);
          tmp_9 = safe_mul_func_uint16_t_u_u_slice_1(tmp_8,
                                                     (uint16_t)*(*(*l_1419)));
          *l_1441 = (int16_t)((long)*l_1441 & (-10L | (long)tmp_9));
          *g_179 = (int32_t)(-1L);
        }
        g_275 = (uint8_t)((int)g_275 - 1);
      }
    }
  }
  else {
    int32_t tmp_13;
    int16_t tmp_15;
    int16_t l_1579 = (int16_t)4L;
    int16_t *l_1598 = & g_854;
    tmp_13 = (int32_t)l_1579;
    *(*(*l_1419)) = tmp_13;
    tmp_15 = (int16_t)g_85;
    *l_1598 = tmp_15;
    g_275 = (uint8_t)((int)g_275 - 1);
    func_16_slice_1(g_275);
  }
  *g_313 = (uint16_t)((int)*g_313 - 1);
  *(*g_784) = *(*g_962);
  tmp_47 = 0;
  *l_1782 = (int16_t)((int)*l_1782 | tmp_47);
  tmp_35 = (uint64_t)((int)*l_1782 < *l_1819);
  *(*g_1890) = tmp_35;
  return;
}

static void func_16_slice_1(uint8_t p_17)
{
  int32_t **l_1241 = & g_179;
  *l_1241 = *g_463;
  *(*g_1156) &= (int)p_17;
  return;
}

static void func_30_slice_1(void)
{
  g_36 = (uint64_t)0;
  *(*(*g_462)) = (int32_t)((long)*(*(*g_462)) ^ -1L);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_101: %lu\n", (unsigned long)g_101);
    printf("g_207: %d\n", (int)g_207);
    printf("g_270: %u\n", (unsigned int)g_270);
    printf("g_275: %u\n", (unsigned int)g_275);
    printf("g_36: %lu\n", (unsigned long)g_36);
    printf("g_208: %ld\n", (long)g_208);
    printf("g_255: 未在切片中定义\n");
    printf("g_409: %u\n", (unsigned int)g_409);
    printf("g_501: %u\n", (unsigned int)g_501);
    printf("g_854: %d\n", (int)g_854);

  __retres = 0;
  return __retres;
}


