/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int32_t safe_add_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (1) {
    if (si2 > 0) goto _LAND_0; else goto _LAND_0;
  }
  else {
    _LAND_0: ;
    tmp = si1 + si2;
  }
  return tmp;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static int32_t g_3 = (int32_t)8L;
static int32_t g_25 = (int32_t)0x9ED890FCL;
static uint64_t g_36 = (uint64_t)0xD0881826FBD10CAALL;
static uint16_t g_85 = (uint16_t)0xA615L;
static int32_t g_99[1] = {(int32_t)0xF020A73BL};
static uint64_t g_101 = (uint64_t)0x157F02CAA0E68526LL;
static int32_t *g_179 = g_99;
static int16_t g_207 = (int16_t)0x39DEL;
static int64_t g_208 = (int64_t)0xD5033BB9946DB040LL;
static uint16_t g_270 = (uint16_t)0xA0E6L;
static uint8_t g_275 = (uint8_t)0x94L;
static uint16_t g_409 = (uint16_t)65535UL;
static int32_t * const *g_463 = (int32_t * const *)(& g_179);
static int32_t * const **g_462 = & g_463;
static uint8_t const g_774 = (uint8_t)7UL;
static int64_t *g_785 = & g_208;
static int64_t * const *g_784 = (int64_t * const *)(& g_785);
static int16_t g_854 = (int16_t)0xC4A5L;
static uint64_t *g_929[4][1] = {{& g_101}, {& g_101}, {& g_101}, {& g_101}};
static int64_t **g_962 = & g_785;
static uint8_t const *g_1115 = & g_774;
static uint8_t const ** const g_1114 = & g_1115;
static int32_t **g_1156 = & g_179;
static uint64_t **g_1890 = & g_929[1][0];
static void func_1_slice_1(void);

static void func_13_slice_1(void);

static void func_16_slice_1(uint8_t p_17);

static void func_30_slice_1(void);

static void func_1_slice_1(void)
{
  {
    uint16_t l_19 = (uint16_t)0x5A40L;
    func_30_slice_1();
    func_16_slice_1((uint8_t)l_19);
    func_13_slice_1();
    g_270 = (uint16_t)0;
    goto return_label;
  }
  return_label: return;
}

static void func_13_slice_1(void)
{
  int tmp_34;
  uint64_t tmp_27;
  int32_t ***l_1419 = & g_1156;
  int16_t *l_1782 = & g_207;
  int32_t const *l_1819 = (int32_t const *)(g_99);
  g_270 = (uint16_t)(-16);
  while ((int)g_270 >= 11) {
    g_409 = (uint16_t)(-30);
    while ((int)g_409 >= 45) {
      int32_t tmp_0;
      tmp_0 = safe_add_func_int32_t_s_s_slice_1((int32_t)g_409,6);
      g_409 = (uint16_t)tmp_0;
    }
    func_16_slice_1(*(*g_1114));
    g_270 = (uint16_t)((int)g_270 + 1);
  }
  if (*(*g_1156)) {
    int16_t *l_1441 = & g_207;
    g_275 = (uint8_t)25;
    while ((int)g_275 >= 19) {
      {
        uint16_t tmp_7;
        uint16_t tmp_6;
        int tmp_5;
        tmp_5 = 1;
        tmp_6 = safe_lshift_func_uint16_t_u_u_slice_1((uint16_t)tmp_5,
                                                      (unsigned int)0);
        tmp_7 = safe_mul_func_uint16_t_u_u_slice_1(tmp_6,
                                                   (uint16_t)*(*(*l_1419)));
        *l_1441 = (int16_t)((long)*l_1441 & (-10L | (long)tmp_7));
        *g_179 = (int32_t)(-1L);
      }
      g_275 = (uint8_t)((int)g_275 - 1);
    }
  }
  else {
    int32_t tmp_11;
    int16_t tmp_13;
    int16_t l_1579 = (int16_t)4L;
    int16_t *l_1598 = & g_854;
    tmp_11 = (int32_t)l_1579;
    *(*(*l_1419)) = tmp_11;
    tmp_13 = (int16_t)g_85;
    *l_1598 = tmp_13;
    g_275 = (uint8_t)((int)g_275 - 1);
    func_16_slice_1(g_275);
  }
  *(*g_784) = *(*g_962);
  tmp_34 = 0;
  *l_1782 = (int16_t)((int)*l_1782 | tmp_34);
  tmp_27 = (uint64_t)((int)*l_1782 < *l_1819);
  *(*g_1890) = tmp_27;
  return;
}

static void func_16_slice_1(uint8_t p_17)
{
  int32_t **l_1241 = & g_179;
  *l_1241 = *g_463;
  *(*g_1156) &= (int)p_17;
  return;
}

static void func_30_slice_1(void)
{
  g_36 = (uint64_t)0;
  *(*(*g_462)) = (int32_t)((long)*(*(*g_462)) ^ -1L);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


