#include <stdio.h>
/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_add_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 + (int)si2);
  return __retres;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left)
{
  int8_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left; else tmp = (int)left;
  __retres = (int8_t)tmp;
  return __retres;
}

static int8_t safe_rshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left; else tmp = (int)left >> right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_sub_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 - (int)si2);
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_lshift_func_int16_t_s_u_slice_1(int16_t left,
                                                    unsigned int right)
{
  int16_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (int16_t)tmp;
  return __retres;
}

static int16_t safe_rshift_func_int16_t_s_u_slice_1(int16_t left,
                                                    unsigned int right)
{
  int16_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_add_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si1 > 0) goto _LAND_0;
  else {
    _LAND_0: ;
    tmp = si1 + si2;
  }
  return tmp;
}

static int32_t safe_sub_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static int32_t safe_div_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si2 == 0) tmp = si1; else tmp = si1 / si2;
  return tmp;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t safe_sub_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 - (int)ui2);
  return __retres;
}

static uint8_t safe_mul_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint8_t safe_lshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left << right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint16_t safe_mul_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((unsigned int)ui1 * (unsigned int)ui2);
  return __retres;
}

static uint16_t safe_div_func_uint16_t_u_u_slice_1(uint16_t ui1)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)ui1;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left,
                                                      int right)
{
  uint16_t __retres;
  int tmp;
  if (right < 0) tmp = (int)left; else tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint32_t safe_add_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 + ui2;
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static uint32_t safe_div_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t tmp;
  if (ui2 == (uint32_t)0) tmp = ui1; else tmp = ui1 / ui2;
  return tmp;
}

static int32_t g_18 = (int32_t)(-1L);
static uint16_t g_78[2][3] =
  {{(uint16_t)65530UL, (uint16_t)65530UL, (uint16_t)65530UL},
   {(uint16_t)65530UL, (uint16_t)65530UL, (uint16_t)65530UL}};
static uint16_t *g_81 = (uint16_t *)0;
static int32_t g_88 = (int32_t)7L;
static uint16_t g_97 = (uint16_t)0x2A41L;
static int8_t g_100 = (int8_t)0x14L;
static int32_t *g_147 = & g_18;
static uint32_t g_154[7] =
  {(uint32_t)9UL,
   (uint32_t)9UL,
   (uint32_t)9UL,
   (uint32_t)9UL,
   (uint32_t)9UL,
   (uint32_t)9UL,
   (uint32_t)9UL};
static int64_t g_161 = -9L;
static int64_t g_163 = 1L;
static int64_t *g_162 = & g_163;
static uint64_t g_239 = (uint64_t)0x560234739FD564FFLL;
static uint8_t g_254 = (uint8_t)0xB4L;
static uint32_t g_257[10] =
  {(uint32_t)4294967287UL,
   (uint32_t)0xB0BF3EEEL,
   (uint32_t)4294967287UL,
   (uint32_t)4294967292UL,
   (uint32_t)4294967292UL,
   (uint32_t)4294967287UL,
   (uint32_t)0xB0BF3EEEL,
   (uint32_t)4294967287UL,
   (uint32_t)4294967292UL,
   (uint32_t)4294967292UL};
static uint8_t g_261 = (uint8_t)0x8AL;
static uint64_t *g_302 = & g_239;
static uint8_t g_338 = (uint8_t)0x6CL;
static uint8_t *g_394 = & g_338;
static uint8_t **g_393 = & g_394;
static int16_t g_415 = (int16_t)(-4L);
static int16_t g_445 = (int16_t)(-1L);
static int64_t **g_456 = & g_162;
static int16_t *g_795 = & g_445;
static int16_t **g_794[6] =
  {& g_795, & g_795, & g_795, & g_795, & g_795, & g_795};
static int16_t ***g_793[3][7][5] =
  {{{& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0},
    {g_794, g_794, & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0},
    {g_794, g_794, & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0},
    {g_794, g_794, & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0}},
   {{g_794, g_794, & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0},
    {g_794, g_794, & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], (int16_t ***)0, (int16_t ***)0, (int16_t ***)0},
    {g_794, g_794, & g_794[2], & g_794[2], & g_794[4]},
    {(int16_t ***)0, & g_794[2], & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], & g_794[4], & g_794[2], & g_794[4]}},
   {{(int16_t ***)0, & g_794[2], & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], & g_794[4], & g_794[2], & g_794[4]},
    {(int16_t ***)0, & g_794[2], & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], & g_794[4], & g_794[2], & g_794[4]},
    {(int16_t ***)0, & g_794[2], & g_794[2], & g_794[2], & g_794[2]},
    {& g_794[2], & g_794[2], & g_794[4], & g_794[2], & g_794[4]},
    {(int16_t ***)0, & g_794[2], & g_794[2], & g_794[2], & g_794[2]}}};
static int16_t ****g_792[9] =
  {& g_793[0][2][1],
   & g_793[2][6][0],
   & g_793[0][2][1],
   & g_793[0][2][1],
   & g_793[2][6][0],
   & g_793[0][2][1],
   & g_793[0][2][1],
   & g_793[2][6][0],
   & g_793[0][2][1]};
static uint64_t **g_1021 = & g_302;
static uint64_t ***g_1020 = & g_1021;
static uint64_t ****g_1019 = & g_1020;
static uint32_t *g_1236 = & g_257[6];
static int16_t *****g_1251[6][2] =
  {{& g_792[8], & g_792[7]},
   {& g_792[8], & g_792[7]},
   {& g_792[8], & g_792[7]},
   {& g_792[8], & g_792[7]},
   {& g_792[8], & g_792[7]},
   {& g_792[8], & g_792[7]}};
static uint32_t **g_1277 = & g_1236;
static int8_t g_1290 = (int8_t)0xE9L;
static void func_1_slice_1(void);

static void func_24_slice_1(uint16_t p_25, int8_t p_27);

static uint8_t func_30_slice_1(void);

static int8_t func_33_slice_1(uint32_t p_35);

static int16_t func_38_slice_1(uint8_t p_40);

static void func_46_slice_1(void);

static void func_59_slice_1(void);

static void func_64_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t l_1159;
  int64_t const *l_1260;
  int8_t tmp_17;
  int tmp_16;
  int16_t tmp_11;
  uint8_t tmp_6;
  uint8_t tmp_5;
  int8_t tmp_4;
  int32_t tmp_3;
  uint64_t tmp;
  uint64_t l_13 = 1UL;
  int64_t l_542 = (int64_t)0x518280899225A493LL;
  int16_t *l_767 = & g_415;
  int32_t l_768[8] =
    {(int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL,
     (int32_t)0x9A31281CL};
  int8_t l_901 = (int8_t)(-1L);
  uint16_t *l_1170[1][5][4] =
    {{{& g_97, & g_97, & g_97, & g_97},
      {& g_97, & g_97, & g_97, & g_97},
      {& g_97, & g_97, & g_97, & g_97},
      {& g_97, & g_97, & g_97, & g_97},
      {& g_97, & g_97, & g_97, & g_97}}};
  int32_t * const *l_1180 = (int32_t * const *)(& g_147);
  int32_t * const **l_1179 = & l_1180;
  uint32_t l_1248 = (uint32_t)4294967293UL;
  int64_t const **l_1259 = & l_1260;
  func_46_slice_1();
  *l_767 = func_38_slice_1(*g_394);
  tmp_3 = safe_sub_func_int32_t_s_s_slice_1(l_768[1],g_18);
  tmp_4 = func_33_slice_1((uint32_t)tmp_3);
  tmp_5 = func_30_slice_1();
  tmp_6 = safe_lshift_func_uint8_t_u_u_slice_1(tmp_5,(unsigned int)l_768[1]);
  func_24_slice_1((uint16_t)tmp_6,(int8_t)l_542);
  tmp_11 = safe_sub_func_int16_t_s_s_slice_1((int16_t)(l_13 | (unsigned long)l_768[1]),
                                             (int16_t)l_901);
  tmp = (unsigned long)tmp_11 & l_13;
  *g_302 = tmp;
  tmp_16 = 0;
  tmp_17 = safe_mul_func_int8_t_s_s_slice_1((int8_t)tmp_16,(int8_t)l_13);
  *g_147 = (int32_t)tmp_17;
  if (1) goto _LOR;
  else {
    _LOR:
    {
      int32_t * const **tmp_77;
      int32_t * const ***l_1181 = & l_1179;
      uint32_t l_1254 = (uint32_t)4294967293UL;
      uint8_t const *l_1264 = (uint8_t const *)0;
      uint8_t ***l_1348 = & g_393;
      tmp_77 = l_1179;
      *l_1181 = tmp_77;
      {
        int32_t const l_1202;
        uint8_t tmp_30;
        uint8_t tmp_29;
        int16_t tmp_20;
        int32_t tmp_19;
        int16_t tmp_28;
        uint16_t tmp_27;
        int tmp_26;
        int tmp_23;
        int64_t tmp_21;
        int32_t tmp_18;
        int16_t *****l_1250 = & g_792[7];
        tmp_19 = safe_div_func_int32_t_s_s_slice_1((int32_t)(-7L),l_1202);
        tmp_20 = safe_rshift_func_int16_t_s_u_slice_1((int16_t)tmp_19,
                                                      (unsigned int)l_1202);
        tmp_23 = 0;
        tmp_21 = (int64_t)(~ tmp_23);
        *g_162 = tmp_21;
        tmp_26 = 0;
        tmp_27 = safe_div_func_uint16_t_u_u_slice_1((uint16_t)tmp_26);
        tmp_28 = safe_mul_func_int16_t_s_s_slice_1((int16_t)*(*(*(*l_1181))),
                                                   (int16_t)((long)tmp_27 > 0L));
        tmp_29 = safe_sub_func_uint8_t_u_u_slice_1((uint8_t)((long)(*(*(*l_1179)) <= (
                                                                    (int)tmp_20 < *(*(*(*l_1181))))) <= (
                                                             0x10509444L ^ (long)tmp_28)),
                                                   (uint8_t)0UL);
        tmp_30 = safe_mul_func_uint8_t_u_u_slice_1(tmp_29,*(*g_393));
        tmp_18 = (int32_t)tmp_30;
        *(*(*(*l_1181))) = tmp_18;
        {
          int8_t tmp_49;
          uint16_t tmp_47;
          uint16_t tmp_46;
          uint32_t tmp_45;
          int8_t tmp_48;
          int32_t tmp_44;
          int32_t l_1243[5] =
            {(int32_t)0xF0308A5AL,
             (int32_t)0xF0308A5AL,
             (int32_t)0xF0308A5AL,
             (int32_t)0xF0308A5AL,
             (int32_t)0xF0308A5AL};
          int32_t l_1247 = (int32_t)0x935BCCC7L;
          int16_t l_1293 = (int16_t)0x4FB3L;
          g_161 = (int64_t)0;
          while (g_161 >= (int64_t)0) {
            {
              int64_t const **l_1261 = & l_1260;
              uint32_t l_1266 = (uint32_t)0x4A226888L;
              l_1159 = 0;
              while (l_1159 >= 0) {
                {
                  int32_t *l_1229 = & g_18;
                  g_1236 = & g_257[6];
                  *g_162 |= (long)((*(*(*g_1020)) <= (uint64_t)(*g_456 == (int64_t *)0)) == (int)*g_394);
                  l_1247 |= g_1236 == (uint32_t *)0;
                  *l_1229 = (uint32_t)l_1247 == l_1248;
                }
                l_1159 --;
              }
              g_338 = (uint8_t)0;
              while ((int)g_338 <= 0) {
                if (*g_147) break;
                g_1251[0][0] = & g_792[7];
                *g_147 |= l_1250 != g_1251[0][0];
                g_338 = (uint8_t)((int)g_338 + 1);
              }
              g_261 = (uint8_t)0;
              while ((int)g_261 <= 0) {
                {
                  int8_t tmp_41;
                  uint16_t tmp_40;
                  uint16_t tmp_39;
                  uint8_t const *tmp_38;
                  int32_t tmp_37;
                  uint8_t tmp_36;
                  int16_t tmp_35;
                  uint8_t const **l_1265 = & l_1264;
                  int32_t *l_1271 = & g_88;
                  int32_t **l_1272 = & g_147;
                  tmp_38 = l_1264;
                  *l_1265 = tmp_38;
                  tmp_39 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)(
                                                                 (unsigned long)(
                                                                 ((void *)*g_393 == (void *)tmp_38) >= (
                                                                 (uint16_t *)0 != l_1170[0][3][0])) > 18446744073709551615UL),
                                                                 14);
                  tmp_37 = (int32_t)tmp_39;
                  *(*(*l_1179)) = tmp_37;
                  tmp_36 = (uint8_t)((uint64_t)tmp_37 == *(*(*(*g_1019))));
                  *g_394 = tmp_36;
                  tmp_40 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)(
                                                              l_1259 != l_1261),
                                                              (uint16_t)(
                                                              18446744073709551615UL != (unsigned long)(
                                                              (unsigned int)(
                                                              (long)tmp_36 >= 0x46L) | l_1266)));
                  tmp_41 = safe_rshift_func_int8_t_s_s_slice_1((int8_t)tmp_40,
                                                               (int)l_1254);
                  tmp_35 = (int16_t)tmp_41;
                  *l_767 = tmp_35;
                  *l_1272 = l_1271;
                }
                g_261 = (uint8_t)((int)g_261 + 1);
              }
            }
            g_161 -= (int64_t)1;
          }
          goto break_cont_1;
          break_cont_1:
          tmp_45 = safe_add_func_uint32_t_u_u_slice_1(*(*g_1277),
                                                      (uint32_t)((uint64_t *****)0 == & g_1019));
          tmp_46 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)tmp_45,
                                                      (uint16_t)l_1243[4]);
          tmp_47 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)l_1247,
                                                      (uint16_t)(((int)tmp_46 ^ (
                                                                  0x6306L > (long)g_1290)) < l_1247));
          tmp_48 = safe_add_func_int8_t_s_s_slice_1((int8_t)1L,
                                                    (int8_t)l_1293);
          l_1243[2] = (int)tmp_47 != (int)tmp_48;
          tmp_49 = safe_mul_func_int8_t_s_s_slice_1((int8_t)((unsigned long)l_1243[2] | 1UL),
                                                    (int8_t)*g_394);
          tmp_44 = (int32_t)tmp_49;
          *(*(*(*l_1181))) = tmp_44;
        }
        if (! *(*(*(*l_1181)))) {
          g_415 = (int16_t)15;
          g_163 = (int64_t)0;
          goto return_label;
        }
        g_254 = (uint8_t)4;
        goto break_cont_2;
      }
      break_cont_2: g_100 = (int8_t)2;
      while ((int)g_100 != -6) {
        uint32_t tmp_82;
        *(*(*l_1348)) = (uint8_t)((int)*(*(*l_1348)) + 1);
        tmp_82 = safe_sub_func_uint32_t_u_u_slice_1((uint32_t)g_100,
                                                    (uint32_t)8);
        g_100 = (int8_t)tmp_82;
      }
    }
  }
  return_label: return;
}

static void func_24_slice_1(uint16_t p_25, int8_t p_27)
{
  uint8_t tmp_11;
  int tmp_10;
  int32_t *l_902 = & g_88;
  int32_t **l_903 = & l_902;
  uint16_t **l_913[8] =
    {& g_81, & g_81, & g_81, & g_81, & g_81, & g_81, & g_81, & g_81};
  int8_t *l_926 = & g_100;
  *l_903 = l_902;
  goto break_cont_3;
  break_cont_3: *l_902 ^= (int)p_27;
  {
    int8_t tmp_1;
    int tmp_8;
    int16_t tmp_3;
    uint32_t tmp_7;
    int32_t tmp_6;
    int tmp_5;
    int8_t tmp_2;
    tmp_1 = safe_lshift_func_int8_t_s_s_slice_1((int8_t)1L);
    tmp_3 = safe_rshift_func_int16_t_s_u_slice_1((int16_t)*l_902,
                                                 (unsigned int)11);
    tmp_5 = 1;
    tmp_6 = safe_sub_func_int32_t_s_s_slice_1(tmp_5,(int32_t)p_25);
    tmp_7 = safe_div_func_uint32_t_u_u_slice_1((uint32_t)((long)tmp_6 < 0x89677E12L),
                                               (uint32_t)p_25);
    tmp_2 = (int8_t)((uint32_t)tmp_3 <= tmp_7);
    *l_926 = tmp_2;
    tmp_8 = 0;
    *g_795 = (int16_t)((int)*g_795 & (((int)tmp_1 == ((uint16_t **)0 == l_913[2])) ^ tmp_8));
    tmp_10 = 1;
  }
  tmp_11 = safe_add_func_uint8_t_u_u_slice_1((uint8_t)(tmp_10 >= *(*l_903)),
                                             (uint8_t)255UL);
  *(*l_903) = (int32_t)tmp_11;
  return;
}

static uint8_t func_30_slice_1(void)
{
  uint8_t __retres;
  uint8_t const *l_799;
  uint8_t const **tmp_36;
  uint8_t tmp_35;
  uint8_t **l_789 = & g_394;
  uint8_t const **l_798 = & l_799;
  tmp_36 = l_798;
  tmp_35 = (uint8_t)((void *)l_789 != (void *)tmp_36);
  *(*g_393) = tmp_35;
  g_261 = (uint8_t)((unsigned long)g_261 | 1UL);
  g_161 = (int64_t)8;
  while (g_161 >= (int64_t)(-1)) {
    int32_t tmp;
    g_415 = (int16_t)1;
    while ((int)g_415 >= 0) g_415 = (int16_t)((int)g_415 - 1);
    tmp = safe_sub_func_int32_t_s_s_slice_1((int32_t)g_161,6);
    g_161 = (int64_t)tmp;
  }
  __retres = *g_394;
  return __retres;
}

static int8_t func_33_slice_1(uint32_t p_35)
{
  int8_t __retres;
  __retres = (int8_t)p_35;
  return __retres;
}

static int16_t func_38_slice_1(uint8_t p_40)
{
  int16_t __retres;
  uint16_t tmp_5;
  int tmp_4;
  int16_t tmp;
  int8_t l_545 = (int8_t)0x02L;
  int16_t *l_550 = & g_445;
  int32_t *l_563 = & g_88;
  tmp = safe_lshift_func_int16_t_s_u_slice_1((int16_t)l_545,(unsigned int)11);
  *l_550 = (int16_t)((int)*l_550 | (int)tmp);
  tmp_4 = 0;
  g_415 = safe_mul_func_int16_t_s_s_slice_1((int16_t)((long)(tmp_4 > (int)p_40) != 0x55ACL),
                                            (int16_t)(-1L));
  tmp_5 = safe_mul_func_uint16_t_u_u_slice_1((uint16_t)g_154[2],
                                             (uint16_t)g_415);
  *l_563 = (int32_t)tmp_5;
  goto break_cont_4;
  break_cont_4: __retres = (int16_t)*l_563;
  return __retres;
}

static void func_46_slice_1(void)
{
  func_64_slice_1();
  func_59_slice_1();
  return;
}

static void func_59_slice_1(void)
{
  uint8_t **l_511 = & g_394;
  g_393 = l_511;
  g_254 = (uint8_t)0;
  while ((int)g_254 <= 16) {
    int32_t tmp_5;
    tmp_5 = safe_add_func_int32_t_s_s_slice_1((int32_t)g_254,5);
    g_254 = (uint8_t)tmp_5;
  }
  return;
}

static void func_64_slice_1(void)
{
  g_97 = (uint16_t)0;
  while ((int)g_97 <= 0) g_97 = (uint16_t)((int)g_97 + 1);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_88: %d\n", g_88);
    printf("g_163: %ld\n", (long)g_163);
    printf("g_254: %u\n", (unsigned int)g_254);
    printf("g_445: %d\n", (int)g_445);
    printf("g_97: %u\n", (unsigned int)g_97);
    printf("g_100: %d\n", (int)g_100);
    printf("g_415: %d\n", (int)g_415);
    printf("g_239: %lu\n", (unsigned long)g_239);
    printf("g_261: %u\n", (unsigned int)g_261);
    printf("g_338: %u\n", (unsigned int)g_338);

  __retres = 0;
  return __retres;
}


