/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int8_t safe_mod_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static int16_t safe_mul_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_mod_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  int tmp;
  if ((int)si2 == 0) tmp = (int)si1; else tmp = (int)si1 % (int)si2;
  __retres = (int16_t)tmp;
  return __retres;
}

static int32_t safe_mod_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  if (si2 == 0) tmp = si1; else tmp = si1 % si2;
  return tmp;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint16_t safe_lshift_func_uint16_t_u_s_slice_1(uint16_t left,
                                                      int right)
{
  uint16_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint64_t safe_div_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  tmp = ui1 / ui2;
  return tmp;
}

static uint8_t g_4 = (uint8_t)0x87L;
static int32_t g_9[2][5][2] =
  {{{(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L},
    {(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L}},
   {{(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L},
    {(int32_t)0L, (int32_t)1L},
    {(int32_t)0L, (int32_t)0L},
    {(int32_t)1L, (int32_t)0L}}};
static uint16_t g_60 = (uint16_t)1UL;
static int32_t g_77 = (int32_t)0x48991CD3L;
static int32_t g_78 = (int32_t)(-1L);
static int8_t g_90 = (int8_t)0x97L;
static int16_t g_104 = (int16_t)(-1L);
static uint64_t g_118 = 18446744073709551613UL;
static uint8_t g_132 = (uint8_t)4UL;
static int64_t g_134 = -2L;
static int8_t g_151 = (int8_t)0x66L;
static int64_t g_170[1][4] =
  {{(int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL,
    (int64_t)0xEB764D41390277B5LL}};
static int8_t g_171 = (int8_t)0x1DL;
static uint16_t g_199 = (uint16_t)7UL;
static int8_t *g_252 = & g_171;
static uint8_t g_299[4] =
  {(uint8_t)0x25L, (uint8_t)0x25L, (uint8_t)0x25L, (uint8_t)0x25L};
static int8_t g_309[3] = {(int8_t)0L, (int8_t)0L, (int8_t)0L};
static uint8_t *g_703[1][2] = {{& g_4, & g_4}};
static uint8_t **g_702 = & g_703[0][1];
static int32_t *g_877 = & g_78;
static uint8_t const g_2311 = (uint8_t)0xF8L;
static void func_1_slice_1(void);

static void func_10_slice_1(void);

static void func_14_slice_1(void);

static void func_20_slice_1(void);

static void func_31_slice_1(void);

static void func_37_slice_1(uint8_t p_38, uint8_t *p_39);

static void func_44_slice_1(uint16_t p_45, uint8_t p_46, int32_t *p_47);

static uint16_t func_49_slice_1(void);

static void func_1_slice_1(void)
{
  uint8_t tmp;
  int8_t tmp_1;
  int32_t *l_8 = & g_9[0][4][0];
  tmp = g_4;
  *l_8 = (long)tmp != 0x25L;
  tmp_1 = safe_mod_func_int8_t_s_s_slice_1((int8_t)*l_8,(int8_t)*l_8);
  func_37_slice_1((uint8_t)tmp_1,& g_4);
  func_31_slice_1();
  func_20_slice_1();
  func_14_slice_1();
  func_10_slice_1();
  return;
}

static void func_10_slice_1(void)
{
  g_132 = (uint8_t)24;
  return;
}

static void func_14_slice_1(void)
{
  int16_t tmp_7;
  int tmp_6;
  int32_t l_2327 = (int32_t)0L;
  tmp_6 = 1;
  tmp_7 = safe_mod_func_int16_t_s_s_slice_1((int16_t)tmp_6,(int16_t)l_2327);
  *g_877 &= (int)tmp_7;
  return;
}

static void func_20_slice_1(void)
{
  uint8_t tmp_2;
  int tmp_11;
  int tmp_10;
  int32_t tmp_6;
  uint8_t *l_2034 = & g_4;
  int32_t l_2035 = (int32_t)(-4L);
  tmp_2 = (uint8_t)246UL;
  *l_2034 = tmp_2;
  tmp_10 = 1;
  g_104 = (int16_t)((int)g_104 | tmp_10);
  tmp_11 = 1;
  tmp_6 = tmp_11 < l_2035;
  *g_877 = tmp_6;
  g_199 = (uint16_t)0;
  return;
}

static void func_31_slice_1(void)
{
  int16_t tmp_19;
  uint16_t tmp_18;
  int tmp_17;
  int64_t tmp_0;
  int64_t *l_554 = & g_134;
  tmp_17 = 1;
  tmp_18 = safe_lshift_func_uint16_t_u_s_slice_1((uint16_t)tmp_17,12);
  tmp_19 = safe_mul_func_int16_t_s_s_slice_1((int16_t)tmp_18,
                                             (int16_t)0x2F9CL);
  tmp_0 = (int64_t)tmp_19;
  *l_554 = tmp_0;
  return;
}

static void func_37_slice_1(uint8_t p_38, uint8_t *p_39)
{
  g_4 = (uint8_t)0;
  {
    uint16_t tmp_9;
    int32_t tmp;
    int8_t l_70 = (int8_t)1L;
    int32_t *l_76 = & g_77;
    tmp = (int)p_38 > ((int)l_70 < g_9[0][2][0]);
    g_78 &= tmp;
    tmp_9 = func_49_slice_1();
    func_44_slice_1(tmp_9,*p_39,& g_9[0][4][0]);
    {
      uint16_t l_258[3][4] =
        {{(uint16_t)0x96D9L,
          (uint16_t)0x6E73L,
          (uint16_t)0x6E73L,
          (uint16_t)0x96D9L},
         {(uint16_t)0x6E73L,
          (uint16_t)0x96D9L,
          (uint16_t)0x6E73L,
          (uint16_t)0x6E73L},
         {(uint16_t)0x96D9L,
          (uint16_t)0x96D9L,
          (uint16_t)65526UL,
          (uint16_t)0x96D9L}};
      {
        int32_t tmp_12;
        tmp_12 = (int32_t)l_258[2][3];
        *l_76 = tmp_12;
      }
      goto return_label;
    }
  }
  return_label: return;
}

static void func_44_slice_1(uint16_t p_45, uint8_t p_46, int32_t *p_47)
{
  int32_t *l_84 = & g_78;
  int32_t *l_85 = & g_78;
  int16_t *l_123 = & g_104;
  g_60 = (uint16_t)0;
  while ((int)g_60 != 10) {
    {
      int16_t tmp_2;
      int16_t *l_103 = & g_104;
      tmp_2 = (int16_t)(0xE5F641D3L ^ (long)p_46);
      *l_103 = tmp_2;
    }
    g_60 = (uint16_t)((int)g_60 + 1);
  }
  g_90 = (int8_t)(-24);
  while ((int)g_90 <= 9) {
    {
      int8_t tmp_44;
      uint8_t tmp_41;
      uint64_t *l_117 = & g_118;
      int32_t l_130 = (int32_t)0L;
      uint8_t *l_131 = & g_132;
      *l_117 = (uint64_t)((unsigned long long)*l_117 & (unsigned long long)0x23D7FF4CBEB01B51LL);
      tmp_44 = safe_sub_func_int8_t_s_s_slice_1((int8_t)(-1L),(int8_t)g_4);
      tmp_41 = (uint8_t)tmp_44;
      *l_131 = tmp_41;
      {
        int tmp_37;
        int tmp_32;
        int8_t tmp_31;
        int32_t tmp_29;
        int8_t *l_150 = & g_151;
        tmp_32 = 1;
        tmp_31 = (int8_t)((int)p_45 ^ ((unsigned long)tmp_32 < 4294967291UL));
        *l_150 = tmp_31;
        tmp_37 = 0;
        tmp_29 = tmp_37;
        *l_84 = tmp_29;
        {
          int16_t tmp_16;
          int16_t tmp_15;
          uint64_t tmp_11;
          uint8_t tmp_14;
          int32_t tmp_13;
          int64_t tmp_12;
          int64_t tmp_10;
          g_134 = (int64_t)0xE406C9851B6DC083LL;
          tmp_11 = safe_div_func_uint64_t_u_u_slice_1((uint64_t)g_90,
                                                      (uint64_t)g_134);
          tmp_12 = safe_sub_func_int64_t_s_s_slice_1(-1L,(int64_t)l_130);
          tmp_13 = safe_mod_func_int32_t_s_s_slice_1((int32_t)tmp_12,
                                                     (int32_t)p_46);
          tmp_14 = safe_add_func_uint8_t_u_u_slice_1((uint8_t)0xABL,
                                                     (uint8_t)tmp_13);
          tmp_15 = safe_mul_func_int16_t_s_s_slice_1((int16_t)p_46,
                                                     (int16_t)(0x81E3L > (long)(
                                                               (tmp_11 > (uint64_t)tmp_14) < (int)g_90)));
          *l_85 |= (int)tmp_15;
          tmp_16 = safe_mul_func_int16_t_s_s_slice_1((int16_t)g_132,
                                                     (int16_t)(*l_85 == g_9[0][2][0]));
          tmp_10 = (int64_t)tmp_16;
          g_171 = (int8_t)tmp_10;
          *l_123 = (int16_t)((int)((int16_t)g_171));
          *l_150 = (int8_t)((int)*l_150 & ((int32_t **)0 != & p_47));
        }
      }
    }
    g_90 = (int8_t)((int)g_90 + 1);
  }
  return;
}

static uint16_t func_49_slice_1(void)
{
  uint16_t __retres;
  int32_t const *l_79 = (int32_t const *)(& g_78);
  l_79 = l_79;
  __retres = (uint16_t)*l_79;
  return __retres;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_104: %d\n", (int)g_104);
  __retres = 0;
  return __retres;
}


