#include <stdio.h>
/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int realsmith_RRZSC_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_JpXeW_slice_1(char const *p, int const defval)
{
  int __retres;
  char const *endp = p;
  while (*endp) endp ++;
  if ((int)*endp != 0) {
    __retres = defval;
    goto return_label;
  }
  __retres = 1;
  return_label: return __retres;
}

int realsmith_proxy_WwBhM_slice_1(char p_0_Hd7u2, int p_2_0rxK6)
{
  char proxy_C9inQ[20] =
    {p_0_Hd7u2,
     (char)18,
     (char)29,
     (char)4,
     p_0_Hd7u2,
     (char)0,
     (char)87,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     p_0_Hd7u2,
     (char)28,
     p_0_Hd7u2,
     p_0_Hd7u2,
     (char)44,
     (char)48};
  int proxy_ret_9RVvp =
    realsmith_JpXeW_slice_1((char const *)(proxy_C9inQ),p_2_0rxK6);
  return proxy_ret_9RVvp;
}

static int realsmith_TqPwt_slice_1(void) __attribute__((__used__));
static int realsmith_TqPwt_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_eQYBZ_slice_1(char p_0_J4gkD)
{
  char proxy_fIkn1[11] =
    {(char)23,
     (char)86,
     (char)77,
     p_0_J4gkD,
     (char)34,
     p_0_J4gkD,
     (char)39,
     (char)58,
     p_0_J4gkD,
     p_0_J4gkD,
     p_0_J4gkD};
  int proxy_ret_B7g2i = realsmith_TqPwt_slice_1();
  return proxy_ret_B7g2i;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint16_t safe_rshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int32_t g_11 = (int32_t)0xB0E1B1B5L;
static int32_t g_34 = (int32_t)0x9EED08E1L;
static uint64_t g_39 = 6UL;
static int32_t **g_98 = (int32_t **)0;
static int32_t g_141 = (int32_t)(-10L);
static int64_t g_193 = 0L;
static int32_t *g_223 = & g_141;
static int32_t ***g_595 = & g_98;
static int32_t ****g_594 = & g_595;
static int16_t g_611 = (int16_t)5L;
static int16_t *g_610 = & g_611;
static int16_t **g_609 = & g_610;
static uint32_t g_663 = (uint32_t)4294967293UL;
static int64_t g_732 = (int64_t)0x34649ABFB8EA4430LL;
static int32_t *****g_1013 = & g_594;
static int64_t *g_1990 = & g_732;
static int64_t **g_1989 = & g_1990;
static int16_t g_2065 = (int16_t)0xB934L;
static uint32_t *g_2066 = & g_663;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  uint32_t l_2292;
  int32_t l_2293;
  int32_t const l_2295;
  uint32_t tmp_16;
  int8_t tmp_15;
  int8_t tmp_14;
  int tmp;
  int64_t tmp_13;
  int tmp_12;
  int tmp_30;
  uint16_t tmp_26;
  int16_t tmp_25;
  int tmp_31;
  int64_t tmp_24;
  uint32_t l_2[9] =
    {(uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL};
  int32_t l_12 = (int32_t)0x51554671L;
  int32_t *l_36 = & g_34;
  int32_t **l_35 = & l_36;
  int32_t l_2294 = (int32_t)1L;
  uint64_t l_2296 = (uint64_t)0x7C816288D38B644DLL;
  int32_t l_2308 = (int32_t)0x2D6ED1DBL;
  tmp = realsmith_proxy_eQYBZ_slice_1((char)((int)((char)l_2295) + -5));
  l_12 = (int32_t)((long)l_12 ^ -1L);
  tmp_12 = 1;
  l_2292 = (uint32_t)tmp_12;
  tmp_13 = safe_sub_func_int64_t_s_s_slice_1(-1L,(int64_t)l_2292);
  l_2293 = (int32_t)tmp_13;
  tmp_14 = safe_mul_func_int8_t_s_s_slice_1((int8_t)((long)(l_12 > (l_2293 != l_2294)) != 0x290D0EAFL),
                                            (int8_t)(((tmp + l_2295) - 2) + l_2295));
  tmp_15 = safe_lshift_func_int8_t_s_s_slice_1(tmp_14,5);
  tmp_16 = safe_sub_func_uint32_t_u_u_slice_1((uint32_t)((long)((long)tmp_15 < 0x572AL) ^ g_193),
                                              (uint32_t)l_2296);
  *g_223 = l_2[0] == (uint32_t)(0x8462751CL <= (long)tmp_16);
  tmp_26 = safe_rshift_func_uint16_t_u_u_slice_1((uint16_t)((*g_1013 != (int32_t ****)0) == l_2308),
                                                 (unsigned int)11);
  tmp_25 = (int16_t)((4L ^ (long)*g_610) >= (long)tmp_26);
  *(*g_609) = tmp_25;
  tmp_30 = 1;
  tmp_31 = realsmith_proxy_WwBhM_slice_1((char)((int)((char)g_11) + 45),
                                         (int)g_193 + 92);
  tmp_24 = (int64_t)(1 != ((uint32_t)tmp_30 <= (uint32_t)((((tmp_31 + (int)*g_2066) + g_11) + (int)g_193) - -1327386189) + *g_2066));
  *(*g_1989) = tmp_24;
  {
    int32_t * const l_2338;
    int tmp_23;
    uint8_t l_2334 = (uint8_t)1UL;
    tmp_23 = realsmith_RRZSC_slice_1();
    *(*l_35) |= (((((tmp_23 + *l_2338) + (int)l_2334) + l_2308) + (int)*g_2066) - 762237405) + *l_2338;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_232: 未在切片中定义\n");
    printf("g_34: %d\n", g_34);
    printf("g_186: 未在切片中定义\n");
    printf("g_11: %d\n", g_11);
    printf("g_85: 未在切片中定义\n");
    printf("g_141: %d\n", g_141);
    printf("g_527: 未在切片中定义\n");
    printf("g_611: %d\n", (int)g_611);
    printf("g_732: %ld\n", (long)g_732);
    printf("g_736: 未在切片中定义\n");
    printf("g_39: %lu\n", (unsigned long)g_39);
    printf("g_192: 未在切片中定义\n");
    printf("g_663: %lu\n", (unsigned long)g_663);

  __retres = 0;
  return __retres;
}


