/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int32_t g_34 = (int32_t)0x9EED08E1L;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t *l_36 = & g_34;
  int32_t **l_35 = & l_36;
  {
    int32_t * const l_2338;
    *(*l_35) |= *l_2338;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_34: %d\n", g_34);
  __retres = 0;
  return __retres;
}


