/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int8_t safe_lshift_func_int8_t_s_s_slice_1(int8_t left, int right)
{
  int8_t __retres;
  int tmp;
  tmp = (int)left << right;
  __retres = (int8_t)tmp;
  return __retres;
}

static int64_t safe_sub_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static uint16_t safe_rshift_func_uint16_t_u_u_slice_1(uint16_t left,
                                                      unsigned int right)
{
  uint16_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint16_t)tmp;
  return __retres;
}

static uint32_t safe_sub_func_uint32_t_u_u_slice_1(uint32_t ui1, uint32_t ui2)
{
  uint32_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int32_t g_11 = (int32_t)0xB0E1B1B5L;
static int32_t g_34 = (int32_t)0x9EED08E1L;
static uint64_t g_39 = 6UL;
static int32_t **g_98 = (int32_t **)0;
static int32_t g_141 = (int32_t)(-10L);
static int64_t g_193 = 0L;
static int32_t *g_223 = & g_141;
static int32_t ***g_595 = & g_98;
static int32_t ****g_594 = & g_595;
static int16_t g_611 = (int16_t)5L;
static int16_t *g_610 = & g_611;
static int16_t **g_609 = & g_610;
static uint32_t g_663 = (uint32_t)4294967293UL;
static int64_t g_732 = (int64_t)0x34649ABFB8EA4430LL;
static int32_t *****g_1013 = & g_594;
static int64_t *g_1990 = & g_732;
static int64_t **g_1989 = & g_1990;
static int16_t g_2065 = (int16_t)0xB934L;
static uint32_t *g_2066 = & g_663;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  uint32_t l_2292;
  int32_t l_2293;
  int32_t const l_2295;
  uint32_t tmp_11;
  int8_t tmp_10;
  int8_t tmp_9;
  int64_t tmp_8;
  int tmp_7;
  int tmp_22;
  uint16_t tmp_18;
  int16_t tmp_17;
  int64_t tmp_16;
  uint32_t l_2[9] =
    {(uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL,
     (uint32_t)4294967290UL};
  int32_t l_12 = (int32_t)0x51554671L;
  int32_t *l_36 = & g_34;
  int32_t **l_35 = & l_36;
  int32_t l_2294 = (int32_t)1L;
  uint64_t l_2296 = (uint64_t)0x7C816288D38B644DLL;
  int32_t l_2308 = (int32_t)0x2D6ED1DBL;
  l_12 = (int32_t)((long)l_12 ^ -1L);
  tmp_7 = 1;
  l_2292 = (uint32_t)tmp_7;
  tmp_8 = safe_sub_func_int64_t_s_s_slice_1(-1L,(int64_t)l_2292);
  l_2293 = (int32_t)tmp_8;
  tmp_9 = safe_mul_func_int8_t_s_s_slice_1((int8_t)((long)(l_12 > (l_2293 != l_2294)) != 0x290D0EAFL),
                                           (int8_t)l_2295);
  tmp_10 = safe_lshift_func_int8_t_s_s_slice_1(tmp_9,5);
  tmp_11 = safe_sub_func_uint32_t_u_u_slice_1((uint32_t)((long)((long)tmp_10 < 0x572AL) ^ g_193),
                                              (uint32_t)l_2296);
  *g_223 = l_2[0] == (uint32_t)(0x8462751CL <= (long)tmp_11);
  tmp_18 = safe_rshift_func_uint16_t_u_u_slice_1((uint16_t)((*g_1013 != (int32_t ****)0) == l_2308),
                                                 (unsigned int)11);
  tmp_17 = (int16_t)((4L ^ (long)*g_610) >= (long)tmp_18);
  *(*g_609) = tmp_17;
  tmp_22 = 1;
  tmp_16 = (int64_t)(1 != ((uint32_t)tmp_22 <= *g_2066));
  *(*g_1989) = tmp_16;
  {
    int32_t * const l_2338;
    *(*l_35) |= *l_2338;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


