/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
typedef int (*func_ptr_t)(int , int *);
int add_func(int x, int *p);

int add_func_slice_1(int x, int *p)
{
  int __retres;
  *p += x;
  __retres = *p;
  return __retres;
}

int mul_func(int x, int *p);

int mul_func_slice_1(int x, int *p)
{
  int __retres;
  *p *= x;
  __retres = *p;
  return __retres;
}

func_ptr_t get_func_slice_1(int choice)
{
  func_ptr_t __retres;
  if (choice == 1) {
    __retres = & add_func_slice_1;
    goto return_label;
  }
  __retres = & mul_func_slice_1;
  return_label: return __retres;
}

int main(void)
{
  int tmp_0;
  int tmp_1;
  int val = 10;
  int choice = 1;
  int (*fp)(int , int *) = get_func_slice_1(choice);
  tmp_0 = add_func_slice_1(5,& val);
  int result1 = tmp_0;
  choice = 2;
  fp = get_func_slice_1(choice);
  tmp_1 = mul_func_slice_1(3,& val);
  int result2 = tmp_1;
  int result = (result1 + result2) + val;
  return result;
}


