/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int32_t g_3 = (int32_t)0x198A8F93L;
static int32_t g_13[2][9][7] =
  {{{(int32_t)(-5L),
     (int32_t)1L,
     (int32_t)(-8L),
     (int32_t)(-8L),
     (int32_t)1L,
     (int32_t)(-5L),
     (int32_t)1L},
    {(int32_t)0x54A20A29L,
     (int32_t)(-1L),
     (int32_t)(-1L),
     (int32_t)0x54A20A29L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)0x54A20A29L,
     (int32_t)(-1L)},
    {(int32_t)1L,
     (int32_t)1L,
     (int32_t)(-5L),
     (int32_t)(-8L),
     (int32_t)(-5L),
     (int32_t)1L,
     (int32_t)1L},
    {(int32_t)1L,
     (int32_t)(-1L),
     (int32_t)0xDDA37BB0L,
     (int32_t)(-1L),
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)(-1L)},
    {(int32_t)7L,
     (int32_t)1L,
     (int32_t)7L,
     (int32_t)(-5L),
     (int32_t)(-5L),
     (int32_t)7L,
     (int32_t)1L},
    {(int32_t)(-1L),
     (int32_t)0xB3A3FC4BL,
     (int32_t)0xDDA37BB0L,
     (int32_t)0xDDA37BB0L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)(-1L),
     (int32_t)0xB3A3FC4BL},
    {(int32_t)7L,
     (int32_t)(-5L),
     (int32_t)(-5L),
     (int32_t)7L,
     (int32_t)1L,
     (int32_t)(-8L),
     (int32_t)7L},
    {(int32_t)(-1L),
     (int32_t)(-1L),
     (int32_t)0x54A20A29L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)0x54A20A29L,
     (int32_t)(-1L),
     (int32_t)(-1L)},
    {(int32_t)(-5L),
     (int32_t)7L,
     (int32_t)1L,
     (int32_t)7L,
     (int32_t)(-5L),
     (int32_t)(-5L),
     (int32_t)7L}},
   {{(int32_t)0xDDA37BB0L,
     (int32_t)1L,
     (int32_t)0xDDA37BB0L,
     (int32_t)0x54A20A29L,
     (int32_t)0x54A20A29L,
     (int32_t)0xDDA37BB0L,
     (int32_t)1L},
    {(int32_t)7L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)1L,
     (int32_t)7L,
     (int32_t)1L},
    {(int32_t)0xDDA37BB0L,
     (int32_t)0x54A20A29L,
     (int32_t)0x54A20A29L,
     (int32_t)0xDDA37BB0L,
     (int32_t)1L,
     (int32_t)0xDDA37BB0L,
     (int32_t)0x54A20A29L},
    {(int32_t)(-5L),
     (int32_t)(-5L),
     (int32_t)7L,
     (int32_t)1L,
     (int32_t)7L,
     (int32_t)(-5L),
     (int32_t)(-5L)},
    {(int32_t)(-1L),
     (int32_t)0x54A20A29L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)0x54A20A29L,
     (int32_t)(-1L),
     (int32_t)(-1L),
     (int32_t)0x54A20A29L},
    {(int32_t)(-8L),
     (int32_t)1L,
     (int32_t)(-8L),
     (int32_t)7L,
     (int32_t)7L,
     (int32_t)(-8L),
     (int32_t)1L},
    {(int32_t)0x54A20A29L,
     (int32_t)1L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)0xB3A3FC4BL,
     (int32_t)1L,
     (int32_t)0x54A20A29L,
     (int32_t)1L},
    {(int32_t)(-8L),
     (int32_t)7L,
     (int32_t)7L,
     (int32_t)(-8L),
     (int32_t)1L,
     (int32_t)(-8L),
     (int32_t)7L},
    {(int32_t)(-1L),
     (int32_t)(-1L),
     (int32_t)0x54A20A29L,
     (int32_t)0xB3A3FC4BL,
     (int32_t)0x54A20A29L,
     (int32_t)(-1L),
     (int32_t)(-1L)}}};
static uint16_t g_25 = (uint16_t)0UL;
static uint8_t g_45 = (uint8_t)7UL;
static uint8_t * const g_44[7] =
  {& g_45, (uint8_t *)0, & g_45, & g_45, (uint8_t *)0, & g_45, & g_45};
static int16_t g_103 = (int16_t)0xD576L;
static uint16_t g_172 = (uint16_t)1UL;
static uint32_t g_229 = (uint32_t)0UL;
static uint32_t g_235 = (uint32_t)0x60826268L;
static int64_t const g_240 = -8L;
static int16_t g_381 = (int16_t)0xC6E3L;
static int16_t *g_380 = & g_381;
static uint8_t *g_382 = (uint8_t *)0;
static int64_t g_386 = (int64_t)0xF6B5BFCAD32F07F1LL;
static int64_t *g_385 = & g_386;
static void func_1_slice_1(void);

static void func_28_slice_1(void);

static void func_37_slice_1(void);

static void func_66_slice_1(uint8_t p_67, int32_t p_68);

static void func_74_slice_1(int64_t p_76);

static void func_1_slice_1(void)
{
  int32_t *l_2 = & g_3;
  int32_t *l_6 = & g_3;
  int16_t *l_306 = & g_103;
  g_25 = (uint16_t)((int)g_25 & g_13[0][1][2]);
  g_3 = g_13[0][2][0] & g_13[1][5][2];
  {
    int16_t tmp_3;
    func_66_slice_1((uint8_t)*l_2,*l_6);
    tmp_3 = (int16_t)(-1L);
    *l_306 = tmp_3;
  }
  func_37_slice_1();
  func_28_slice_1();
  return;
}

static void func_28_slice_1(void)
{
  g_172 = (uint16_t)(-1);
  return;
}

static void func_37_slice_1(void)
{
  g_229 = (uint32_t)15;
  return;
}

static void func_66_slice_1(uint8_t p_67, int32_t p_68)
{
  p_67 = (uint8_t)0;
  while ((int)p_67 != 30) {
    func_74_slice_1((int64_t)p_68);
    p_67 = (uint8_t)((int)p_67 + 1);
  }
  return;
}

static void func_74_slice_1(int64_t p_76)
{
  int32_t l_250;
  l_250 = (int32_t)p_76;
  g_235 &= (unsigned int)l_250;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


