/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int realsmith_RRZSC_slice_1(void)
{
  int __retres;
  printf("g_34: %d\n", g_34);
  __retres = 0;
  return __retres;
}

static int32_t g_34 = (int32_t)0x9EED08E1L;
static uint32_t g_663 = (uint32_t)4294967293UL;
static uint32_t *g_2066 = & g_663;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t *l_36 = & g_34;
  int32_t **l_35 = & l_36;
  int32_t l_2308 = (int32_t)0x2D6ED1DBL;
  {
    int32_t * const l_2338 = & g_1320;
    int tmp_23;
    uint8_t l_2334 = (uint8_t)1UL;
    tmp_23 = realsmith_RRZSC_slice_1();
    *(*l_35) |= (((((tmp_23 + *l_2338) + (int)l_2334) + l_2308) + (int)*g_2066) - 762237405) + *l_2338;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_34: %d\n", g_34);
  __retres = 0;
  return __retres;
}


