/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_add_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 + (int)si2);
  return __retres;
}

static int16_t safe_rshift_func_int16_t_s_u_slice_1(int16_t left)
{
  int16_t __retres;
  int tmp;
  tmp = (int)left;
  __retres = (int16_t)tmp;
  return __retres;
}

static uint64_t safe_sub_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t __retres;
  __retres = ui1 - ui2;
  return __retres;
}

static int realsmith_lIpsF_slice_1(void) __attribute__((__used__));
static int realsmith_lIpsF_slice_1(void)
{
  int __retres;
  __retres = -1;
  return __retres;
}

int realsmith_tS6Qc_slice_1(void)
{
  int __retres;
  int buffer;
  buffer = 1;
  __retres = buffer;
  goto return_label;
  return_label: return __retres;
}

static int64_t g_101 = (int64_t)0x2FE49608984295ADLL;
static int64_t g_135[6] =
  {(int64_t)0xA5B0066401EE1831LL,
   (int64_t)0xA5B0066401EE1831LL,
   (int64_t)0xA5B0066401EE1831LL,
   (int64_t)0xA5B0066401EE1831LL,
   (int64_t)0xA5B0066401EE1831LL,
   (int64_t)0xA5B0066401EE1831LL};
static uint32_t g_175 = (uint32_t)0UL;
static int16_t g_203 = (int16_t)0x07C0L;
static uint16_t g_301 = (uint16_t)0xC571L;
static int32_t g_322 = (int32_t)0x4ACA4B36L;
static int16_t g_359 = (int16_t)0xB388L;
static int64_t * const g_440[9][1] =
  {{& g_101},
   {& g_135[4]},
   {& g_135[4]},
   {& g_101},
   {& g_135[4]},
   {& g_135[4]},
   {& g_101},
   {& g_135[4]},
   {& g_135[4]}};
static int64_t * const *g_439 = & g_440[2][0];
static uint32_t *g_1101 = & g_175;
static uint16_t *g_1235[6][6] =
  {{& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301},
   {& g_301, & g_301, & g_301, & g_301, & g_301, & g_301}};
static uint16_t **g_1234 = & g_1235[2][1];
static uint32_t **g_1447 = & g_1101;
static int32_t g_1648 = (int32_t)(-3L);
static int8_t g_1801 = (int8_t)0xECL;
static int32_t const *g_2215 = (int32_t const *)(& g_1648);
static int16_t *g_2774 = & g_203;
static int16_t **g_2773 = & g_2774;
static int16_t **g_2778 = & g_2774;
static int16_t const *g_3028 = (int16_t const *)(& g_359);
static int16_t const **g_3027 = & g_3028;
static int32_t const * const g_3919 = (int32_t const *)(& g_322);
static int8_t const *g_3936 = (int8_t const *)(& g_1801);
static int16_t * const * const **g_4404 = (int16_t * const * const **)0;
static int16_t * const * const ***g_4403 = & g_4404;
static void func_1_slice_1(void);

static void func_1_slice_1(void)
{
  uint64_t const l_4351[3] = {18446744073709551610UL,18446744073709551610UL,18446744073709551610UL};
  uint64_t tmp_80;
  int tmp_65;
  int16_t tmp_79;
  int tmp_78;
  int16_t tmp_64;
  uint16_t l_9 = (uint16_t)0x0CB8L;
  int32_t l_4276 = (int32_t)0xF414069CL;
  uint32_t l_4352 = (uint32_t)1UL;
  int64_t l_4430 = (int64_t)0xB4CCF6A44C2CC62DLL;
  uint8_t l_4432 = (uint8_t)0x35L;
  {
    int8_t tmp_58;
    int tmp_57;
    tmp_57 = 1;
    tmp_58 = safe_add_func_int8_t_s_s_slice_1((int8_t)((int16_t *)0 != *g_2773),
                                              (int8_t)tmp_57);
    l_4276 = (int32_t)tmp_58;
    goto break_cont_1;
  }
  break_cont_1:
  tmp_65 = realsmith_lIpsF_slice_1();
  tmp_78 = realsmith_tS6Qc_slice_1();
  *(*g_1234) = (uint16_t)((int)*(*g_1234) ^ (((((((tmp_78 + l_4276) + *g_2215) + (int)l_4352) + (int)l_4430) + (
                                               *g_3919 - 1254771510)) - 1278002734) + l_4276));
  tmp_79 = safe_rshift_func_int16_t_s_u_slice_1((int16_t)(! 6UL));
  tmp_80 = safe_sub_func_uint64_t_u_u_slice_1((uint64_t)tmp_79,
                                              (uint64_t)((int)((uint8_t)(
                                                         (((((tmp_65 + (int)l_4432) + (int)l_4352) + (int)l_9) + (int)l_4430) + (int)l_4351[1]) - 1278006036)) + (int)l_4432));
  tmp_64 = (int16_t)tmp_80;
  *(*g_2778) = tmp_64;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_203: %d\n", g_203);
  __retres = 0;
  return __retres;
}


