/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
struct S0 {
   int32_t f0 ;
   uint32_t f1 ;
   uint8_t const f2 ;
   int64_t f3 ;
   int16_t f4 ;
   int8_t f5 ;
   uint64_t const f6 ;
   int32_t const f7 ;
   int64_t f8 ;
};
long realsmith_7QoqD_slice_1(long const v, long const m)
{
  long __retres;
  long const r; // 未初始化的变量r
  printf("realsmith_7QoqD_slice_1调用: v=%ld, m=%ld, r(未初始化)=%ld\n", v, m, r);
  __retres = (v + m) - r;
  printf("realsmith_7QoqD_slice_1返回值: %ld\n", __retres);
  return __retres;
}

static int8_t safe_div_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static uint8_t safe_rshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint64_t safe_div_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  tmp = ui1 / ui2;
  return tmp;
}

static uint32_t g_7 = (uint32_t)4294967295UL;
static struct S0 *g_9 = (struct S0 *)0;
static int32_t g_29 = (int32_t)5L;
static int32_t * const g_28 = & g_29;
static int64_t g_380[8][2][4] =
  {{{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}}};
static uint32_t g_391 = (uint32_t)0xB19036ABL;
static struct S0 g_394 =
  {.f0 = (int32_t)0L,
   .f1 = (uint32_t)0x77997638L,
   .f2 = (uint8_t)255UL,
   .f3 = (int64_t)0x28089FA9871E9C7BLL,
   .f4 = (int16_t)0x902DL,
   .f5 = (int8_t)0xFDL,
   .f6 = (uint64_t)0xDE7C1975B9A4AED9LL,
   .f7 = (int32_t)0x64FAAABBL,
   .f8 = 0L};
static int8_t g_537 = (int8_t)0x96L;
static void func_1_slice_1(void);

static void func_2_slice_1(uint8_t p_3);

static void func_10_slice_1(void);

static void func_30_slice_1(void);

static void func_36_slice_1(int32_t p_37);

static void func_1_slice_1(void)
{
  func_10_slice_1();
  func_2_slice_1((uint8_t)(6L != (long)g_7));
  return;
}

static void func_2_slice_1(uint8_t p_3)
{
  func_36_slice_1((int32_t)((long)p_3 | 0x6F740F60L));
  return;
}

static void func_10_slice_1(void)
{
  func_36_slice_1(*g_28);
  func_30_slice_1();
  return;
}

static void func_30_slice_1(void)
{
  int32_t l_401 = (int32_t)(-6L);
  func_36_slice_1(l_401);
  return;
}

static void func_36_slice_1(int32_t p_37)
{
  uint8_t tmp_6;
  int8_t tmp_4;
  uint64_t tmp_3;
  long tmp_5;
  int16_t l_42 = (int16_t)(-1L);
  printf("--- func_36_slice_1开始 (p_37=%d) ---\n", p_37);
  tmp_3 = safe_div_func_uint64_t_u_u_slice_1((uint64_t)0x29BAD2CE6C1CC492LL,
                                             (uint64_t)(p_37 | 1));
  tmp_4 = safe_div_func_int8_t_s_s_slice_1((int8_t)tmp_3,(int8_t)(-5L));
  tmp_5 = realsmith_7QoqD_slice_1((long)g_537 + (long)187,
                                  (long)g_394.f0 + (long)64);
  tmp_6 = safe_rshift_func_uint8_t_u_u_slice_1((uint8_t)((int)((int16_t)(
                                                         ((((tmp_5 + (long)l_42) + (long)g_394.f0) + g_394.f8) + (long)g_537) - (long)21)) + (int)l_42),
                                               (unsigned int)tmp_4);
  g_391 ^= (unsigned int)tmp_6;
  
  // 添加打印语句以验证g_391的值
  printf("g_391: %u\n", g_391);
  printf("--- func_36_slice_1结束 ---\n");
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_391: %lu\n", (unsigned long)g_391);
  __retres = 0;
  return __retres;
}


