#include <stdio.h>
/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
struct S0 {
   int32_t f0 ;
   uint32_t f1 ;
   uint8_t const f2 ;
   int64_t f3 ;
   int16_t f4 ;
   int8_t f5 ;
   uint64_t const f6 ;
   int32_t const f7 ;
   int64_t f8 ;
};
static int8_t safe_div_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  int tmp;
  tmp = (int)si1 / (int)si2;
  __retres = (int8_t)tmp;
  return __retres;
}

static uint8_t safe_rshift_func_uint8_t_u_u_slice_1(uint8_t left,
                                                    unsigned int right)
{
  uint8_t __retres;
  int tmp;
  if (right >= (unsigned int)32) tmp = (int)left;
  else tmp = (int)left >> right;
  __retres = (uint8_t)tmp;
  return __retres;
}

static uint64_t safe_div_func_uint64_t_u_u_slice_1(uint64_t ui1, uint64_t ui2)
{
  uint64_t tmp;
  tmp = ui1 / ui2;
  return tmp;
}

static uint32_t g_7 = (uint32_t)4294967295UL;
static struct S0 *g_9 = (struct S0 *)0;
static int32_t g_29 = (int32_t)5L;
static int32_t * const g_28 = & g_29;
static struct S0 g_62 =
  {.f0 = (int32_t)0xFB07D6E1L,
   .f1 = (uint32_t)0xCCD29D3EL,
   .f2 = (uint8_t)246UL,
   .f3 = (int64_t)0x19AB6322A57D884BLL,
   .f4 = (int16_t)0L,
   .f5 = (int8_t)9L,
   .f6 = 0UL,
   .f7 = (int32_t)(-1L),
   .f8 = (int64_t)0xFA8187147D86C3CELL};
static uint16_t g_71 = (uint16_t)65526UL;
static int16_t g_118 = (int16_t)0x4DB2L;
static int16_t g_122 = (int16_t)(-1L);
static uint16_t g_238 = (uint16_t)65527UL;
static int16_t g_275 = (int16_t)0L;
static int8_t g_363 = (int8_t)0L;
static int16_t g_377 = (int16_t)(-1L);
static int16_t g_379 = (int16_t)(-10L);
static int64_t g_380[8][2][4] =
  {{{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}},
   {{(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL},
    {(int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL,
     (int64_t)0x96F2B2D53C59B481LL}}};
static uint32_t g_391 = (uint32_t)0xB19036ABL;
static struct S0 g_394 =
  {.f0 = (int32_t)0L,
   .f1 = (uint32_t)0x77997638L,
   .f2 = (uint8_t)255UL,
   .f3 = (int64_t)0x28089FA9871E9C7BLL,
   .f4 = (int16_t)0x902DL,
   .f5 = (int8_t)0xFDL,
   .f6 = (uint64_t)0xDE7C1975B9A4AED9LL,
   .f7 = (int32_t)0x64FAAABBL,
   .f8 = 0L};
static int16_t g_541 = (int16_t)(-2L);
static uint32_t g_544[7][2] =
  {{(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L},
   {(uint32_t)0xC7D90080L, (uint32_t)0xC7D90080L}};
static int8_t *g_756 = & g_363;
static void func_1_slice_1(void);

static void func_2_slice_1(uint8_t p_3);

static void func_10_slice_1(void);

static void func_30_slice_1(void);

static void func_36_slice_1(int32_t p_37);

static void func_1_slice_1(void)
{
  func_10_slice_1();
  func_2_slice_1((uint8_t)(6L != (long)g_7));
  return;
}

static void func_2_slice_1(uint8_t p_3)
{
  int16_t l_785;
  int tmp_30;
  int32_t tmp_25;
  int16_t *l_786[3][7][3] =
    {{{& g_275, & g_118, (int16_t *)0},
      {& g_379, (int16_t *)0, & l_785},
      {& g_118, & g_118, & g_394.f4},
      {& g_394.f4, (int16_t *)0, & l_785},
      {& g_275, & g_379, & g_379},
      {(int16_t *)0, & g_394.f4, (int16_t *)0},
      {& g_379, & g_275, & g_379}},
     {{& l_785, & l_785, & l_785},
      {& g_118, (int16_t *)0, & g_394.f4},
      {& g_394.f4, & g_394.f4, & g_394.f4},
      {& g_118, & l_785, & l_785},
      {& g_394.f4, & l_785, (int16_t *)0},
      {& g_118, (int16_t *)0, & g_118},
      {& l_785, (int16_t *)0, & g_394.f4}},
     {{& g_379, & g_394.f4, & g_122},
      {(int16_t *)0, (int16_t *)0, & g_541},
      {& g_275, (int16_t *)0, & g_377},
      {& g_394.f4, & l_785, & g_62.f4},
      {& g_118, & l_785, (int16_t *)0},
      {& g_62.f4, & g_394.f4, & g_62.f4},
      {& g_377, (int16_t *)0, & g_377}}};
  func_36_slice_1((int32_t)((long)p_3 | 0x6F740F60L));
  tmp_30 = 0;
  tmp_25 = tmp_30;
  *g_28 = tmp_25;
  *g_28 |= (int16_t *)0 == l_786[0][1][2];
  return;
}

static void func_10_slice_1(void)
{
  func_36_slice_1(*g_28);
  func_30_slice_1();
  return;
}

static void func_30_slice_1(void)
{
  int32_t l_401 = (int32_t)(-6L);
  g_238 = (uint16_t)l_401;
  func_36_slice_1(l_401);
  return;
}

static void func_36_slice_1(int32_t p_37)
{
  uint8_t tmp_4;
  int8_t tmp_3;
  uint64_t tmp_2;
  int16_t l_42 = (int16_t)(-1L);
  tmp_2 = safe_div_func_uint64_t_u_u_slice_1((uint64_t)0x29BAD2CE6C1CC492LL,
                                             (uint64_t)(p_37 | 1));
  tmp_3 = safe_div_func_int8_t_s_s_slice_1((int8_t)tmp_2,(int8_t)(-5L));
  tmp_4 = safe_rshift_func_uint8_t_u_u_slice_1((uint8_t)l_42,
                                               (unsigned int)tmp_3);
  g_391 ^= (unsigned int)tmp_4;
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_29: %d\n", g_29);
    printf("g_57: 未在切片中定义\n");
    printf("g_388: 未在切片中定义\n");
    printf("g_391: %lu\n", (unsigned long)g_391);
    printf("g_419: 未在切片中定义\n");
    printf("g_71: %u\n", (unsigned int)g_71);
    printf("g_238: %u\n", (unsigned int)g_238);

  __retres = 0;
  return __retres;
}


