#include <stdio.h>
/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
int F_BKS_realsmith_x6vp5 = -1;
int F_ORG_realsmith_x6vp5 = 11;
static unsigned int realsmith_x6vp5_slice_1(int cfg) __attribute__((__used__));
static unsigned int realsmith_x6vp5_slice_1(int cfg)
{
  unsigned int __retres;
  unsigned int width = (unsigned int)1;
  unsigned int banks =
    (unsigned int)(! (! (cfg & F_BKS_realsmith_x6vp5)) + 1);
  unsigned int org = (unsigned int)(! (! (cfg & F_ORG_realsmith_x6vp5)) + 1);
  unsigned int density = (unsigned int)1;
  unsigned int MBs =
    ((unsigned int)(256 << density) * banks) / (org << width);
  __retres = MBs << 20;
  return __retres;
}

int realsmith_g215Q_slice_1(void)
{
  int __retres;
  __retres = 0xffff;
  return __retres;
}

static int realsmith_n1fEL_slice_1(void) __attribute__((__used__));
static int realsmith_n1fEL_slice_1(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

static int realsmith_Vz588_slice_1(void) __attribute__((__used__));
static int realsmith_Vz588_slice_1(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int realsmith_proxy_E9Bwk_slice_1(char p_0_AYWNu)
{
  char proxy_L34qP[16] =
    {p_0_AYWNu,
     p_0_AYWNu,
     (char)42,
     p_0_AYWNu,
     p_0_AYWNu,
     p_0_AYWNu,
     p_0_AYWNu,
     (char)76,
     (char)42,
     p_0_AYWNu,
     (char)95,
     (char)21,
     (char)78,
     p_0_AYWNu,
     p_0_AYWNu,
     p_0_AYWNu};
  int proxy_ret_ouMlM = realsmith_Vz588_slice_1();
  return proxy_ret_ouMlM;
}

static unsigned long realsmith_tK4ee_slice_1(void) __attribute__((__used__));
static unsigned long realsmith_tK4ee_slice_1(void)
{
  unsigned long __retres;
  unsigned long n = (unsigned long)1;
  n += (unsigned long)2;
  __retres = n;
  return __retres;
}

unsigned long realsmith_proxy_KVzjr_slice_1(unsigned long p_2_HQv5V,
                                            unsigned long p_3_zJlFg)
{
  unsigned long proxy_ret_RJUbi = realsmith_tK4ee_slice_1();
  return proxy_ret_RJUbi;
}

int realsmith_SnIqT_slice_1(void)
{
  int i;
  int c;
  int n = 0;
  c = 1;
  i = 0;
  while (i < c) {
    n ++;
    i ++;
  }
  return n;
}

int realsmith_proxy_izldH_slice_1(void)
{
  int proxy_ret_JcRKK = realsmith_SnIqT_slice_1();
  return proxy_ret_JcRKK;
}

char const *realsmith_8KVHn_slice_1(void)
{
  char const *__retres;
  __retres = "U";
  return __retres;
}

char realsmith_proxy_bHUXO_slice_1(int p_0_RoezV)
{
  char __retres;
  char *proxy_ret_xswCa = realsmith_8KVHn_slice_1();
  __retres = *proxy_ret_xswCa;
  return __retres;
}

static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int32_t safe_sub_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static int64_t safe_add_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  if (si1 > (int64_t)0) goto _LAND_0;
  else {
    _LAND_0: ;
    tmp = si1 + si2;
  }
  return tmp;
}

static uint16_t safe_add_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t const g_6 = (uint8_t)1UL;
static int32_t g_38[7] =
  {(int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L};
static int64_t g_89 = 9L;
static int16_t g_101 = (int16_t)3L;
static int8_t g_106 = (int8_t)0xB6L;
static int32_t g_111 = (int32_t)0x7A7D0CF2L;
static uint32_t g_154 = (uint32_t)0x43B7CC5CL;
static int64_t *g_165 = & g_89;
static uint16_t g_206 = (uint16_t)0x09FBL;
static int64_t g_275[10][5] =
  {{(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L}};
static int16_t g_278 = (int16_t)0x67ACL;
static uint16_t g_327 = (uint16_t)65535UL;
static uint8_t g_335[1] = {(uint8_t)248UL};
static int32_t g_347 = (int32_t)0L;
static uint32_t g_388 = (uint32_t)0x74BA25DFL;
static uint64_t g_428 = (uint64_t)0x35123A7DBBA21B07LL;
static int32_t g_529[8] =
  {(int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L,
   (int32_t)0x845004E3L};
static uint32_t *g_714 = & g_388;
static int8_t *g_1195 = & g_106;
static int16_t g_1333 = (int16_t)1L;
static int8_t const g_1655 = (int8_t)(-7L);
static int32_t g_2348 = (int32_t)0xBCAFE1B8L;
static uint16_t g_2767[7][3] =
  {{(uint16_t)65535UL, (uint16_t)0x416DL, (uint16_t)65535UL},
   {(uint16_t)65535UL, (uint16_t)0xCE22L, (uint16_t)65535UL},
   {(uint16_t)0xF9E3L, (uint16_t)65535UL, (uint16_t)65535UL},
   {(uint16_t)65532UL, (uint16_t)65532UL, (uint16_t)0x4D99L},
   {(uint16_t)0x46FAL, (uint16_t)65535UL, (uint16_t)65535UL},
   {(uint16_t)0x4D99L, (uint16_t)0xCE22L, (uint16_t)0x6F32L},
   {(uint16_t)0x46FAL, (uint16_t)0x416DL, (uint16_t)0x46FAL}};
static int32_t g_2850 = (int32_t)(-1L);
static void func_1_slice_1(void);

static void func_21_slice_1(int8_t p_22, uint64_t const p_23);

static int32_t func_25_slice_1(int32_t p_26, uint16_t const p_27);

static void func_46_slice_1(void);

static void func_57_slice_1(void);

static void func_65_slice_1(uint32_t p_66);

static void func_1_slice_1(void)
{
  int16_t const l_36[1];
  int tmp_12;
  unsigned long tmp_1;
  int32_t tmp_7;
  int8_t tmp_5;
  int tmp_6;
  int32_t tmp_4;
  char tmp_13;
  uint32_t l_7 = (uint32_t)0UL;
  tmp_1 = realsmith_proxy_KVzjr_slice_1((unsigned long)l_36[0] + (unsigned long)(-8968),
                                        (unsigned long)l_36[0] + (unsigned long)(-9041));
  tmp_5 = safe_sub_func_int8_t_s_s_slice_1((int8_t)0xF0L,(int8_t)g_6);
  tmp_6 = realsmith_proxy_izldH_slice_1();
  tmp_4 = (int)g_6 | (((long long)((int)g_6 != (int)tmp_5) < 0x2A0C0E0752570E81LL) != 
                      (int)((uint8_t)((tmp_6 + (int)g_6) - 2)) + (int)g_6);
  tmp_7 = func_25_slice_1(tmp_4,(uint16_t)l_36[0]);
  func_21_slice_1((int8_t)((unsigned long)tmp_7 ^ 1UL),
                  (uint64_t)((int)((int16_t)((tmp_1 + (unsigned long)l_36[0]) - (unsigned long)9066)) + (int)l_36[0]));
  tmp_12 = 0;
  tmp_13 = realsmith_proxy_bHUXO_slice_1((int)l_7 + 80);
  *g_165 = safe_add_func_int64_t_s_s_slice_1((int64_t)((uint32_t)(((int)tmp_13 + (int)((char)l_7)) - 85) + l_7),
                                             (int64_t)tmp_12);
  return;
}

static void func_21_slice_1(int8_t p_22, uint64_t const p_23)
{
  uint32_t ***l_2342;
  uint32_t const ***l_2344;
  uint32_t const ****tmp_75;
  int tmp_76;
  int tmp_77;
  int16_t tmp_74;
  int8_t tmp_73;
  uint16_t *l_2328 = & g_206;
  uint32_t ****l_2341[8][10] =
    {{& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0}};
  uint32_t const ****l_2343 = & l_2344;
  int16_t l_2349 = (int16_t)0xA454L;
  int16_t *l_2350 = & g_101;
  *l_2328 = (uint16_t)5UL;
  tmp_75 = l_2343;
  tmp_76 = realsmith_g215Q_slice_1();
  tmp_77 = realsmith_n1fEL_slice_1();
  *g_165 |= (long)((((((tmp_76 + g_2348) + g_347) + (int)g_2767[2][1]) + (
                     (int)g_428 - -1147004153)) - -1129193042) + g_2348 >= 
                   (int)((int8_t)((tmp_77 + (int)p_22) - 1)) + (int)p_22);
  l_2349 = (int16_t)((long)l_2349 & *g_165);
  tmp_74 = (int16_t)(((void *)l_2341[7][4] == (void *)tmp_75) ^ (int)l_2349);
  *l_2350 = tmp_74;
  tmp_73 = (int8_t)((unsigned long)tmp_74 | p_23);
  *g_1195 = tmp_73;
  return;
}

static int32_t func_25_slice_1(int32_t p_26, uint16_t const p_27)
{
  func_65_slice_1((uint32_t)((unsigned long long)p_27 ^ 0x9239C2B513AA7A40LL));
  func_57_slice_1();
  func_46_slice_1();
  return p_26;
}

static void func_46_slice_1(void)
{
  unsigned int tmp_9;
  uint32_t l_1666 = (uint32_t)0x77C36663L;
  int32_t *l_1667 = & g_111;
  tmp_9 = realsmith_x6vp5_slice_1((int)l_1666 + -2009294396);
  *l_1667 = (int32_t)((uint32_t)((long)(tmp_9 + l_1666) - 2277729891) + l_1666);
  return;
}

static void func_57_slice_1(void)
{
  g_278 = (int16_t)(-16);
  while ((int)g_278 >= -20) {
    int32_t tmp;
    tmp = safe_sub_func_int32_t_s_s_slice_1((int32_t)g_278,5);
    g_278 = (int16_t)tmp;
  }
  return;
}

static void func_65_slice_1(uint32_t p_66)
{
  int tmp_231;
  uint16_t tmp_230;
  int tmp_229;
  uint32_t tmp_228;
  int64_t tmp_227;
  int32_t l_764 = (int32_t)0xAE417D81L;
  uint32_t *l_772 = & g_154;
  tmp_229 = realsmith_proxy_E9Bwk_slice_1((char)((int)((char)g_275[9][1]) + -35));
  tmp_230 = safe_add_func_uint16_t_u_u_slice_1((uint16_t)((((int64_t)(
                                                            (tmp_229 + (int)g_275[9][1]) - 1) + g_275[9][1]) ^ (long)l_764) & (long)g_335[0]),
                                               (uint16_t)p_66);
  tmp_228 = (uint32_t)tmp_230;
  *l_772 = tmp_228;
  tmp_231 = 1;
  tmp_227 = (int64_t)tmp_231;
  *g_165 = tmp_227;
  {
    uint32_t l_784;
    int32_t l_807;
    l_784 = (uint32_t)0;
    while (l_784 <= (uint32_t)4) {
      goto break_cont_1;
      break_cont_1: l_784 += (uint32_t)1;
    }
    l_807 = 0;
    while (l_807 < 6) {
      g_347 = -8;
      l_807 ++;
    }
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
    printf("g_106: %d\n", (int)g_106);
    printf("g_111: %d\n", g_111);
    printf("g_278: %d\n", (int)g_278);
    printf("g_89: %ld\n", (long)g_89);
    printf("g_101: %d\n", (int)g_101);
    printf("g_153: 未在切片中定义\n");
    printf("g_154: %lu\n", (unsigned long)g_154);
    printf("g_206: %u\n", (unsigned int)g_206);
    printf("g_327: %u\n", (unsigned int)g_327);
    printf("g_388: %lu\n", (unsigned long)g_388);
    printf("g_428: %lu\n", (unsigned long)g_428);
    printf("g_347: %d\n", g_347);
    printf("g_378: 未在切片中定义\n");
    printf("g_640: 未在切片中定义\n");

  __retres = 0;
  return __retres;
}


