/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int8_t safe_sub_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 - (int)si2);
  return __retres;
}

static int32_t safe_sub_func_int32_t_s_s_slice_1(int32_t si1, int32_t si2)
{
  int32_t tmp;
  tmp = si1 - si2;
  return tmp;
}

static int64_t safe_add_func_int64_t_s_s_slice_1(int64_t si1, int64_t si2)
{
  int64_t tmp;
  if (si1 > (int64_t)0) goto _LAND_0;
  else {
    _LAND_0: ;
    tmp = si1 + si2;
  }
  return tmp;
}

static uint16_t safe_add_func_uint16_t_u_u_slice_1(uint16_t ui1, uint16_t ui2)
{
  uint16_t __retres;
  __retres = (uint16_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t const g_6 = (uint8_t)1UL;
static int32_t g_38[7] =
  {(int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L,
   (int32_t)0x77DFCC86L};
static int64_t g_89 = 9L;
static int16_t g_101 = (int16_t)3L;
static int8_t g_106 = (int8_t)0xB6L;
static int32_t g_111 = (int32_t)0x7A7D0CF2L;
static uint32_t g_154 = (uint32_t)0x43B7CC5CL;
static int64_t *g_165 = & g_89;
static uint16_t g_206 = (uint16_t)0x09FBL;
static int64_t g_275[10][5] =
  {{(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L},
   {(int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL,
    (int64_t)0x8DD369A3BF34E4EBLL},
   {1L, 1L, 1L, 1L, 1L}};
static int16_t g_278 = (int16_t)0x67ACL;
static uint8_t g_335[1] = {(uint8_t)248UL};
static int32_t g_347 = (int32_t)0L;
static int8_t *g_1195 = & g_106;
static int16_t g_1333 = (int16_t)1L;
static int32_t g_2348 = (int32_t)0xBCAFE1B8L;
static int32_t g_2850 = (int32_t)(-1L);
static void func_1_slice_1(void);

static void func_21_slice_1(int8_t p_22, uint64_t const p_23);

static int32_t func_25_slice_1(int32_t p_26, uint16_t const p_27);

static void func_46_slice_1(void);

static void func_57_slice_1(void);

static void func_65_slice_1(uint32_t p_66);

static void func_1_slice_1(void)
{
  int16_t const l_36[1] = {0x2367L};
  int tmp_6;
  int32_t tmp_1;
  int8_t tmp_0;
  int32_t tmp;
  uint32_t l_7 = (uint32_t)0UL;
  tmp_0 = safe_sub_func_int8_t_s_s_slice_1((int8_t)0xF0L,(int8_t)g_6);
  tmp = (int)g_6 | (((long long)((int)g_6 != (int)tmp_0) < 0x2A0C0E0752570E81LL) != (int)g_6);
  tmp_1 = func_25_slice_1(tmp,(uint16_t)l_36[0]);
  func_21_slice_1((int8_t)((unsigned long)tmp_1 ^ 1UL),(uint64_t)l_36[0]);
  tmp_6 = 0;
  *g_165 = safe_add_func_int64_t_s_s_slice_1((int64_t)l_7,(int64_t)tmp_6);
  return;
}

static void func_21_slice_1(int8_t p_22, uint64_t const p_23)
{
  uint32_t ***l_2342;
  uint32_t const ***l_2344;
  uint32_t const ****tmp_70;
  int16_t tmp_69;
  int8_t tmp_68;
  uint16_t *l_2328 = & g_206;
  uint32_t ****l_2341[8][10] =
    {{& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0},
     {& l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0,
      & l_2342,
      & l_2342,
      & l_2342,
      (uint32_t ****)0,
      (uint32_t ****)0}};
  uint32_t const ****l_2343 = & l_2344;
  int16_t l_2349 = (int16_t)0xA454L;
  int16_t *l_2350 = & g_101;
  *l_2328 = (uint16_t)5UL;
  tmp_70 = l_2343;
  *g_165 |= (long)(g_2348 >= (int32_t)p_22);
  l_2349 = (int16_t)((long)l_2349 & *g_165);
  tmp_69 = (int16_t)(((void *)l_2341[7][4] == (void *)tmp_70) ^ (int)l_2349);
  *l_2350 = tmp_69;
  tmp_68 = (int8_t)((unsigned long)tmp_69 | p_23);
  *g_1195 = tmp_68;
  return;
}

static int32_t func_25_slice_1(int32_t p_26, uint16_t const p_27)
{
  func_65_slice_1((uint32_t)((unsigned long long)p_27 ^ 0x9239C2B513AA7A40LL));
  func_57_slice_1();
  func_46_slice_1();
  return p_26;
}

static void func_46_slice_1(void)
{
  uint32_t l_1666 = (uint32_t)0x77C36663L;
  int32_t *l_1667 = & g_111;
  *l_1667 = (int32_t)l_1666;
  return;
}

static void func_57_slice_1(void)
{
  g_278 = (int16_t)(-16);
  while ((int)g_278 >= -20) {
    int32_t tmp;
    tmp = safe_sub_func_int32_t_s_s_slice_1((int32_t)g_278,5);
    g_278 = (int16_t)tmp;
  }
  return;
}

static void func_65_slice_1(uint32_t p_66)
{
  int tmp_216;
  uint16_t tmp_215;
  uint32_t tmp_214;
  int64_t tmp_213;
  int32_t l_764 = (int32_t)0xAE417D81L;
  uint32_t *l_772 = & g_154;
  tmp_215 = safe_add_func_uint16_t_u_u_slice_1((uint16_t)((g_275[9][1] ^ (long)l_764) & (long)g_335[0]),
                                               (uint16_t)p_66);
  tmp_214 = (uint32_t)tmp_215;
  *l_772 = tmp_214;
  tmp_216 = 1;
  tmp_213 = (int64_t)tmp_216;
  *g_165 = tmp_213;
  {
    uint32_t l_784;
    int32_t l_807;
    l_784 = (uint32_t)0;
    while (l_784 <= (uint32_t)4) {
      goto break_cont_1;
      break_cont_1: l_784 += (uint32_t)1;
    }
    l_807 = 0;
    while (l_807 < 6) {
      g_347 = -8;
      l_807 ++;
    }
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  __retres = 0;
  return __retres;
}


