/* Generated by Frama-C */
#include "inttypes.h"
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int realsmith_32egx_slice_1(void) __attribute__((__used__));
static int realsmith_32egx_slice_1(void)
{
  int __retres;
  {
    int tmp;
    tmp = 1;
    __retres = tmp;
  }
  return __retres;
}

int realsmith_proxy_oaaAB_slice_1(int p_1_iwu9a, int p_3_5uwzy)
{
  int proxy_ret_nLjya = realsmith_32egx_slice_1();
  return proxy_ret_nLjya;
}

int TREE_UNORDERED_realsmith_srmb4 = 8;
static int realsmith_srmb4_slice_1(void) __attribute__((__used__));
static int realsmith_srmb4_slice_1(void)
{
  int __retres;
  __retres = TREE_UNORDERED_realsmith_srmb4;
  return __retres;
}

int realsmith_proxy_ZYxV8_slice_1(void)
{
  int proxy_ret_Ngza7 = realsmith_srmb4_slice_1();
  return proxy_ret_Ngza7;
}

static int realsmith_5OFdD_slice_1(void) __attribute__((__used__));
static int realsmith_5OFdD_slice_1(void)
{
  int ret;
  ret = 1;
  return ret;
}

int realsmith_proxy_d3qhy_slice_1(void)
{
  int proxy_ret_vTst0 = realsmith_5OFdD_slice_1();
  return proxy_ret_vTst0;
}

static int8_t safe_mul_func_int8_t_s_s_slice_1(int8_t si1, int8_t si2)
{
  int8_t __retres;
  __retres = (int8_t)((int)si1 * (int)si2);
  return __retres;
}

static int16_t safe_sub_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 - (int)si2);
  return __retres;
}

static int16_t safe_rshift_func_int16_t_s_s_slice_1(int16_t left, int right)
{
  int16_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left; else tmp = (int)left >> right;
  __retres = (int16_t)tmp;
  return __retres;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t safe_sub_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 - (int)ui2);
  return __retres;
}

static int8_t g_12 = (int8_t)0x8FL;
static uint8_t g_26 = (uint8_t)1UL;
static int32_t g_72[8][2][7] =
  {{{(int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L},
    {(int32_t)3L,
     (int32_t)3L,
     (int32_t)0xB3DAD933L,
     (int32_t)3L,
     (int32_t)3L,
     (int32_t)0xB3DAD933L,
     (int32_t)3L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L},
    {(int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)0xE46196C9L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L},
    {(int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L},
    {(int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L)}},
   {{(int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L},
    {(int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L}}};
static uint64_t g_78 = (uint64_t)0xDE0D780A8980DF3ALL;
static int32_t g_89 = (int32_t)0x0C122BDAL;
static int64_t g_108 = (int64_t)0x69E62AD52EBB0BE5LL;
static uint32_t g_111 = (uint32_t)0xCF28406AL;
static int64_t g_115 = -6L;
static int32_t g_169 = (int32_t)(-7L);
static int64_t const g_248 = (int64_t)0x6235A88E17929216LL;
static uint32_t *g_273 = & g_111;
static uint32_t **g_272 = & g_273;
static uint8_t g_280 = (uint8_t)255UL;
static uint8_t *g_328 = (uint8_t *)0;
static uint8_t g_330 = (uint8_t)0x0BL;
static int64_t const *g_394 = (int64_t const *)(& g_108);
static int32_t *g_398 = & g_169;
static int32_t **g_397 = & g_398;
static int32_t ***g_396 = & g_397;
static int16_t g_404[3] = {(int16_t)(-1L), (int16_t)(-1L), (int16_t)(-1L)};
static uint64_t g_418 = (uint64_t)0x49C35A51F451565ELL;
static int8_t g_542 = (int8_t)0L;
static uint8_t g_578[1][6][5] =
  {{{(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL},
    {(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL},
    {(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL}}};
static int8_t *g_716 = & g_542;
static int8_t **g_715 = & g_716;
static uint16_t *g_794 = (uint16_t *)0;
static uint16_t **g_793 = & g_794;
static uint16_t ***g_792[2][4] =
  {{& g_793, & g_793, & g_793, & g_793}, {& g_793, & g_793, & g_793, & g_793}};
static uint16_t ***g_796[7][3] =
  {{(uint16_t ***)0, (uint16_t ***)0, & g_793},
   {(uint16_t ***)0, & g_793, (uint16_t ***)0},
   {(uint16_t ***)0, & g_793, & g_793},
   {& g_793, & g_793, & g_793},
   {(uint16_t ***)0, (uint16_t ***)0, & g_793},
   {(uint16_t ***)0, & g_793, (uint16_t ***)0},
   {(uint16_t ***)0, & g_793, & g_793}};
static int8_t g_979[2] = {(int8_t)0x43L, (int8_t)0x43L};
static uint16_t ****g_1016 = & g_796[0][1];
static uint16_t *****g_1015 = & g_1016;
static int16_t g_1017 = (int16_t)0L;
static int32_t const *g_1056 = (int32_t const *)(& g_169);
static int32_t const * const *g_1055 = (int32_t const * const *)(& g_1056);
static uint64_t g_1200 = 6UL;
static int16_t g_1343 = (int16_t)(-8L);
static int16_t g_1520[10][10] =
  {{(int16_t)(-1L),
    (int16_t)(-7L),
    (int16_t)0L,
    (int16_t)(-7L),
    (int16_t)(-1L),
    (int16_t)0xF73FL,
    (int16_t)0L,
    (int16_t)0xF73FL,
    (int16_t)(-1L),
    (int16_t)(-7L)},
   {(int16_t)0xA4D5L,
    (int16_t)(-7L),
    (int16_t)0xA4D5L,
    (int16_t)0x804EL,
    (int16_t)0x38E1L,
    (int16_t)(-7L),
    (int16_t)0x38E1L,
    (int16_t)0x804EL,
    (int16_t)0xA4D5L,
    (int16_t)(-7L)},
   {(int16_t)(-1L),
    (int16_t)0x804EL,
    (int16_t)1L,
    (int16_t)0x8634L,
    (int16_t)(-1L),
    (int16_t)0x8634L,
    (int16_t)1L,
    (int16_t)0x804EL,
    (int16_t)(-1L),
    (int16_t)0x804EL},
   {(int16_t)0x38E1L,
    (int16_t)0x8634L,
    (int16_t)0xA4D5L,
    (int16_t)0xF73FL,
    (int16_t)0xA4D5L,
    (int16_t)0x8634L,
    (int16_t)0x38E1L,
    (int16_t)0xF73FL,
    (int16_t)0x38E1L,
    (int16_t)0x8634L},
   {(int16_t)(-1L),
    (int16_t)0xF73FL,
    (int16_t)0L,
    (int16_t)0xF73FL,
    (int16_t)(-1L),
    (int16_t)(-7L),
    (int16_t)0L,
    (int16_t)(-7L),
    (int16_t)(-1L),
    (int16_t)0xF73FL},
   {(int16_t)0xA4D5L,
    (int16_t)0xF73FL,
    (int16_t)0xA4D5L,
    (int16_t)0x8634L,
    (int16_t)0x38E1L,
    (int16_t)0xF73FL,
    (int16_t)0x38E1L,
    (int16_t)0x8634L,
    (int16_t)0xA4D5L,
    (int16_t)0xF73FL},
   {(int16_t)(-1L),
    (int16_t)0x8634L,
    (int16_t)1L,
    (int16_t)0x804EL,
    (int16_t)(-1L),
    (int16_t)0x804EL,
    (int16_t)1L,
    (int16_t)0x8634L,
    (int16_t)(-1L),
    (int16_t)0x8634L},
   {(int16_t)0x38E1L,
    (int16_t)0x804EL,
    (int16_t)0xA4D5L,
    (int16_t)(-7L),
    (int16_t)0xA4D5L,
    (int16_t)0x804EL,
    (int16_t)0x38E1L,
    (int16_t)(-7L),
    (int16_t)0x38E1L,
    (int16_t)0x804EL},
   {(int16_t)(-1L),
    (int16_t)(-7L),
    (int16_t)0L,
    (int16_t)(-7L),
    (int16_t)(-1L),
    (int16_t)0xF73FL,
    (int16_t)0L,
    (int16_t)0xF73FL,
    (int16_t)(-1L),
    (int16_t)(-7L)},
   {(int16_t)0xA4D5L,
    (int16_t)(-7L),
    (int16_t)0xA4D5L,
    (int16_t)0x804EL,
    (int16_t)0x38E1L,
    (int16_t)(-7L),
    (int16_t)0x38E1L,
    (int16_t)0x804EL,
    (int16_t)0xA4D5L,
    (int16_t)(-7L)}};
static int16_t g_1720[7] =
  {(int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL};
static uint64_t g_1825 = 18446744073709551608UL;
static int32_t *g_2040 = & g_72[5][1][1];
static uint64_t g_2138 = (uint64_t)0x343A8CBE63047B7DLL;
static uint16_t g_2345 = (uint16_t)0x99E8L;
static uint8_t *g_2609 = & g_578[0][0][1];
static uint32_t g_3203[7][8] =
  {{(uint32_t)0UL,
    (uint32_t)7UL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)1UL,
    (uint32_t)0UL,
    (uint32_t)18446744073709551611UL,
    (uint32_t)0UL,
    (uint32_t)1UL},
   {(uint32_t)0UL,
    (uint32_t)18446744073709551611UL,
    (uint32_t)0UL,
    (uint32_t)1UL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)7UL,
    (uint32_t)0UL,
    (uint32_t)0UL},
   {(uint32_t)18446744073709551615UL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)18446744073709551614UL,
    (uint32_t)7UL,
    (uint32_t)7UL,
    (uint32_t)18446744073709551614UL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)18446744073709551615UL},
   {(uint32_t)18446744073709551615UL,
    (uint32_t)1UL,
    (uint32_t)0x9751EBDBL,
    (uint32_t)0UL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)0x9A3F4544L,
    (uint32_t)18446744073709551614UL,
    (uint32_t)0x9A3F4544L},
   {(uint32_t)0UL,
    (uint32_t)0UL,
    (uint32_t)0UL,
    (uint32_t)0UL,
    (uint32_t)0UL,
    (uint32_t)0x9A3F4544L,
    (uint32_t)18446744073709551611UL,
    (uint32_t)0xFA6A389DL},
   {(uint32_t)0UL,
    (uint32_t)1UL,
    (uint32_t)0UL,
    (uint32_t)1UL,
    (uint32_t)18446744073709551614UL,
    (uint32_t)18446744073709551614UL,
    (uint32_t)1UL,
    (uint32_t)0UL},
   {(uint32_t)0xFA6A389DL,
    (uint32_t)0xFA6A389DL,
    (uint32_t)0UL,
    (uint32_t)18446744073709551615UL,
    (uint32_t)0x9751EBDBL,
    (uint32_t)7UL,
    (uint32_t)18446744073709551611UL,
    (uint32_t)0UL}};
static int32_t g_3356 = (int32_t)(-1L);
static int8_t g_3560 = (int8_t)(-4L);
static uint64_t const *g_4244 = (uint64_t const *)(& g_2138);
static uint64_t const **g_4243 = & g_4244;
static void func_1_slice_1(void);

static void func_8_slice_1(void);

static void func_27_slice_1(void);

static void func_30_slice_1(int64_t p_32);

static void func_48_slice_1(uint8_t *p_50, uint32_t p_51);

static void func_53_slice_1(void);

static void func_64_slice_1(uint64_t p_66);

static void func_1_slice_1(void)
{
  int32_t l_33 = (int32_t)0x88FF7673L;
  func_30_slice_1((int64_t)l_33);
  func_27_slice_1();
  func_8_slice_1();
  return;
}

static void func_8_slice_1(void)
{
  int16_t tmp_53;
  uint64_t tmp_37;
  int32_t *l_4788 = & g_169;
  uint64_t *l_4817 = & g_1200;
  uint64_t *l_4821 = & g_78;
  tmp_53 = safe_rshift_func_int16_t_s_s_slice_1((int16_t)0x94ABL,*l_4788);
  *l_4817 |= (unsigned long)((long)tmp_53 < 4L);
  tmp_37 = *l_4817;
  *l_4821 = tmp_37;
  return;
}

static void func_27_slice_1(void)
{
  int32_t *l_3383 = & g_89;
  g_1825 = (uint64_t)0;
  g_542 = (int8_t)0;
  {
    int8_t *** const l_3390[9] = {& g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715};
    int32_t tmp_20;
    tmp_20 = l_3390[8] != & g_715;
    *l_3383 = tmp_20;
    goto return_label;
  }
  return_label: return;
}

static void func_30_slice_1(int64_t p_32)
{
  int tmp_9;
  int tmp_7;
  uint32_t l_42 = (uint32_t)1UL;
  uint8_t *l_329 = & g_330;
  int8_t *l_2239 = & g_979[1];
  tmp_7 = realsmith_proxy_d3qhy_slice_1();
  func_64_slice_1((uint64_t)((int)((int8_t)((((tmp_7 + (int)g_12) + (int)g_1825) + (int)g_3203[6][4]) - -1756239005)) + (int)g_12));
  func_53_slice_1();
  tmp_9 = 1;
  *l_2239 = (int8_t)((int)*l_2239 ^ tmp_9);
  func_48_slice_1((uint8_t *)l_2239,(uint32_t)g_1017);
  return;
}

static void func_48_slice_1(uint8_t *p_50, uint32_t p_51)
{
  *p_50 = (uint8_t)((int)*p_50 + 1);
  g_108 = (int64_t)3;
  {
    int32_t l_2278;
    int32_t l_2290;
    int tmp_91;
    tmp_91 = 1;
    l_2278 = tmp_91;
    l_2290 = l_2278;
    *p_50 = (uint8_t)((int)*p_50 | l_2290);
    g_115 = (int64_t)0;
    while (g_115 <= (int64_t)1) {
      *p_50 = (uint8_t)((long)*p_50 & 0x39L);
      g_169 = 0;
      while (g_169 <= 1) {
        {
          uint8_t tmp_30;
          uint8_t tmp_29;
          int tmp_25;
          int16_t tmp_28;
          int tmp_27;
          uint8_t tmp_26;
          uint64_t l_2344[9] =
            {18446744073709551615UL,
             1UL,
             18446744073709551615UL,
             18446744073709551615UL,
             1UL,
             18446744073709551615UL,
             18446744073709551615UL,
             1UL,
             18446744073709551615UL};
          tmp_25 = realsmith_proxy_ZYxV8_slice_1();
          tmp_27 = realsmith_proxy_oaaAB_slice_1((int)l_2344[1] + 44,
                                                 (int)l_2344[1] + 69);
          tmp_28 = safe_sub_func_int16_t_s_s_slice_1((int16_t)0x2541L,
                                                     (int16_t)((uint64_t)(
                                                               (tmp_27 + (int)l_2344[1]) - 2) + l_2344[1]));
          tmp_26 = (uint8_t)(((int)tmp_28 == (int)g_979[g_115]) > *(*g_1055));
          tmp_29 = safe_add_func_uint8_t_u_u_slice_1(tmp_26,
                                                     (uint8_t)((int)((uint8_t)(
                                                               ((((tmp_25 + (int)*p_50) + (int)p_51) + (int)*g_273) + (int)g_1720[0]) - 10824)) + (int)*p_50));
          tmp_30 = safe_sub_func_uint8_t_u_u_slice_1(tmp_29,*p_50);
          g_2345 = (uint16_t)tmp_30;
        }
        g_169 ++;
      }
      g_115 += (int64_t)1;
    }
    g_1200 = (uint64_t)0;
    goto return_label;
  }
  return_label: return;
}

static void func_53_slice_1(void)
{
  int32_t ****l_2105;
  int32_t ** const *l_2107 = & g_397;
  uint32_t tmp_14;
  int32_t ** const **l_2106 = & l_2107;
  l_2105 = & g_396;
  tmp_14 = (uint32_t)((void *)l_2105 != (void *)l_2106);
  *(*g_272) = tmp_14;
  g_418 = (uint64_t)(-27);
  return;
}

static void func_64_slice_1(uint64_t p_66)
{
  int32_t l_70[9][2][6] =
    {{{(int32_t)0x5737FB64L,
       (int32_t)6L,
       (int32_t)0xC8520716L,
       (int32_t)0xE2B1956AL,
       (int32_t)(-2L),
       (int32_t)0L},
      {(int32_t)(-2L),
       (int32_t)(-10L),
       (int32_t)0x9E77F559L,
       (int32_t)1L,
       (int32_t)(-1L),
       (int32_t)0xC8520716L}},
     {{(int32_t)6L,
       (int32_t)(-5L),
       (int32_t)0x9E77F559L,
       (int32_t)(-5L),
       (int32_t)6L,
       (int32_t)0L},
      {(int32_t)0xDABEE07FL,
       (int32_t)(-1L),
       (int32_t)0xC8520716L,
       (int32_t)0x5F634C5DL,
       (int32_t)(-10L),
       (int32_t)0x8CC907F7L}},
     {{(int32_t)(-1L),
       (int32_t)8L,
       (int32_t)0xE2B1956AL,
       (int32_t)0x4A98A1BDL,
       (int32_t)(-1L),
       (int32_t)0xE2B1956AL},
      {(int32_t)0x36FDE002L,
       (int32_t)0x0146BFE2L,
       (int32_t)0x5F634C5DL,
       (int32_t)(-8L),
       (int32_t)0x4A98A1BDL,
       (int32_t)(-2L)}},
     {{(int32_t)(-1L),
       (int32_t)0x72231B3DL,
       (int32_t)(-10L),
       (int32_t)0xBF646D91L,
       (int32_t)8L,
       (int32_t)0x5F634C5DL},
      {(int32_t)0x993C4D98L,
       (int32_t)0L,
       (int32_t)(-10L),
       (int32_t)0x4A98A1BDL,
       (int32_t)0x0146BFE2L,
       (int32_t)(-2L)}},
     {{(int32_t)0x796FB6C7L,
       (int32_t)(-1L),
       (int32_t)0x5F634C5DL,
       (int32_t)0xB3A04BB8L,
       (int32_t)0x72231B3DL,
       (int32_t)0xE2B1956AL},
      {(int32_t)0xB3A04BB8L,
       (int32_t)0x72231B3DL,
       (int32_t)0xE2B1956AL,
       (int32_t)0L,
       (int32_t)0L,
       (int32_t)0xE2B1956AL}},
     {{(int32_t)0x993C4D98L,
       (int32_t)0x993C4D98L,
       (int32_t)0x5F634C5DL,
       (int32_t)8L,
       (int32_t)(-1L),
       (int32_t)(-2L)},
      {(int32_t)0x4A98A1BDL,
       (int32_t)(-4L),
       (int32_t)(-10L),
       (int32_t)(-8L),
       (int32_t)0x72231B3DL,
       (int32_t)0x5F634C5DL}},
     {{(int32_t)0x0146BFE2L,
       (int32_t)0x4A98A1BDL,
       (int32_t)(-10L),
       (int32_t)0L,
       (int32_t)0x993C4D98L,
       (int32_t)(-2L)},
      {(int32_t)(-1L),
       (int32_t)0L,
       (int32_t)0x5F634C5DL,
       (int32_t)0x796FB6C7L,
       (int32_t)(-4L),
       (int32_t)0xE2B1956AL}},
     {{(int32_t)0x796FB6C7L,
       (int32_t)(-4L),
       (int32_t)0xE2B1956AL,
       (int32_t)(-1L),
       (int32_t)0x4A98A1BDL,
       (int32_t)0xE2B1956AL},
      {(int32_t)0x0146BFE2L,
       (int32_t)0x36FDE002L,
       (int32_t)0x5F634C5DL,
       (int32_t)0xBF646D91L,
       (int32_t)0L,
       (int32_t)(-2L)}},
     {{(int32_t)0L,
       (int32_t)8L,
       (int32_t)(-10L),
       (int32_t)8L,
       (int32_t)(-4L),
       (int32_t)0x5F634C5DL},
      {(int32_t)0x36FDE002L,
       (int32_t)(-1L),
       (int32_t)(-10L),
       (int32_t)(-1L),
       (int32_t)0x36FDE002L,
       (int32_t)(-2L)}}};
  p_66 = (uint64_t)0;
  while (p_66 <= (uint64_t)1) {
    {
      int32_t *l_71[7][3][1];
      uint8_t l_73;
      int32_t **l_76[10];
      int i_0;
      int j_0;
      int k_0;
      int32_t ***l_87 = & l_76[8];
      i_0 = 0;
      while (i_0 < 7) {
        j_0 = 0;
        while (j_0 < 3) {
          k_0 = 0;
          while (k_0 < 1) {
            l_71[i_0][j_0][k_0] = & g_72[5][1][1];
            k_0 ++;
          }
          j_0 ++;
        }
        i_0 ++;
      }
      i_0 = 0;
      while (i_0 < 10) {
        l_76[i_0] = & l_71[3][1][0];
        i_0 ++;
      }
      g_72[5][1][1] = (int32_t)p_66;
      l_73 = (uint8_t)0;
      while ((int)l_73 <= 1) {
        {
          int32_t l_88;
          uint32_t l_112 = (uint32_t)0UL;
          if (g_72[5][1][1]) goto __Cont;
          l_88 = 1;
          while (l_88 >= 0) {
            g_78 = (uint64_t)0;
            while (g_78 <= (uint64_t)1) {
              *(*(*l_87)) = l_70[g_78 + (uint64_t)7][l_73][p_66 + (uint64_t)3];
              g_89 = 0;
              while (g_89 <= 1) {
                {
                  int8_t tmp_6;
                  tmp_6 = safe_mul_func_int8_t_s_s_slice_1((int8_t)(p_66 != 0UL),
                                                           (int8_t)l_112);
                  g_72[5][1][1] = (int32_t)tmp_6;
                }
                g_89 ++;
              }
              g_78 += (uint64_t)1;
            }
            l_88 --;
          }
        }
        __Cont: l_73 = (uint8_t)((int)l_73 + 1);
      }
    }
    p_66 += (uint64_t)1;
  }
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_89: %d\n", g_89);
  __retres = 0;
  return __retres;
}


