/* Generated by Frama-C */
#include "math.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "string.h"
static int16_t safe_sub_func_int16_t_s_s_slice_1(int16_t si1, int16_t si2)
{
  int16_t __retres;
  __retres = (int16_t)((int)si1 - (int)si2);
  return __retres;
}

static int16_t safe_rshift_func_int16_t_s_s_slice_1(int16_t left, int right)
{
  int16_t __retres;
  int tmp;
  if ((int)left < 0) tmp = (int)left;
  else 
    if (right < 0) tmp = (int)left; else tmp = (int)left >> right;
  __retres = (int16_t)tmp;
  return __retres;
}

static uint8_t safe_add_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 + (int)ui2);
  return __retres;
}

static uint8_t safe_sub_func_uint8_t_u_u_slice_1(uint8_t ui1, uint8_t ui2)
{
  uint8_t __retres;
  __retres = (uint8_t)((int)ui1 - (int)ui2);
  return __retres;
}

static int8_t g_12 = (int8_t)0x8FL;
static uint8_t g_26 = (uint8_t)1UL;
static int32_t g_72[8][2][7] =
  {{{(int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L},
    {(int32_t)3L,
     (int32_t)3L,
     (int32_t)0xB3DAD933L,
     (int32_t)3L,
     (int32_t)3L,
     (int32_t)0xB3DAD933L,
     (int32_t)3L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L},
    {(int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)0xE46196C9L,
     (int32_t)0x7656207CL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L},
    {(int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L}},
   {{(int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)3L,
     (int32_t)1L,
     (int32_t)0x7656207CL,
     (int32_t)1L},
    {(int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L)}},
   {{(int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L},
    {(int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L),
     (int32_t)(-2L),
     (int32_t)3L,
     (int32_t)(-2L)}},
   {{(int32_t)1L,
     (int32_t)0xEA99669DL,
     (int32_t)0xE46196C9L,
     (int32_t)3L,
     (int32_t)0xE46196C9L,
     (int32_t)0xEA99669DL,
     (int32_t)1L},
    {(int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L,
     (int32_t)(-2L),
     (int32_t)0xB3DAD933L,
     (int32_t)0xB3DAD933L}}};
static uint64_t g_78 = (uint64_t)0xDE0D780A8980DF3ALL;
static int32_t g_89 = (int32_t)0x0C122BDAL;
static int64_t g_108 = (int64_t)0x69E62AD52EBB0BE5LL;
static uint32_t g_111 = (uint32_t)0xCF28406AL;
static int64_t g_115 = -6L;
static int32_t g_169 = (int32_t)(-7L);
static uint32_t *g_273 = & g_111;
static uint32_t **g_272 = & g_273;
static uint8_t g_330 = (uint8_t)0x0BL;
static int32_t *g_398 = & g_169;
static int32_t **g_397 = & g_398;
static int32_t ***g_396 = & g_397;
static uint64_t g_418 = (uint64_t)0x49C35A51F451565ELL;
static int8_t g_542 = (int8_t)0L;
static uint8_t g_578[1][6][5] =
  {{{(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL},
    {(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL},
    {(uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL, (uint8_t)5UL},
    {(uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL, (uint8_t)0UL}}};
static int8_t *g_716 = & g_542;
static int8_t **g_715 = & g_716;
static uint16_t *g_794 = (uint16_t *)0;
static uint16_t **g_793 = & g_794;
static uint16_t ***g_792[2][4] =
  {{& g_793, & g_793, & g_793, & g_793}, {& g_793, & g_793, & g_793, & g_793}};
static uint16_t ***g_796[7][3] =
  {{(uint16_t ***)0, (uint16_t ***)0, & g_793},
   {(uint16_t ***)0, & g_793, (uint16_t ***)0},
   {(uint16_t ***)0, & g_793, & g_793},
   {& g_793, & g_793, & g_793},
   {(uint16_t ***)0, (uint16_t ***)0, & g_793},
   {(uint16_t ***)0, & g_793, (uint16_t ***)0},
   {(uint16_t ***)0, & g_793, & g_793}};
static int8_t g_979[2] = {(int8_t)0x43L, (int8_t)0x43L};
static uint16_t ****g_1016 = & g_796[0][1];
static uint16_t *****g_1015 = & g_1016;
static int16_t g_1017 = (int16_t)0L;
static int32_t const *g_1056 = (int32_t const *)(& g_169);
static int32_t const * const *g_1055 = (int32_t const * const *)(& g_1056);
static uint64_t g_1200 = 6UL;
static int16_t g_1720[7] =
  {(int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL,
   (int16_t)0x2A3EL};
static uint64_t g_1825 = 18446744073709551608UL;
static int32_t *g_2040 = & g_72[5][1][1];
static uint64_t g_2138 = (uint64_t)0x343A8CBE63047B7DLL;
static uint16_t g_2345 = (uint16_t)0x99E8L;
static uint8_t *g_2609 = & g_578[0][0][1];
static int32_t g_3356 = (int32_t)(-1L);
static uint64_t const *g_4244 = (uint64_t const *)(& g_2138);
static uint64_t const **g_4243 = & g_4244;
static void func_1_slice_1(void);

static void func_8_slice_1(void);

static void func_27_slice_1(void);

static void func_30_slice_1(void);

static void func_48_slice_1(uint8_t *p_50);

static void func_53_slice_1(void);

static void func_1_slice_1(void)
{
  int32_t l_33 = (int32_t)0x88FF7673L;
  func_30_slice_1();
  func_27_slice_1();
  func_8_slice_1();
  return;
}

static void func_8_slice_1(void)
{
  int16_t tmp_48;
  uint64_t tmp_36;
  int32_t *l_4788 = & g_169;
  uint64_t *l_4817 = & g_1200;
  uint64_t *l_4821 = & g_78;
  tmp_48 = safe_rshift_func_int16_t_s_s_slice_1((int16_t)0x94ABL,*l_4788);
  *l_4817 |= (unsigned long)((long)tmp_48 < 4L);
  tmp_36 = *l_4817;
  *l_4821 = tmp_36;
  return;
}

static void func_27_slice_1(void)
{
  int32_t *l_3383 = & g_89;
  g_1825 = (uint64_t)0;
  g_542 = (int8_t)0;
  {
    int8_t *** const l_3390[9] = {& g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715, & g_715};
    int32_t tmp_20;
    tmp_20 = l_3390[8] != & g_715;
    *l_3383 = tmp_20;
    goto return_label;
  }
  return_label: return;
}

static void func_30_slice_1(void)
{
  int tmp_5;
  uint8_t *l_329 = & g_330;
  int8_t *l_2239 = & g_979[1];
  func_53_slice_1();
  tmp_5 = 1;
  *l_2239 = (int8_t)((int)*l_2239 ^ tmp_5);
  func_48_slice_1((uint8_t *)l_2239);
  return;
}

static void func_48_slice_1(uint8_t *p_50)
{
  *p_50 = (uint8_t)((int)*p_50 + 1);
  g_108 = (int64_t)3;
  {
    int32_t l_2278;
    int32_t l_2290;
    int tmp_65;
    tmp_65 = 1;
    l_2278 = tmp_65;
    l_2290 = l_2278;
    *p_50 = (uint8_t)((int)*p_50 | l_2290);
    g_115 = (int64_t)0;
    while (g_115 <= (int64_t)1) {
      *p_50 = (uint8_t)((long)*p_50 & 0x39L);
      g_169 = 0;
      while (g_169 <= 1) {
        {
          uint8_t tmp_24;
          uint8_t tmp_23;
          int16_t tmp_22;
          uint8_t tmp_21;
          uint64_t l_2344[9] =
            {18446744073709551615UL,
             1UL,
             18446744073709551615UL,
             18446744073709551615UL,
             1UL,
             18446744073709551615UL,
             18446744073709551615UL,
             1UL,
             18446744073709551615UL};
          tmp_22 = safe_sub_func_int16_t_s_s_slice_1((int16_t)0x2541L,
                                                     (int16_t)l_2344[1]);
          tmp_21 = (uint8_t)(((int)tmp_22 == (int)g_979[g_115]) > *(*g_1055));
          tmp_23 = safe_add_func_uint8_t_u_u_slice_1(tmp_21,*p_50);
          tmp_24 = safe_sub_func_uint8_t_u_u_slice_1(tmp_23,*p_50);
          g_2345 = (uint16_t)tmp_24;
        }
        g_169 ++;
      }
      g_115 += (int64_t)1;
    }
    g_1200 = (uint64_t)0;
    goto return_label;
  }
  return_label: return;
}

static void func_53_slice_1(void)
{
  int32_t ****l_2105;
  int32_t ** const *l_2107 = & g_397;
  uint32_t tmp_13;
  int32_t ** const **l_2106 = & l_2107;
  l_2105 = & g_396;
  tmp_13 = (uint32_t)((void *)l_2105 != (void *)l_2106);
  *(*g_272) = tmp_13;
  g_418 = (uint64_t)(-27);
  return;
}

int main(void)
{
  int __retres;
  func_1_slice_1();
  printf("g_89: %d\n", g_89);
  __retres = 0;
  return __retres;
}


