/* Generated by Frama-C */
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "unistd.h"
int main(void)
{
  int __retres;
  pid_t tmp;
  tmp = getpid();
  uint32_t x = (uint32_t)tmp;
  x = x * 33U ^ 0x5AU;
  __retres = (int)(x & 0xFFU);
  return __retres;
}


